### ISSUE TITLE
Moving a file in the project should offer to move the type

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#1035]
If the user drags and drops a file inside the project, we should offer to move the types in the file to the new namespace. Example:

`Project/Foo/Bar.cs` (contains type `Foo.Bar`) -> `Project/Baz/Bar.cs` (prompt to move `Foo.Bar` to `Baz.Bar`)

**Comment by ocallesp** [comment]
Similar issue #5372 In here there are some comments that in CPS we need some medatada. Let me ask this question in today's meeting.

In CPS we handle part of the file move in:
namespace Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode
But this place looks generic for the specific case when FileMove to rename namespace.

Another place is DocumentManager.cs after RenameDocument()

@ryzngard What is expected in the Ux ? 
should we ask the user if he wants to rename the namespace using a dialog box [yes/no] ?
The namespace rename should be something offered/handled by codefixes ?

It seems this should be handled in Donet ProjectSystem, and get a notification after the move was successfully applied.

**Comment by ryzngard** [comment]
If we add the option as a checkbox to this dialog (default checked) that might be good. The downside is I think we'd want to remove the "Never prompt before moving files to a new location" option in the dialog, since we're attaching some action to it now instead of just letting the user know information. 

Maybe like this? 

![image](https://user-images.githubusercontent.com/475144/90052790-813dd000-dc8e-11ea-8da4-f50a747399b4.png)

**Comment by jjmew** [comment]
@ryzngard and @ocallesp  take a look at [this ticket](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1144262). I think that should be considered.
