### ISSUE TITLE
Including files outside the project cone don't show up in soln explorer

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1233]
CPS made a change to not show the files outside the project cone to avoid showing some packages that were including files from the nuget packages directory. However if projects include file either using globs or directly then they don't show up in soln explorer. For individual files, adding the Link metadata helps but it's not possible to do that for globs.

Tagging @lifengl @jviau @adrianvmsft

**Comment by srivatsn** [comment]
Tagging @onovotny

**Comment by onovotny** [comment]
More than that, I don't want the files to show as links...they're files. Basically, if an out of project thing (nuget reference) include comes from something outside my project, I don't need to see it -- but if my csproj has it, I want to see it.

**Comment by adrianvmsft** [comment]
Because it is too risky to change *how* we display items in the project tree for the RTM, we are considering finding an alternate solution that would limit *when* we display such items.

We are trying to find a reasonable balance between showing unneeded items and not showing items that are needed.

This means we can only address the issue partially, so we would like to get you thoughts:

**Option 1: Show only items that fall under the solution (or project) cone**
This means we would still limit the number of cases where these folders appear.
The assumption is that it will include most of the items that you care about.
Would this option work for you?

**Option 2: Respect visibility set to false on items included via globs**
This means respecting visibility set to false on items when included via globs. Folders outside of the project cone would be hidden if all children are hidden.
This option would allow selectively hide/show individual globs (but won't allow changing how they get displayed in the tree).
This option may still be too risky for RTM.

Please let us know what you think.
Thanks,
Adrian

**Comment by onovotny** [comment]
I would think that option 2 is more preferable as relying on the solution location seems brittle. 

I actually don't mind the tree visualization of "..\some-sibiling-folder\foo" as that's accurate.

**Comment by srivatsn** [comment]
The CPS side of this work is done now. However there's some work left to do in the SDK (https://github.com/dotnet/sdk/issues/1115) to make the scenario work.

**Comment by lifengl** [comment]
Here is a piece of sample needed in the targets file to make Compile item to work:

    <Compile Update="@(Compile)">
      <Link Condition="'%(LinkBase)' != '' AND '%(LinkBase)' != '.'">%(LinkBase)\%(RecursiveDir)\%(Filename)%(Extension)</Link>
      <Link Condition="'%(LinkBase)' == '.'  AND '%(RecursiveDir)' != ''">%(RecursiveDir)\%(Filename)%(Extension)</Link>
      <Link Condition="'%(LinkBase)' == '.'  AND '%(RecursiveDir)' == ''">%(Filename)%(Extension)</Link>
    </Compile>

This will allow the customer to add <LinkBase> to external globs, and map them into the project.

**Comment by onovotny** [comment]
@lifengl `Link` cannot be part of the answer. There are times when we don't want to use `Link`....

**Comment by srivatsn** [comment]
The SDK portion has been implemented as well - https://github.com/dotnet/sdk/pull/1246

**Comment by davkean** [comment]
We should document this, where's the right place for it?
