### ISSUE TITLE
Figure out whether project system should be using ConfigureAwait(true/false) on its await calls

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#124]
_From @davkean on November 13, 2015 20:51_

We've currently suppress all usages of RS0003 in the project system code:

```
Warning RS0003  Do not directly await a Task without calling ConfigureAwait
```

We should review all instances of the suppressed values and figure out if we want `ConfigureAwait(true)` or `ConfigureAwait(false)`.

_Copied from original issue: dotnet/roslyn#6770_

**Comment by davkean** [comment]
Search for this bug number to find the instances.

**Comment by davkean** [comment]
Conclusion is that we want to almost always use ConfigureAwait(true) based on the new VS guidance: https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md#should-i-await-a-task-with-configureawaitfalse.

**Comment by davkean** [comment]
We also want to turn off the analyzer.

**Comment by davkean** [comment]
I'll give this one to you @davidwengier.

**Comment by davidwengier** [comment]
Note, this rule has been moved to CA2007 in Microsoft.CodeQuality.Analyzers.

As per the comment a day ago, we want to use .ConfigureAwait(true). Since this is the default for this rule, the fix for this will be to disable all suppressions of the rule and explicitly call .ConfigureAwait(true) (or return tasks, or remove async as appropriate). The analyzer will then be turned off, and the explicit calls can be removed again.

**Comment by davidwengier** [comment]
Above PR fixes the ConfigureAwait(true) states, and removes the analyzer. Further PRs needed to remove ConfigureAwait(false) cases if possible, as each is reviewed.

**Comment by davidwengier** [comment]
All ConfigureAwait calls have been removed.
