### ISSUE TITLE
Tree open state lost on restore completion when package disappears

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#1320]
**Steps**:
1. Create a new .NET Core App of some kind (I used a class library)
2. Expand the Dependencies->NuGet elements to see the NuGet dependencies. Select a dependency (I selected .NET Core App). Like this:
![image](https://cloud.githubusercontent.com/assets/2371880/22219111/593bea12-e15e-11e6-98b3-1e4c830a514d.png)
3. Edit the csproj to change TFM to `netstandard1.4`. Save.
4. On restore completion, the tree will refresh.

**Expected**:
The NuGet tree is expanded, showing the new dependency, like this:
![image](https://cloud.githubusercontent.com/assets/2371880/22219135/784b56a4-e15e-11e6-9118-8235b2e3ec8a.png)

**Actual**:
NuGet tree is collapsed:
![image](https://cloud.githubusercontent.com/assets/2371880/22219154/8c91871e-e15e-11e6-82f6-efb25d8e47cc.png)

**Comment by abpiskunov** [comment]
hm .. that is out of control we send changes to CPS remove and re-add in one requesdt and it does this thing. I will open a bug on their side to see if they could get us option to show some node after tree updates..

**Comment by davkean** [comment]
Agreed, ran into this a few times. It's annoying.

**Comment by jviau** [comment]
A couple things:

1) `IProjectTree` is VS-agnostic and has no concept of selection. I am not sold on introducing something like that there.

2) You are performing a Remove -> Add, so CPS does not try to maintain the same expanded state. If you perform a Rename I _think_ CPS will try to maintain the same selection state. I know for the physical tree it should, not sure about virtual trees.

You can always manually re-expand the NuGet node by using `IVsUIHierarchyWindow.ExpandItem`.

**Comment by abpiskunov** [comment]
Fixed for most cases by https://github.com/dotnet/project-system/pull/1880 . Notice that in case when dependency supports lower hierarchies and it existed in the tree, when we update it and change it state from unresolved to resolved we have to remove it and readd. If we don't do that and just update in place like we do everytime now, GraphProvider would not be updated by CPS and would not know that node has children now. I will open a CPS issue for that, but from roslyn project system i did change to update tree nodes instead of removing them everytime.

**Comment by abpiskunov** [comment]
CPS bug opened 405833
