### ISSUE TITLE
Invariant Culture shows up in Assembly Neutral Language list

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1419]
Setting it does nothing. This is basically the same as "(None)".

![image](https://cloud.githubusercontent.com/assets/1103906/22503574/827ab6a0-e8c6-11e6-8d68-a38bfebb481c.png)

**Comment by wolf99** [comment]
Is it the same? I don't know the inner workings but on face value "None" would seem to mean "no setting", whereas "Invariant" would mean set to be insensitive to culture (i.e. a setting to this effect would be added).

I found this issue precisely because I was searching for information on using the Invariant option as my resources are XSD schema files that are only intended to be used with the invariant culture. That is, they do not have no culture *specified* ("none"), but instead should be recognized as being insensitive to culture.

**Comment by sharwell** [comment]
@davkean Can you clarify which of the following is the bug? That way if someone beats us to a PR they can get it right. 😄 

1. The bug is the current behavior is correct and the setting is useless; resolve by not showing the item
2. The bug is the current behavior fails to properly apply the value when a user picks "Invariant Language"; resolve by keeping the item and fixing the way it gets used
