### ISSUE TITLE
Package page duplicates most of it's accelerators (including with the menu bar) 

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1420]
![image](https://cloud.githubusercontent.com/assets/1103906/22503787/6ed0ecfe-e8c7-11e6-958e-921f9b3bfccd.png)

**Comment by davkean** [comment]
This basically means that while this page is open, you can not go directly to any of the top menu items.

**Comment by Giftednewt** [comment]
Would there be any preference on the accelerators for this property page?

Looks like the duplicates on the accelerators are also part of the translations in the xlf files. Should these also be changed or are they generated somehow?

I've checked a few different property pages and most appear to duplicate at least some of the accelerators from the menu bar. I could make them different from the VS defaults, but if the user modifies the accelerators for the menu bar the original behaviour will be exhibited.

**Comment by Pilchie** [comment]
@davkean do you have thoughts here?  I know it's been a long standing problem for the existing other pages?

**Comment by Giftednewt** [comment]
Any updates on this?

I can look at the pages at the same time to bring them all in line with what ever preferences you may have on this if you feel that would be useful

**Comment by davkean** [comment]
@Giftednewt We should change them to not clash with the default menu bar. They also should clash with each other. See the following guidelines: https://msdn.microsoft.com/en-us/library/bb158536.aspx.

**Comment by Giftednewt** [comment]
@davkean I'm working through this and based on the number of labels on the prop page and the number of available letters left to use that don't clash with the default menu bar it's going to be impossible to make all the labels have an accelerator that doesn't clash unless I start removing accelerators from some of the labels.

I currently have the following that I cannot see a way of making not clash with the menu as all possible accelerators have either been used by the menu or the other labels on the property page

- Assembly &file version:
- Require &license Acceptance:
- Assembly &neutral Language:
- Release &notes:
- &Repository Type:
- &Tags:
- Package &version:

I also notice from the original screenshot that there is an "Architecture" menu which I don't have as part of my default VS menu bar. I'm assuming because I'm running community and you have Enterprise or some such other edition. This makes me think that there is potential that even by changing the current accelerators to not clash with the ones in my default menu bar that I'm going to miss some due to restricted features

Do you have any preference on a way forward to get this resolved?
