### ISSUE TITLE
Targets that differ based TFM fight each other in the Error List

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1511]
1. Create a new project
2. Add the following:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0;net45</TargetFrameworks>
  </PropertyGroup>

  <Target Name="Warnings" AfterTargets="ResolveProjectReferences">

    <Warning Text="netcoreapp1.0" Condition="'$(TargetFramework)'=='netcoreapp1.0'" />
    <Warning Text="net45" Condition="'$(TargetFramework)'=='net45'" />
  </Target>
</Project>
```

3. Reload the project
4. Edit Project
5. Save

Expected: Two warnings; one for each TFM
Actual: First the first warning appears, then it disappears and the second one appears

**Comment by davkean** [comment]
This is because we're doing two design-time builds; one with the first TFM and one the second. The Error List associates "targets" with errors - so when the first build runs it gets logged, when it runs the second build runs, the ErrorList thinks that the target has run with new data and it removes the previous error.

**Comment by davkean** [comment]
We should merge these similar to what we do with Roslyn.

**Comment by RaulPerez1** [comment]
To add another option to the plate. We have a similar scenario in C++ with shared projects and project contexts. We run N number of parses (one per project context) and differentiate them in the error list in two ways:
1) They have a different error icon (purple squiggle instead of red)
2) Their project is different

![clipboard01](https://cloud.githubusercontent.com/assets/19919028/22798761/0a1e3a54-eeb8-11e6-9ef7-530da3739d8a.jpg)

I believe you an add arbitrary columns to the error list (not sure if that has changed) so we could add a TFM column which gives the user all the advantages of filtering/sorting from the control. I believe you can also control the filters so you could have it to only active by default.

**Comment by davkean** [comment]
Interesting, what's that second column?

**Comment by RaulPerez1** [comment]
Sorry I'm not sure why I cropped the column names row, here's the full screenshot:

![clipboard01](https://cloud.githubusercontent.com/assets/19919028/22805619/48d6cc50-eed3-11e6-8820-7d2ffbd2f443.jpg)

Presuming you're talking about the icon that's the "Severity" column. In C++ we use that icon to distinguish between build and IntelliSense icons since they are provided by two different compilers and then for IntelliSense we further distinguish between active or inactive (red vs purple).

**Comment by davkean** [comment]
It's interesting that you guys went down a completely different approach to C# which merges duplicate errors.

**Comment by RaulPerez1** [comment]
That's a separate point but yes, two compilers means different sometimes results that can't be merged. The interesting thing in my screenshot though is that you have errors from 2 separate contexts because the have different command lines (akin to multiple TFM's kicking off multiple design time builds).

Here's a very quick and dirty mock that ilustrates how this could work for multiple TFMs

![clipboard01](https://cloud.githubusercontent.com/assets/19919028/22806411/ccb1336e-eed6-11e6-914d-986727e35556.jpg)

Now picture that the NetStandard is a completely different error than the NetCore ones (even though they may be on the same file and project, e.g. some API is conditionally defined)

**Comment by davkean** [comment]
Not a separate point I was referring to the same situation, this is what C# does:

![image](https://cloud.githubusercontent.com/assets/1103906/22806981/d9a0a1de-ef78-11e6-9971-617cfe829fc3.png)

**Comment by davkean** [comment]
From a build perspective they are "two errors" but from a logical point of view, they are the same error, hence why we merge them.

**Comment by RaulPerez1** [comment]
I think we're talking about the same thing in different terms. What I mean about two points

1) Merging errors from IntelliSense and Build
2) Displaying errors from multiple design time builds

In my screenshot there's no build errors at all (the filter was set to IntelliSense to begin with). So you're only seeing scenario number 2. That is something that C# didn't implement (errors from multiple contexts). You're correct in that even for the second scenario you could potentially still merge them but we decided against it for perf reasons on our side.

**Comment by srivatsn** [comment]
With the latest CPS bits, the errors don't keep changing but CPS dedupes errors now and we see only one error in the error list. The error for the other TFM is lost. @lifengl mentioned that we need to implement something in this repo. @lifengl can you please note the details here?

**Comment by lifengl** [comment]
ML need implement a new IBuildableConfiguredProjectsProvider to replace the default implementation of the CPS one.  That is a dataflow contract to tell which sets of configured projects are actively built in the design time, and push a new change, when it is changed.  The default implementation only includes the active configured project.  But the default one can be a sample (and it hooks up the active configuration data flow, which might be the new implementation will do as well, the gap is mostly that it need publish data when a new configured project is loaded as well.

I think CPS need publish a new version of NuGet packages including the new API.  Can @adrianvmsft help?

**Comment by adrianvmsft** [comment]
I pushed a new set of nuget packages to the myget feed that contain the IBuildableConfiguredProjectsProvider interface:
15.3.149-pre-gccb0ae8112

**Comment by davkean** [comment]
Duping against: https://github.com/dotnet/project-system/issues/1511.
