### ISSUE TITLE
Search in solution explorer is very slow

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1559]
Searching in solution is very very slow and sometimes causes VS to hang. this is because it's searching through the entire depth of dependencies nodes and is very inefficient.

Comment from @abpiskunov:

We need to do redesign for displaying search data. Issue here is that Solution Explorer search was not designed to have more than 2 levels of hierarchy, but for core projects we might have deep hierarchies which makes solution explorer (progression) to hang.

Main scenarios for devs when they search:

-	Where a dependency X comes from?
-	Where a version x.x. of a dependency X comes from.
We need to come  up with the results view that answres those questions and does not have deep hierarchy to be displayed.

**Comment by drewnoakes** [comment]
This should be re-evaluated given #6155 (and associated changes in NuGet's VSIX) which completely re-writes how search occurs in the tree.

**Comment by drewnoakes** [comment]
I've run several traces over Solution Explorer search and, while it is slow, cannot see the dependencies tree contributing in any meaningful way to delays.

We recently changed the implementation to use `ISearchProvider` directly, rather than using progression's graph nodes and the corresponding built-in search provider. I cannot see how we can further improve the performance of our search provider, and its performance seems fine. Closing this.
