### ISSUE TITLE
For the Jenkins 'groovy' file: move the inline batch script into checked-in batch files

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/project-system#1729]

**Comment by tannergooding** [comment]
@davkean, do we not have a label to differentiate between "bug" and "infrastructure improvement"?

I had suggested this change initially because it makes modifying jobs "better" due to not having to modify the groovy and regenerate the jobs when you are doing something like adding a new configuration switch.

**Comment by davkean** [comment]
We don't differentiate between bug and infrastructure improvement, we do pull our test - but I've not what value it provides, we never query based on it.

**Comment by tannergooding** [comment]
Most of this was simplified by the move to the toolset.
