### ISSUE TITLE
Prevent <SubType> from being written to the project file

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#182]
csproj/vbideprj both burn in `<SubType>` when they discover a component or a form that needs to have a different icon and be opened in the designer. Talking with some folks, this was done for performance reasons. We should find a new way to represent this same information _without_ putting it in the project file.

**Comment by davidwengier** [comment]
https://github.com/dotnet/project-system/pull/4635#issuecomment-477311344

**Comment by davkean** [comment]
Starting in 16.1, this has been fixed for new project system (currently used for .NET Core) - SubType is now written to the project user file which is not committed to source control.

**Comment by LunarLambda** [comment]
Hi

This is causing issues for us in VS 2019 because when opening the project after a clean git checkout (or when pulling new files) because VS doesn't properly detect the Forms as such and refuses to let us open the designer unless we add the SubType back to the main .csproj file.

Do we need to update VS or is there something else we're missing?

**Comment by jnm2** [comment]
@LunarLambda It's just very slow sometimes.

**Comment by LunarLambda** [comment]
How slow? I spent a good 20 minutes trying to figure it out before realising I can edit the .csproj files to make it work (though I *then* realised VS seemed to only care that .csproj had been touched at all, since I initially copy-pasted the wrong file path and it still caused the form to show up correctly).

**Comment by jnm2** [comment]
@LunarLambda The slowness was a bug was fixed in VS 2022, but I see in https://github.com/dotnet/winforms/issues/3619 that there's a report that VS 2019 still has the bug. I guess that repository would be the place to raise this issue. Maybe file VS feedback linking it too?

**Comment by LunarLambda** [comment]
Will do, thank you.
