### ISSUE TITLE
Ability to hide items that are part of the project in the solution explorer

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/project-system#192]
Similar to the related files issue

**Comment by BillHiebert** [comment]
In xproj this was represented by the DotnetInvisibleContent item group.

**Comment by davkean** [comment]
Instead of "excluding" from project, this is "hiding", ie it's still part of the project, it just doesn't show up the tree.

**Comment by davkean** [comment]
Also xproj had defaults for this, so similar to the related files for this.

**Comment by jp2masa** [comment]
There's the `Visible` item metadata which allows to hide a file from the project tree. Is this a different feature?

**Comment by davkean** [comment]
Yes, this represents the gesture that would add that metadata for you.

In project.json days they couldn't use `<Visible>` because there wasn't an actual item in the project that referred to files in the project, now we have real items and we have the ability to update items via the `<FooBar Update="*.cs"/>` syntax.

**Comment by davkean** [comment]
I don't think this will ever bubble as important as the other things we need to work on. I'm going to close this out, and we can reopen if we hear feedback about it.
