### ISSUE TITLE
How can you test multiple netstandard targets?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/project-system#1938]
In Json.NET I have a netstandard1.0 and 1.3 targets. I want to test them individually.

My test project has a netcoreapp1.1 target that depends on the library and automatically pulls in netstandard1.3, allowing me to test that target.

How can I then test the netstandard1.0 target of Json.NET from the same test csproj?

**Comment by srivatsn** [comment]
This issue was moved to Microsoft/vstest#697

**Comment by JamesNK** [comment]
Slow your roll before throwing it over the fence, I think the project system is involved as well.

If I want to test netstandard1.0 and 1.3, I can't have two netcoreapp1.1 targets? Also how do I explicitly tell the test project which target from a dependency to use?

**Comment by Nirmal4G** [comment]
Me too, I have the same problem. I was round tripping using generated assemblies manually, but there must be a better way to do this, If so then how do I do this?

**Comment by srivatsn** [comment]
@JamesNK missed seeing your last comment - you're right. I misread your question and this does involve work between project system and the SDK. Some of this support is already there. For your second bullet, you can set metadata on the ProjectReference to force msbuild to pick a particular TFM instead of it making a decision based on compatibility.

As for having two netcoreapp1.1 targets, you don't want it to be just netcoreapp1.1;netcoreapp1.1 because then you can't distinguish between them in the project file for conditions. So ideally you'd want something like this to make this work:

```xml
  <PropertyGroup>    
    <TargetFrameworks>mynetcoreapp1.1_1;mynetcoreapp1.1_2</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'mynetcoreapp1.1_1'">
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v1.1</TargetFrameworkVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'mynetcoreapp1.1_2'">
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v1.1</TargetFrameworkVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'mynetcoreapp1.1_1'">
    <ProjectReference Include="..\ClassLibrary4\ClassLibrary4.csproj">
      <SetTargetFramework>TargetFramework=netstandard1.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'mynetcoreapp1.1_2'">
    <ProjectReference Include="..\ClassLibrary4\ClassLibrary4.csproj">
      <SetTargetFramework>TargetFramework=netstandard1.3</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
```

This doesn't work today though because NuGet uses the TargetFramework property to restore instead of the TargetFrameworkMoniker property which is the canonical name that everything in VS uses. #615 tracks fixing that issue. Once that's fixed the above snippet should work.  For now you can make the test project target netcoreapp1.1;netcoreapp1.0 and have the two conditional project references and I verified that works.

**Comment by srivatsn** [comment]
@nguerrera @dsplaisted - why does the syntax for SetTargetFramework requires name=value? I first tried just `<SetTargetFramework>netstandard1.0</SetTargetFramework>` and that fails because we are passing this value directly as the `Properties` argument to the `MSBuild` task. Shouldn't we passing TargetFramework=<SetTargetFramework's Value>?

Also /cc @emgarten and @dotnet/vstest

**Comment by nguerrera** [comment]
`%(SetTargetFramework) `is what normally comes back from the GetTargetFrameworkProperties and we allow you to pick your own set of properties and not runt the target. It is similar to %(SetConfiguration) and %(SetPlatform) which are key=value sets and they are chosen by AssignProjectConfigurations target. I think we want to have a friendlier syntax for this and it can be e.g. just `<Project Include="x.csproj" TargetFramework="net45" />`.  The ability to honor existing metadata was a late change in v1.0 an escape hatch. I considered friendlier syntax, but figured we could design that separately and use a better name after v1.

I think that reads nicest, but would there be a possible conflict with the `<TargetFramework>` sniffing of project system selector?

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1561
