### ISSUE TITLE
Why Visual Studio 2017 modifies csproj file while adding files/folders?

### ISSUE THREAD

**Issue by livarcocc** [dotnet/project-system#1949]
_From @SirwanAfifi on April 9, 2017 6:43_

I'm using Visual Studio Community 2017 - Version 15.1 (26403.0), whenever I build the project newly added files or folders will be added to to `.csproj` file as some item groups:
```

<ItemGroup>
    <Folder Include="Views\Shared\Components\MyComponent\Edit\" />
     .....
</ItemGroup>
```

Is this modification necessary? Why they should be there? How to prevent Visual Studio to add these tags?

_Copied from original issue: dotnet/sdk#1105_

**Comment by davkean** [comment]
@SirwanAfifi Do you have a repro for this? I've never seen this before.

**Comment by UTGuy** [comment]
Is.... this going to get fixed? It also shows changes to the csproj when checking into source repos

**Comment by davkean** [comment]
What version are you using? Please make sure you are on 15.4.

**Comment by UTGuy** [comment]
@davkean 15.4.1

**Comment by UTGuy** [comment]
.... and apparently 15.4.2 is still doing this.

**Comment by Pilchie** [comment]
@SirwanAfifi and @UTGuy is this with new SDK projects, or classic .NET Framework projects?

**Comment by davkean** [comment]
New project system: https://github.com/SirwanAfifi/Testing_csproj_file/blob/master/Testing_csproj_file/Testing_csproj_file.csproj.

**Comment by Pilchie** [comment]
Moving to 15.7, as we're entering escrow for 15.6, and haven't had a chance to tackle this yet.

**Comment by Macadoshis** [comment]
this is pure garbage and messes with the *.[xxx]proj when you want to keep under version control...
And it can't manage files added/removed/moved from an external file folder (another EDI, Windows Explorer, ...).
pure garbage.

**Comment by davkean** [comment]
@UTGuy @SirwanAfifi I've downloaded the project and cannot repro the situation in 15.6 or 15.7 by adding a _file_ to wwwroot. If you can still repro it, can you record a video (say via screentogif.com) so I can make sure I'm following the exact instructions?

Note: If you create an empty _folder_ under the project root - it will, based on the current design, add a `<Folder Include="Folder"/>` to the project. This is because there's no concept of "globbing" (*.*) folders within MSBuild. If you are referring to this behavior - can you please open a bug over on http://github.com/microsoft/msbuild. The project system has to live within the boundaries of what MSBuild supports. Once you add a file to the empty folder, the `<Folder Include="Folder"/>` construct will be removed from the project file.

**Comment by anhphan** [comment]
@davkean I still see this behaviors in 15.6, but in special case, it's happen when we change default item type with wildcat.

Example, when I make central files of my project as `Content` (default item type will be `None`)
``` xml
    <Content Include="Features/**/*.js;Features/**/*.css;Features/**/*.png;Features/**/*.jpg">
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <CopyToPublishDirectory>true</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

Then every time I added a file match this case (copy/paste to visual studio), visual studio will modify my project and add something like this:
``` xml
  <ItemGroup>
    <None Remove="Features\Home\css\site.css" />
  </ItemGroup>
```

Currently, to prevent this I must add this hack to my project:
``` xml
    <None Remove="Features/**/*.js;Features/**/*.css;Features/**/*.png;Features/**/*.jpg"></None>
```

**Comment by davkean** [comment]
@anhphan VS is trying to avoid double-including the same file. The Microsoft.Net.Sdk has a None "glob" that includes everything under the project root that isn't a Compile or EmbeddedResource. Opt out of that by setting EnableDefaultNoneItems property to false.

**Comment by anhphan** [comment]
Hmm, It's only make seen for the known item type like None, Compile, EmbeddedResource. But not good when it's also affected for custom variable (used in custom target) like this:
``` xml
  <ItemGroup>
    <NeedPreprocessFiles Include="Features\**\*.xml" />
  </ItemGroup>
```

disable `EnableDefaultNoneItems` is not a good option because it will make file not automatic display in visual studio.

**Comment by artemutin** [comment]
> Hmm, It's only make seen for the known item type like None, Compile, EmbeddedResource. But not good when it's also affected for custom variable (used in custom target) like this:
> 
> ```
>   <ItemGroup>
>     <NeedPreprocessFiles Include="Features\**\*.xml" />
>   </ItemGroup>
> ```
> 
> disable `EnableDefaultNoneItems` is not a good option because it will make file not automatic display in visual studio.

I was able to solve this problem by moving whole ItemGroup with custom variable, inside custom <Target>, which uses it.
