### ISSUE TITLE
Cannot run if Windows Application is selected

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system#2033]
Output type may be Class Library, Console Application, or Windows Application. If you select Console Application everything just works when you press F5. If you select Windows Application you get:

 > Unable to run your project. The "RunCommand" property is not defined.

This is surprising. There shouldn't be any difference between the two. All I'm doing is hiding the console window; nothing project-system level like Windows Forms support or anything. The exe builds fine either way.

**Comment by basoundr** [comment]
This issue needs 2 fixes.

1. Not show Windows Application as an output type option for .Net Core and .Net Standard Application because 'Windows Application' does not mean anything in these worlds
2. Do not show the dialog when running a Framework Project with Windows Application output type. 

For 1, the fix will be in Project System Repo and for 2, the fix will be in the SDK repo.

**Comment by davkean** [comment]
@basoundr Not sure I agree on 1. Having a Console window is not a requirement for .NET Core. Filtering some output types (such WinMD) might make sense based on target, that should be driven by SupportedOuputTypes driven via MSBuild. The project should should not know about targets and what's valid for certain targets.

**Comment by basoundr** [comment]
@davkean we are enforcing this behavior through SupportedOuputTypes property. Check the PR #2118

**Comment by srivatsn** [comment]
Since we've decided that showing windows application makes sense for netcore proejcts fix 1 above is not needed. 2 should get fixed by https://github.com/dotnet/sdk/pull/1178
