### ISSUE TITLE
VS doesn't show CS files if TargetFrameworks is added with a condition

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/project-system#2070]
If there is a project with TargetFramework conditions defined as below:

```
<TargetFrameworks Condition="'$(IsVsixBuild)' != 'true'">netstandard1.3;net45</TargetFrameworks>
<TargetFramework Condition="'$(IsVsixBuild)' == 'true'">net45</TargetFramework>
```

Visual studio stops showing any .cs files in the solution explorer.

Repro steps:
1) git clone https://github.com/nuget/nuget.client.git
2) git checkout 6d042c86521a396ee64fb008857b134d8bbb47ae

Open NuGet.sln in the repository root. Notice for project like NuGet.Build.Tasks , all .cs files are missing.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1857490/25403292/b7015dc2-29b0-11e7-9111-64535210f39e.png)

**Comment by bernd5** [comment]
As a quickfix you need to define a "dummy" TargetFramework and overwrite it afterward via properties and conditions.
This is currently required because vs does not really "execute" the msbuild file - there is just a simple XML parser to extract the neccessary information...

**Comment by srivatsn** [comment]
With the latest 15.3 Preview1, I can checkout this commit and I see the full tree. This likely got fixed by https://github.com/dotnet/project-system/issues/547

**Comment by srivatsn** [comment]
I should say the issue that @bernd5 is pointing at still is there that unless there's an unconditional TargetFramework entry in the csproj VS will open the project with the old project system instead of the new one unless the .sln file explicitly overrides that. ([see](https://github.com/dotnet/project-system/blob/master/docs/opening-with-cps.md)). In this case however, the sln file has the CPS guid and it was opening the projects in CPS.
