### ISSUE TITLE
Disallow editing contentfiles from packages

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2141]
Content files from nuget package simply show up in the tree as editable items. https://github.com/dotnet/project-system/issues/604 tracks coming up with a proper editing experience by cloning the file but until then we should just mark them as readonly so that users don't accidentally change the packages.

**Comment by drewnoakes** [comment]
When addressing this, see if we can get invocation to open content file items in the dependencies tree to open the file, also non-editable.

**Comment by Barsonax** [comment]
Any chance this is gonna get fixed soon? This seems to be a pretty serious bug as it makes it possible to edit a shared package.

According to the documentation contenfiles should be readonly so tooling should respect that!

**Comment by jjmew** [comment]
@ocallesp This is came up because #6290 we believe this is important as we shouldn't allow those files to be edited.

**Comment by ocallesp** [comment]
@drewnoakes I created a simple Console NetCore project and added the nuget package AdamsLair.Duality.Samples.Tilemaps. There are some files under Content Files, but cannot open or edit them. 
Was editing already disabled ? It seems that this issue was fixed, but should be able to open the res files ? 

![image](https://user-images.githubusercontent.com/510598/89735650-028c2d00-da19-11ea-84ea-62e4359c848f.png)

**Comment by drewnoakes** [comment]
@ocallesp these nodes were never wired up for interaction beyond the browse object. We may do that in future.

This bug relates to the equivalent items within the "Data" folder at the bottom of your screenshot.

**Comment by davkean** [comment]
PR: https://github.com/dotnet/project-system/pull/6480 and https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/266425 (Microsofties only).
