### ISSUE TITLE
Asynchronous project loading no longer serves any purpose.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2216]
Async project loading perf has taken a nose dive.  Specifically, while loading VS is totally unusable due to UI thread hangs.  As such, actually asynchronously loading serves no purpose.  I still have to wait for hte entire solution to load.

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie

**Comment by Pilchie** [comment]
I believe that the VS Platform project and solution team (@huizhonglong, etc), are already investigating disabling it.

**Comment by sharwell** [comment]
This issue seems a bit misleading to me. The problem we're experience is due to the legacy project system not actually allowing the projects to load asynchronously, but instead forcing them to load synchronously on the UI thread. The main point where I observed this occurring is due to the problem described in #2119, which apparently is in the process of being resolved by adding a fast path for OpenOutputGroups that doesn't require a build.

**Comment by huizhonglong** [comment]
We're doing A/B experiment on disabling ASL. @IlyaBiryukov

**Comment by IlyaBiryukov** [comment]
[Experiment details](http://exp/Details?id=45e9fdc1-94bb-4397-a109-e0e2b7dcc52f)

**Comment by davkean** [comment]
Going to close this in lieu of specific issues:

- Output group is known and has since been fixed. 
- Long design-time builds is being tracked by https://github.com/dotnet/sdk/issues/1496
