### ISSUE TITLE
Debug property page isn't respecting theme colors

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2288]
![image](https://cloud.githubusercontent.com/assets/1103906/26439614/47a7eb2a-416c-11e7-9147-ae1935dac2a8.png)

**Comment by davkean** [comment]
Resources (and probably Settings) page either:

![image](https://cloud.githubusercontent.com/assets/1103906/26439668/7c0d9b12-416c-11e7-92c8-de4a230096d1.png)

**Comment by davkean** [comment]
@tannergooding @srivatsn Tells me the pages aren't supposed to be themed, but the background color has definitely changed.

**Comment by davkean** [comment]
You can see the old background color here: https://github.com/dotnet/project-system/issues/2289

**Comment by tannergooding** [comment]
Ok, I looked into this and it is because the fallback background color was changed from `SystemColors.Control` to `SystemColors.Window`.

This change was made because the fallback color (if the page is unthemed or if the theming service is missing/down) needs match the color used by the High Contrast theme, so that the control still meets accessibility requirements.

The easiest fix here would be to change the High Contrast theme background color from `SystemColors.Window` to `SystemColors.Control` and to change the fallback/unthemed colors back to match.
