### ISSUE TITLE
Invalid target framework message sometimes doesn't disappear until build is explicitly invoked

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#2349]
Repro-ing this depends on having the following fixes, which I cobbled together locally for now:

- https://github.com/Microsoft/msbuild/pull/2133
- https://github.com/dotnet/sdk/pull/1274

When changing the `TargetFramework` from an invalid value to a valid value, the error in the Errors list sometimes does not disappear until the project is built.  I haven't been able to figure out why it sometimes stays and sometimes disappears, but the repro steps are more or less:

- Create a new .NET Standard Library
- Open project file for editing in VS
- Change `TargetFramework` property to `foobar`
- Save
  - The error window should show an error saying that the TargetFramework was not recognized
- Build
- Change `TargetFramework` property back to `netstandard2.0`
- Save

## Expected (happens sometimes)

The error is removed from the Errors window.

## Actual (happens sometimes)

The error stays in the output window.  Building the project causes the error to be removed.

**Comment by davkean** [comment]
Can you turn on design-time build logs and attach? 

https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#visual-studio-2017

The warnings disappearing are because we reran a target and it no longer produced the error.

**Comment by davkean** [comment]
Oh I understand what you are expecting (read the description but the not the expected). 

There is zero coordination between design-time build errors and "real" build errors. ie Errors raised from a build, will not be removed by design-time builds - even if the same targets ran.

The current behavior is:

- Errors raised by design-time builds, are only removed by the design-time build if that same target is run and does not produce an error
- Errors raised by builds are cleared at the start of a build

**Comment by davkean** [comment]
We want to do this coordination, similar to what Roslyn does, but we are not currently do it.

**Comment by dsplaisted** [comment]
OK, so you're saying that right now, non-compile errors from an explicit build won't go away until there is another explicit build?

**Comment by davkean** [comment]
Yes, we've now been given the hooks to do this via CPS, but we haven't implemented it yet.

**Comment by davkean** [comment]
Dup'ing against the feature here: https://github.com/dotnet/project-system/issues/2349
