### ISSUE TITLE
We need a way to prevent ExecuteSynchronously/JoinableTaskFactory.Run usage

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2391]
ExecuteSynchronously/JoinableTaskFactory.Run is causing a bunch of thread pool exhaustion when run from a thread pool thread. We've introduced a bunch of bugs because of it:

https://github.com/dotnet/project-system/issues/2389
https://github.com/dotnet/project-system/issues/2379
https://github.com/dotnet/project-system/issues/1342

We need a way (Roslyn rule or something) that prevents us from calling these methods unless deliberately opt'd in. Maybe our version of the threading service that assets/crashes if called off the UI thread?

**Comment by abpiskunov** [comment]
Should it be instead coming from CPS? Other consumers also might hit it...

Thanks,
Anton

On Jun 6, 2017, at 12:10 AM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


ExecuteSynchronously/JoinableTaskFactory.Run is causing a bunch of thread pool exhaustion when run from a thread pool thread. We've introduced a bunch of bugs because of it:

#2389<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fissues%2F2389&data=02%7C01%7Canton.piskunov%40microsoft.com%7C3d4515ca3e144afd01b308d4acab10b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636323298095073472&sdata=2OYbi6Uxl3LIqIDL9PuiqfIxYTMzwqh6ErBqym2QsIk%3D&reserved=0>
#2379<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fissues%2F2379&data=02%7C01%7Canton.piskunov%40microsoft.com%7C3d4515ca3e144afd01b308d4acab10b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636323298095073472&sdata=l9vcEl96QovuKpWIJh9VpYoWmwwmNnIxAtg%2FrRToJuM%3D&reserved=0>
#1342<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fissues%2F1342&data=02%7C01%7Canton.piskunov%40microsoft.com%7C3d4515ca3e144afd01b308d4acab10b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636323298095073472&sdata=YLS15KD2NOI3Q9EYknHAIqVMlO%2BC2djk9Ieo5iWtSQI%3D&reserved=0>

We need a way (Roslyn rule or something) that prevents us from calling these methods unless deliberately opt'd in. Maybe our version of the threading service that assets/crashes if called off the UI thread?

**Comment by davkean** [comment]
We've merged in the Microsoft.VisualStudio.Threading analyzers which enforce this.
