### ISSUE TITLE
Nuget dependencies node search results shows incorrect dependencies

### ISSUE THREAD

**Issue by danroth27** [dotnet/project-system#2451]
I was trying to track down where we have a dependency on Microsoft.Composition, so I did a search in the solution explorer for an ASP.NET Core project and I get this:

![image](https://user-images.githubusercontent.com/1874516/27192904-df9c7cd4-51b1-11e7-93f5-edb174762a1e.png)

It looks like this is saying that Microsoft.VisualStudio.Web.CodeGeneration.Design has a dependency on Microsoft.Composition, but it actually doesn't. I believe the dependency is there, but it's much deeper in the tree (pulled in by roslyn or something like that).

**Comment by abpiskunov** [comment]
Its by design. Because of solution explorer limitations, we decided to show flat list of all dependencies from all levels, that given direct project package dependency depends on.

Thanks,
Anton

On Jun 15, 2017, at 11:04 AM, Daniel Roth <notifications@github.com<mailto:notifications@github.com>> wrote:


I was trying to track down where we have a dependency on Microsoft.Composition, so I did a search in the solution explorer for an ASP.NET<http://ASP.NET> Core project and I get this:

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1874516%2F27192904-df9c7cd4-51b1-11e7-93f5-edb174762a1e.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7C70ef7001e2574936d4a508d4b4109ef8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636331430857142286&sdata=RG7Sb2l%2Fww8KUVdtvEWG%2BLjXvLWMey6Rw3V9NK0J6c0%3D&reserved=0>

It looks like this is saying that Microsoft.VisualStudio.Web.CodeGeneration.Design has a dependency on Microsoft.Composition, but it actually doesn't. I believe the dependency is there, but it's much deeper in the tree (pulled in by roslyn or something like that).

**Comment by danroth27** [comment]
> we decided to show flat list of all dependencies from all levels, that given direct project package dependency depends on.

I'm not sure what you mean . . . could you please clarify? How should I interpret what the dependency node is showing me? It *looks* like it is showing direct dependencies, but it obviously isn't in this case. What is it trying to convey instead? If the intent is to hide part of the dependency chain should there be some sort of UI indication (like a ...) that this is happening?

**Comment by abpiskunov** [comment]
Yes, you understood right. We are not hiding chain, we just can not show it since it would be too slow and useless because of multiple scroll pages.

What we at leadt show is that top level dependency implicitly or explicitly brings package X.

There were tens of long threads about that and even more discussions, i would not start a new one :). Check with Barry, Damian or Bill ...

Thanks,
Anton

On Jun 15, 2017, at 2:10 PM, Daniel Roth <notifications@github.com<mailto:notifications@github.com>> wrote:


we decided to show flat list of all dependencies from all levels, that given direct project package dependency depends on.

I'm not sure what you mean . . . could you please clarify? How should I interpret what the dependency node is showing me? It looks like it is showing direct dependencies, but it obviously isn't in this case. What is it trying to convey instead? If the intent is to hide part of the dependency chain should there be some sort of UI indication (like a ...) that this is happening?

**Comment by srivatsn** [comment]
This is the current behavior and it's that way because of some perf restrictions but https://github.com/dotnet/project-system/issues/1942 tracks improving this - so this is not the eventual design.

**Comment by danroth27** [comment]
Ah, I think I understand the behavior now. When you search for a package you will see top level dependencies that depend on the package you are searching for either directly or indirectly. 

I get that's due to a UI limitation, but I wonder if the UI for the search results could be tweaked a bit to make this clearer. Right now we use the same UI paradigm (a nested package node) to represent both a direct dependency (when your navigating around the dependencies node) and also an *indirect* dependency (when you search). Could we tweak the UI to make it indirect dependencies clearer? Ex use a different icon for indirect dependencies or maybe put an ellipsis in front of the package ID?

**Comment by abpiskunov** [comment]
Yeah, Ellipsis or icon sounds like good addition for current design, if priority is high enough ..

Thanks,
Anton

On Jun 15, 2017, at 4:27 PM, Daniel Roth <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, I think I understand the behavior now. When you search for a package you will see top level dependencies that depend on the package you are searching for either directly or indirectly.

I get that's due to a UI limitation, but I wonder if the UI for the search results could be tweaked a bit to make this clearer. Right now we use the same UI paradigm (a nested package node) to represent both a direct dependency (when your navigating around the dependencies node) and also an indirect dependency (when you search). Could we tweak the UI to make it indirect dependencies clearer? Ex use a different icon for indirect dependencies or maybe put an ellipsis in front of the package ID?

**Comment by tmeschter** [comment]
Doesn't meet the bar for 15.5 at this point. Moving out to 15.6.

**Comment by Pilchie** [comment]
We're not going to get to this anytime soon, but we still have #1942 to track fixing for real.
