### ISSUE TITLE
Up to date check needs to work with multi-TFM projects

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/project-system#2487]
Right now, we are called with the active configured project, but multi-TFM projects will build multiple configurations.

**Comment by panopticoncentral** [comment]
Since this is potentially somewhat complex, and since the issue hasn't been raised frequently, I'm moving this to 15.7. @davkean I'm curious what your thoughts on this are since you've thought so much about multi-TFM. The up-to-date checker is tied to a configured project. It doesn't seem correct that an up to date checker would be looking at other configurations. That might suggest that it would be more correct to do it at the CPS level? Or somewhere else?

**Comment by Pilchie** [comment]
:link: also reported in https://developercommunity.visualstudio.com/content/problem/231529/fast-up-to-date-check-only-checks-one-targetframew.html.

**Comment by davkean** [comment]
We only ever build the first TFM's configured project (clearing the TargetFramework property so all TFMs build) - so only the first up-to-date check should run. However, as @Pilchie mentioned it should be grabbing data from all the implicitly active projects. I'd recommend a service that individually in each implicitly active configuration (similar to what I'm doing in https://github.com/dotnet/project-system/pull/3423, that the core up-to-date queries to determine the _real_ up-to-dateness.

**Comment by jaredpar** [comment]
I've been hitting this a lot this week as I've been moving the compiler test suite to run on CoreClr. Our setup is to have all of our test projects multi-target netcoreapp2.0 and net46. End up spending a bit of time debugging netcoreapp2.0 failures which locks the files in the output directory. Now if I build then net46 succeeds but netcoreapp2.0 fails due to lock files. Once I stop the debugger and build again nothing happens because the up to date check succeeds.

**Comment by jamesmontemagno** [comment]
With the .NET Core 2.1.400 SDK installed any of projects that multi-target and use extensions such as *.ios.cs and *.android.cs no longer show up inside the solution explorerer. This worked in 2.1.202 as if I delete other ones then it works just fine.

**Comment by Pilchie** [comment]
@jamesmontemagno I don't think that issue is related to this one.  I'm not not sure it's related to the .NET Core SDK version as much as the VS version?

**Comment by jamesmontemagno** [comment]
If I delete 2.1.400 and revert back to 2.1.202 then it works fine in 15.8.

**Comment by jamesmontemagno** [comment]
We had a thread with @davkean about this in the past. Would like to know how to proceed on this and it is necessary for all of my cross-platform libraries I create.

**Comment by davkean** [comment]
Have you mixed issues? The issue you are referring is https://github.com/dotnet/sdk/issues/2337, which has a workaround at the bottom. The real feature is being tracked by https://github.com/dotnet/project-system/issues/935.

**Comment by jamesmontemagno** [comment]
Got it, I may have spiraled down the wrong GitHub thread of issues.

**Comment by Pilchie** [comment]
:link: Also reported at https://developercommunity.visualstudio.com/content/problem/312810/up-to-date-checks-fails-regularly-on-cross-targete.html****

**Comment by xen2** [comment]
I have also been hitting this issue quite a lot when working on porting Xenko to new project system.
Hope it can be solved soon, `DisableFastUpToDateCheck` is way too slow for a 100+ projects solution.

(detailed WIP blog post: https://github.com/xenko3d/xenko-website/blob/master/_posts/2018-11-12-feature-spotlight-xenko-3-1-and-nuget.md)

**Comment by panopticoncentral** [comment]
@drewnoakes @davkean I don't think I'm going to get to look at this soon. Drew, is this something you could look at?

**Comment by davkean** [comment]
Given we pushed multi-targeting support into CPS, I think we should change `ProjectConfig.StartUpToDateCheck` and `ProjectConfig.QueryStartUpToDateCheck` it consult all "configs" in same group (via `IActiveConfigurationGroupService/IActiveConfigurationGroupService2`) and ask their `IBuildUpToDateCheckProvider` equivalents.

**Comment by jaredpar** [comment]
For context: this is currently a rather annoying bug for the Roslyn repository. All of our unit tests are multi-TFM projects and the FUTD check is giving false positive for them. It means we end up in a lot of situations where we're running tests and they're actually running against our old code, not the new one. Lots of head scratching as to why our changes aren't taking effect.

**Comment by drewnoakes** [comment]
Be sure to check the case in duplicate issue https://github.com/dotnet/project-system/issues/4338.

**Comment by drewnoakes** [comment]
@jjmew I would like to take this for 16.8 as a precursor to working on proper multi-target support for the dependencies node. This would be a simpler implementation, would add customer value (I actually hit this myself today) and would help flesh out the design for #6183.

**Comment by drewnoakes** [comment]
We discussed this today with CPS and concluded the design is subtly different than it would be for the dependencies node.

The distinction is between aggregation across implicitly active configurations of _services_ versus _data sources_.

- Making the fast up-to-date check support multi-targets correctly involves aggregating _services_. The extension point (`IBuildUpToDateCheckProvider`) may be exported per-implicitly-active configuration, and therefore may be exported in a non-active configuration, yet would still need to be considered. An example would be a multi-target project (e.g. iOS, Android) where iOS is active, yet a custom `IBuildUpToDateCheckProvider` is exported for Android only.

- In contrast, the dependencies node will aggregate _data sources_, for which `UnwrapChainedProjectValueDataSource<,>` is a good fit.

Notes about the resulting design:

- Need an `IBuildUpToDateCheckProvider` that lives in unconfigured project scope within CPS, and which aggregates all `IBuildUpToDateCheckProvider` instances across implicitly active configurations.
- As soon as one 'child' `IBuildUpToDateCheckProvider` returns `false`, the `CancelationToken` should be cancelled so that pending work in other configurations can be aborted.
- To reduce duplicate file system timestamp access, `IBuildUpToDateCheckProvider2` could be introduced that overloads `IsUpToDateAsync` with an additional argument that obtains and caches these timestamps. That cache's lifespan would begin and end with that single top-level check.

This work will require changes in both CPS and the .NET Project System.

**Comment by drewnoakes** [comment]
`BuildUpToDateCheck.IsUpToDateAsync` should also check its `CancelationToken` in more places. Currently it only does this in its early stages. Once it starts looping through files on disk it will complete without checking the token.

**Comment by jnyrup** [comment]
Here's a workaround when conditionally compiling `*netcore30*.cs` files only for `netcoreapp3.0`

```csproj
<ItemGroup Condition=" '$(TargetFramework)' != 'netcoreapp3.0' ">
  <!-- Do not compile files -->
  <Compile  Remove="**/*netcore30*.cs" />

  <!-- Still show files in Solution Explorer -->
  <None Include="**/*netcore30*.cs" />

  <!-- Trigger rebuilds on changing the files -->
  <UpToDateCheckInput Include="**/*netcore30*.cs" />
</ItemGroup>
```
