### ISSUE TITLE
Move away from returning file paths for dependency nodes that don't need it

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2559]
We fake up file paths for dependency nodes that don't need them. This causes us to produce a bunch of data manipulating them, mostly implementing FindByPath (which produces 60% of data in current builds).

We should move to using the `>identity` syntax for nodes that don't need them so that we don't search the tree and don't need to do any path manipulation.

Make note that in DepedenciesProjectTreeProvider.RemoveAsync and CanRemove we are making the assumption that all nodes have a file path that matches the ID. We should fix this.

See PhysicalProjectTreeProvider.GetPath for the `>identity` syntax.

**Comment by abpiskunov** [comment]
Make sure you verify Graph logic that maps to real tree nodes and update bower and npm nodes from web project sustem, since it will be a breaking change.

Thanks,gic
Anton

On Jul 4, 2017, at 5:35 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


We fake up file paths for dependency nodes that don't need them. This causes us to produce a bunch of data manipulating them, mostly implementing FindByPath (which produces 60% of data in current builds).

We should move to using the >identity syntax (see for nodes that don't need them so that we don't search the tree and don't need to do any path manipulation.

Make note that in DepedenciesProjectTreeProvider.RemoveAsync and CanRemove we are making the assumption that all nodes have a file path that matches the ID. We should fix this.

See PhysicalProjectTreeProvider.GetPath for the >identity syntax.

**Comment by davkean** [comment]
Make sure we handle the Analyzers, Projects, etc nodes themselves - these are getting file paths like "Analyzers" and "Projects".

**Comment by Pilchie** [comment]
Is this a problem only during search, or also during solution load?

**Comment by davkean** [comment]
The Test Window used to hit this path on open (not solution load but immediately after) but unsure in the source based discovery.

**Comment by drewnoakes** [comment]
From @davkean in https://github.com/dotnet/project-system/issues/6110#issuecomment-617009875:

> The one thing that we might want to think about, is that this API is called by _IVsHierarchy.ParseCanonicalName_ and _IVsProject.IsDocumentInProject_, which paired with IVsHierarchy.GetCanonicalName is supposed to return/provide a way to retrieve and query any item within a tree. These APIs don't actually have to take paths, but rather monikers that more than often are paths. For drag and drop, I want to select/expand to a project reference for the drag as reference feature- and I was thinking that combos of this these APIs combiend with Solution Explorer APIs (ExpandItem) would provide that.
>
> One option might to not remove this implementation, but to short circuit when the provided moniker isn't actually a moniker/id that we produced.

**Comment by drewnoakes** [comment]
This was fixed in https://github.com/dotnet/project-system/pull/6282. We no longer merge data values into a fake file path for use on tree items. Instead, the physical tree provider's default logic is used where possible, creating pseudo-paths of form `>123`, where 123 is the item ID. These paths are much smaller in memory and enable faster lookup.

An exception is analyzer references, where the file path is used by Roslyn to attach child nodes in Solution Explorer.
