### ISSUE TITLE
Visual Studio becomes extremely slow when adding a deep folder structure to wwwroot in a .NET Core Webapplication

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2588]
From: [VS Feedback](https://developercommunity.visualstudio.com/content/problem/76445/visual-studio-becomes-extremely-slow-when-adding-a.html) (Includes ETL traces) ([Internal Link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/460234))

This may be remedied by recent improvements on the Dependencies node. 

**From customer:**
- - - - -
Whenever I create a new (.NET Core 2.0 preview 2) web application project and I add new content to the wwwroot with a deep folder structure, Visual Studio becomes extremely slow:

- Any interaction with solution explorer can take up to 30 - 40 seconds (adding files, renaming, deleting, etc).
- Any interaction with dotnet command from cmd line is unbearably slow (dotnet build, restore, publish, etc).

This behaviour consistently occurs after adding a large amount of files to the wwwroot and makes working with Visual Studio completely impossible.

Steps to reproduce:
- Create new empty .NET Core web application
- Interact with Solution Explorer (everything is snappy as it should be)
- Build and start application (everything is snappy as it should be)
- Add a bunch of files with a deep folder structure to the wwwroot (in my example: admin designs template, found here: https://themeforest.net/item/admindesigns-bootstrap-admin-template-framework/9903221?s_rank=1)
- Repeat all steps above and discover how unresponsive Visual Studio becomes.

Using the same files in VS2017 in a .NET Framework 4.6.2 application works fine and behaves as expected.
- - - - -

**Comment by natidea** [comment]
Additional traces: [466099](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/466099)

**Comment by abpiskunov** [comment]
@natidea did you check traces? I have not yest, but this issue seems to be related to globbing perf - we did see similar behavior when node modules were located under wwwroot and we have explicit exclusion for known large folders from wwwroot. In this case customer seems to add some folder we did  not exclude and globbing started to process it.

**Comment by srivatsn** [comment]
@natidea can you follow up with CPS folks?

**Comment by AyhamB** [comment]
@natidea I'm facing same issue as @natidea It's very easy to reproduce. Adding a template assets folder under wwwroot makes it impossible to work on the project. Any advice or workaround?

**Comment by jasselin** [comment]
@natidea Have a look at this, seems to work for me. https://github.com/Microsoft/msbuild/issues/2238

**Comment by Pilchie** [comment]
@davkean would this be project-system? Seems like it should be either CPS or MSBuild?

**Comment by davkean** [comment]
Agreed.

**Comment by Pilchie** [comment]
Tagging @lifengl and @rainersigwald.

**Comment by Pilchie** [comment]
Seems like Microsoft/msbuild#2238 covers it there.  @lifengl - can you track in CPS?

**Comment by Pilchie** [comment]
Ping @lifengl?

**Comment by Pilchie** [comment]
Filed [566362](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/566362) internally to track.

**Comment by lifengl** [comment]
I noticed the customer has sent a feedback item with some ETL traces.  The trace shows the performance issue related to globbing items.  Considering many improvements inside msbuild in this area in 15.5 timeframe, and this was an old report, I will resolve that as fixed by msbuild.

If we still see this problem in the new VS update, please report it, and we can take another look.
