### ISSUE TITLE
Adding item templates doesn't effect the project if EnableDefaultCompileItems is set to false.

### ISSUE THREAD

**Issue by ericstj** [dotnet/project-system#2678]
Using 15.3 preview 26723.0.d15rel

1. Create new NETStandard library project.
2. Edit the CSproj to set EnableDefaultCompileItems and manually include class1.cs.  EG:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Class1.cs" />
  </ItemGroup>

</Project>
```
3. Do Add > New Item and select a class.  Name it "test".
4. In Class1.cs try to instantiate "test".

Expect: compile works and item is added to csproj.

Actual: added item is missing from project, but appears in the solution hierarchy 😕 
Unloading and reloading the project maintains this state.  The added item remains missing from the project file.  I can't seem to do anything to get the file to disappear from the hierarchy.

**Comment by davkean** [comment]
The SDK has a glob that includes all files that are not Compile items in the None glob. The None glob is picking it up. As far as the project system is concerned this is by design, but you might want to file this against SDK which contains the glob if you think this is confusing.

**Comment by ericstj** [comment]
The problem wasn't that things appeared in the solution heirarchy, I expect that.  The problem was that the project system didn't update the project as a result of applying the item template.

**Comment by davkean** [comment]
Ah, you added the class via a template and we didn't add to the Compile glob. Hmm, unsure who's bug this is.

**Comment by davkean** [comment]
//cc @lifengl  @jviau 

I spend some time thinking about this, and this behavior is by design.

First of all, to avoid this, opt out of the all the default globs by setting `<EnableDefaultItems>false<EnableDefaultItems>` property or opt just out of the default  `None` glob by by setting `<EnableDefaultNoneItems>false<EnableDefaultNoneItems>` property.

The template has zero control over the item type here - it's solely gets added into whatever item type the project says it should. The same behavior occurs if you explicitly drop a new file on disk, or move it from one folder to another.

What's happening here is the project system to trying to avoid double-including the same file. It's seeing that adding this file would cause it to be covered by the `None` item and stops. It doesn't understand the complex rules in the SDK that says that adding a file to the `Compile` item would cause it to be removed from `None` item and hence avoid the double-include in this case.

It does this, because of these sorts of situations:

``` XML 
<Project>
  <ItemGroup>
    <None Include="*.cs" />
  </ItemGroup>
</Project>
```

If the project was to add the `<Compile Include="test.cs"/>` to the above, the file would now be included twice; once in `None` and once in `Compile` item.

Based on that, I'm going to resolve this by design.

**Comment by ericstj** [comment]
I see.  The behavior is definitely broken and seems to be the result of the SDK's None item.

**Comment by davkean** [comment]
We have a bug against SDK to change the globs: https://github.com/dotnet/sdk/issues/1157.
