### ISSUE TITLE
Some Custom tools do not run in .NETStandard projects

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2687]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/61552/custom-tools-do-not-run-in-standard-projects.html) | [Internal Link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/441201):

> I use a lot of custom tools in my projects. These all run fine in VS2015 and VS2017 with .net framework and/or .net core projects. They do not run at all under Standard projects. The box for custom tool is there, I can fill it in but the custom tool is never run, not even when I invoke it directly.
> I had thought it was some problem with the tools not registering the correct GUID. But just now I discovered that I have the exact same behavior regardless of whether the tool is present on the system at all. Specifically, my tool is registered as Protogen.
> In a Framework project, declaring the custom tool as
> Protogen - Works normally. - correct NotProtogen - Throws tool not found error - correct
> In a standard project 
> Protogen - Does nothing, no error - wrong NotProtogen - Does nothing, no error - wrong
> I can find no mention of custom tools not working. It will be something of a hassle if I have to resort to running batch files to invoke the tools manualy.
> The code for the tools I use is at the following URL. One of the tools generates the binding code for single file generators.
> https://github.com/hallambaker/PHB-Build-Tools 

A related issue https://github.com/Microsoft/VSSDK-Extensibility-Samples/issues/95 points out the [Single File Generator](https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/Single_File_Generator) sample does not work in .NET Standard projects. But the ResXResourceGenerator does work. 

This issue tracks custom tools not running on .NET Standard projects even when invoked directly. Related CPS bug [453823](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/453823) (https://github.com/dotnet/project-system/issues/1521) tracks certain cases (e.g. switching tabs) where Single File Generators are never run.

**Comment by TomasMorton** [comment]
This is also an issue that we are encountering.
We have DataSet files (.xsd) which use the MSDataSetGenerator custom tool.  We are using the 2017 .csproj format targeting net45.  
When we try to run the custom tool, nothing at all happens.

**Comment by tellarin** [comment]
I'm now also facing this. But for .tt T4 files.
All worked fine until I updated to VS 2017 15.5.1

**Comment by jmarolf** [comment]
moved to CPS [545508](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/545508)

**Comment by TomasMorton** [comment]
How are we meant to track this now?

**Comment by jmarolf** [comment]
@TomasMorton good point.  I'll leave this open and try and act as a bridge to the internal team.  This is still targeted at 15.6

**Comment by TomasMorton** [comment]
Thank you very much.

**Comment by davkean** [comment]
@jmarolf This is actually our bug - we have to register the tools for our project type.

**Comment by Dark-Bond** [comment]
What's the status of this?  Just like the OP, I've got a significant amount of code generated from custom tools.  It's been more than a year.  Do you have any insight on what's wrong and/or when it will be fixed?

**Comment by JoeGaggler** [comment]
Looks like this was punted again. As a workaround I have our custom tools running in a legacy project in the same solution, however I'll be looking into migrating away from VS-registered Custom Tools altogether (i.e. ISingleFileGenerator)

**Comment by Dark-Bond** [comment]
I don't get it.  Are they trying to drive us out of the Visual Studio environment?  You can't even use the DataSets any more in .Net Standard.  A whole year has gone by and no one seems to have noticed.  Am I on the wrong track with moving to .Net Standard or should I give up on the concept of IDE custom tools?

**Comment by danielk67** [comment]
Same here... using a Custom tool works in VS2017 but not with my .NET standard project.

Would be nice to know if a bug fix is planned in the roadmap?

**Comment by hallambaker** [comment]
I now have a work around but not a good one. I have a tool that I use to convert Visual studio project files to make files for Linux and OSX builds. So I dump out a make file for windows now as well. This has the advantage of also supporting shared code projects.

It is MIT License:
https://github.com/hallambaker/PHB-Build-Tools

Tool is Makey

**Comment by JoeGaggler** [comment]
I'm hoping that the Visual Studio team decides to support to [dotnet CLI tools](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility). The custom tool command in Visual Studio would simply consume the output of the CLI for generated file, providing the `<DependentUpon>` file as input. The single-file-generator would then conveniently be installed via NuGet instead of VSIX, and would work in Visual Studio as well as VSCode.

**Comment by davkean** [comment]
Folks, sorry for the late reply, I had to get myself familiar with how single file generator registration worked. I've spent some time on this and figured it out.

The reason existing single file generators do not work for .NET Standard/.NET Core projects is because our "project type" is different to the legacy project system, resulting in the project system looking up a different key to find them. In the future [we hope to avoid that and just look up the legacy location](https://github.com/dotnet/project-system/issues/3535). 

For now, single file generators would need to also [register themselves](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators) under the following GUIDs as well their existing ones:

Language|GUID
---|---
C# (.NET Standard/.NET Core)|9A19103F-16F7-4668-BE54-9A1E7A4F7556
F# (.NET Standard/.NET Core)|6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705
Visual Basic (.NET Standard/.NET Core)|778DAE3C-4631-46EA-AA77-85C1314464D9

I'm going to dupe this against #3535 which contains more information.

**Comment by davkean** [comment]
Microsofties, I have a PR for this internally: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/122410?_a=overview.

**Comment by hallambaker** [comment]
No, that does not address the issue. I have been registering against 9A19103F-... as well and it doesn't work.

There is clearly something broken in VS because all custom tools show the same behavior - nothing happens. Nothing happens even when you specify a non existent tool.

    [CodeGeneratorRegistration(typeof(CommandCS), "CommandCS", 
					vsContextGuids.vsContextGuidVCSProject, GeneratesDesignTimeSource = true)]
    [CodeGeneratorRegistration(typeof(CommandCS), "CommandCS", 
					"9A19103F-16F7-4668-BE54-9A1E7A4F7556", GeneratesDesignTimeSource = true)]
    [CodeGeneratorRegistration(typeof(CommandCS), "CommandCS", 
					vsContextGuids.vsContextGuidVBProject, GeneratesDesignTimeSource = true)]

**Comment by Dark-Bond** [comment]
@davkean - If you have a working version of this, perhaps you could post a small, working example to GitHub.  I still can't get it working with the new GUIDS so I suspect there's still something missing.
