### ISSUE TITLE
Second build of a project always fails up-to-date

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2698]
1. File -> New Console App (.NET Core)
2. Wait for design-time builds to finish (or the warning icon in dependency node)
3. Build
4. Build again

Expected: For design-time build to be up-to-date
Actual:

1>FastUpToDate: The list of source items has changed since the last build. (ConsoleApp86)
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: ConsoleApp86, Configuration: Debug Any CPU ------
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by davkean** [comment]
tag @panopticoncentral

**Comment by panopticoncentral** [comment]
Yeah, this is a known issue that I meant to revisit. IIRC, it's a problem with globs. The up to date check component isn't instantiated until the first build. At that point, we haven't got anything from the data flow, so we can't check up to date. The second time, we've gotten the results from the data flow, but we don't actually know if the list of source items have changed since the last build since the list of source items might have changed even though the project file didn't, so we fail again. Third time is the charm -- we have data & we know the list of source items haven't changed...

**Comment by davkean** [comment]
We should hook onto project load and run before the first build.

**Comment by panopticoncentral** [comment]
@davkean What is the best way to do this? Is there some place in project load that would be ideal to instantiate us so we could hook into the data flow?

**Comment by davkean** [comment]
If the up-to-date check is based on CSharp or LanguageService capabilities, you can just use [ProjectAutoLoad]:

``` C#
[ProjectAutoLoad(...)]
private Task OnProjectFactoryCompleted()
{
    return InitializeAsync();
}
```

**Comment by davkean** [comment]
If it's based on other capabilities - you need a dynamic load component, and I have a change that simplifies that next week.
