### ISSUE TITLE
Cannot delete a selection of project items containing a mix of links and actual files

### ISSUE THREAD

**Issue by mizbrodin** [dotnet/project-system#2701]
Microsoft Visual Studio Enterprise 2017 Preview 7 (15.3.0-pre.7.0+26730.0)

Repro steps:
1. Create a new class library project. Class1.cs file will be created automatically.
2. Add an existing file into the project as a link (**Add as Link** button in the Open File dialog box)
3. Select both items in Solution Explorer (Class1.cs and the newly added linked item).
4. Press **Delete** key on the keyboard: nothing happens.
5. Right click on the selected items: there is no Delete/Remove command in the popup menu.

**Comment by davkean** [comment]
Thanks @mizbrodin, I've filed this against a team internally that owns this code. 

Microsofties, internal link: https://devdiv.visualstudio.com/DevDiv/_workItems?id=487921&fullScreen=false&_a=edit.

**Comment by davkean** [comment]
Closing in lieu of the above bug.

**Comment by lifengl** [comment]
it is the side effect that VS uses "remove" command for linked items because we don't delete physical files, and "delete" command for normal items.  When mixed items are selected, none of them can apply to all items.  The behavior applies to traditional projects as well.

We will consider it in a future release..
