### ISSUE TITLE
Removing all items included by a wildcard doesn't remove the wildcard

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/project-system#2838]
Starting with this - note my project is not in c:\shared

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="c:\shared\*.cs" />
  </ItemGroup>

</Project>
```
which in my case gives me foo.cs and bar.cs in the solution explorer, I remove foo.cs and bar.cs from the solution explorer, and it gives me
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="c:\shared\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="c:\shared\bar.cs" />
    <Compile Remove="c:\shared\foo.cs" />
  </ItemGroup>

</Project>
```

In my mind, it's more likely that I meant "I don't need the shared files" than I mean "I don't need these specific files but I might add other files to that folder later". In my actual case there were a large number of files pulled in by the wildcard so I ended up with a lot of Remove tags.

I suggest the heuristic be, if a gesture removes the last files originating from a project file wildcard expression outside of the project root, the wildcard expression (and any Remove expressions against it) can be removed.

**Comment by davkean** [comment]
I remember we discussed this at length, cannot remember the conclusion why we entered here exactly. cc //- @lifengl @jviau.

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workitems/edit/499766.

**Comment by binki** [comment]
The alternative to the existing behavior would be for VisualStudio to replace the wildcard with the list of files which are present in the project at the current time. I prefer the current behavior over that.

That said, if you are adding a wildcard expression, you probably should be editing the `.csproj` directly instead of using VisualStudio’s GUI to exclude files. There’s no way for VisualStudio to deterministically guess what edits you actually want to be making (such as removing the wildcard line completely).
