### ISSUE TITLE
PP file output is not generated during the build in classic c# project

### ISSUE THREAD

**Issue by jainaashish** [dotnet/project-system#2861]
PP file output is not being generated during the build

**Steps:**
1. create c# class library
2. Install package contentfilesexample -v 1.0.2 as PackageReference

**Expected**
ExampleReader will be in the current namespace from the pp file.

**Actual**
ExampleReader does not exist

Copied from https://github.com/dotnet/sdk/issues/1100 for classic c# project system as well

**Comment by tmeschter** [comment]
What I see on both 15.3 and a 15.5 Preview build is that the build properly preprocesses Example**Reader**.cs.pp into ExampleReader.cs under obj\debug, and that file is properly added to the project and `ExampleReader` shows up in Intellisense (though the file itself does not show up in Solution Explorer as it is generated during a build).

However, Example**Internals**.cs is missing. Since it doesn't need to be preprocessed, we try to reference it from the NuGet package itself, at <user>\.nuget\packages\contentfilesexample\1.0.2\contentFiles\cs\portable-net45%2Bwpa81%2Bwp8%2Bwin8\ExampleInternals.cs. What gets passed to the compiler (and thus to the project system and language service) is <user>\.nuget\packages\ContentFilesExample\1.0.2\contentFiles\cs\portable-net45+wpa81+wp8+win8\ExampleInternals.cs

**Comment by jainaashish** [comment]
@tmeschter thanks for looking into it, let me check this path at NuGet.

**Comment by Pilchie** [comment]
We concluded this was a problem with that specific package, right?  Should this bug be closed?

**Comment by Pilchie** [comment]
Closing based on mail thread - please let us know if you think it's still an issue.
