### ISSUE TITLE
[Dependencies] Regression when adding newly created project reference, it is always yellow even though has hierarchy

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2897]
VS Dev15.5 Preview 2 d15rel 27016.0

Repro steps (we have automated integration test and i tried them manually too):

1. Create a new core 2.0 Web app wait for restore, save solution
2. Creat a new ClassLibrary core 2.0, wait for restore
3. Add project reference web->classlib via Add Reference dialog, wait for restore:

Actual result:

Project dependency appears in the web but is yellow, However it does have hierarchy under it.

Expected dependency to be normal since targets frameworks are the same for web and classlib.

![image](https://user-images.githubusercontent.com/1592091/31685702-ccd0b064-b338-11e7-8ac1-90e69d089059.png)

**Comment by abpiskunov** [comment]
Note: After closing vs and reopening solution in new instance icons go back to normal after all restore and load is complete.

**Comment by natidea** [comment]
This is being tracked by [509659](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/509659)
This problem is due to a change in MSBuild metadata (ResolveProjectReferences)

![image](https://user-images.githubusercontent.com/7732033/31689370-0fb956e6-b344-11e7-9aa5-e2984f8ad50f.png)

The reference is:
```xml
  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>
```
This change breaks the check in [DependenciesRuleHandlerBase.cs#L129](https://github.com/dotnet/project-system/blob/7267defa7fb7d5790378e21f19ca740a21a36e1c/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependenciesRuleHandlerBase.cs#L129) which compares the Original Item Specs from ProjectReference and ResolvedProjectReference to determine whether a change should be processed. It returns false and hence the design time change is not processed.
