### ISSUE TITLE
'Pack project' command does not work when project build result is up-to-date

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#2923]
Try [Build] -&gt; [Pack 'myproject'] command,
nuget package was not created when project is pre-builted and results 'up-to-date'.

repro:
1. Create new ConsoleApp(.NET Core)
2. Build Solution and repeat it (build process returns 'up-to-date')
3. Try to Pack project, package is not created.

build output (step 3):
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/133251/pack-project-command-does-not-work-when-project-bu.html
VSTS ticketId: 510661_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/152746/package-up-to-date.html

**Comment by panopticoncentral** [comment]
This doesn't appear to be a project system issue. The project system is called for a fast up to date check with the reason `BuildAction.Build`. We report back, correctly, that the project doesn't need to be built because it is up to date. Either the build action needs to be `BuildAction.Pack`, in which case we would not report the project as up to date (since we don't know about packing), or someone upstream from this call needs to consider the fact that the pack action is being called. This needs to move over to the CPS team to look at.

**Comment by bording** [comment]
@panopticoncentral Given that you've closed this and it's not actually fixed yet, is there some other new issue that can be followed instead?

**Comment by panopticoncentral** [comment]
Sorry, should have made clear that you will be able to follow the issue at the original feedback link, https://developercommunity.visualstudio.com/content/problem/133251/pack-project-command-does-not-work-when-project-bu.html

**Comment by bording** [comment]
> Sorry, should have made clear that you will be able to follow the issue at the original feedback link, https://developercommunity.visualstudio.com/content/problem/133251/pack-project-command-does-not-work-when-project-bu.html

What's the reason for moving the issue there instead of keeping something in GitHub? Having to track multiple places to follow issues is a pain, and that feedback site in particular is a pain to navigate compared to GitHub.

**Comment by panopticoncentral** [comment]
I totally understand. The problem is that the bug isn't in the open source portion of the project system, it appears to be in the common project system (CPS) code. Unfortunately, CPS is still closed source and not in this repo, so the developers who work on CPS don't monitor the issues in this repo and have their own internal bug tracker which is connected to the link above.
