### ISSUE TITLE
[Question] Project file editing

### ISSUE THREAD

**Issue by jp2masa** [dotnet/project-system#3061]
I think that when adding a new line in a project file, the caret should be moved (as it is now), but the whitespace chars shouldn't be added, as it works for other files.
Also, it would be nice if EditorConfig settings could apply to project files too.

**Comment by Pilchie** [comment]
@jmarolf is this just the xml editor doing this?

**Comment by jmarolf** [comment]
Yes, the xml editor is that is doing this.  We'd need to update it to understand .editorconfig and virtual whitespace.

**Comment by Pilchie** [comment]
I believe the problem with editorconfig is that we open a copy of the file in the temp directory, so the editor config file doesn't appear to apply.

**Comment by jmarolf** [comment]
@Pilchie yeah, that is a problem.  We should fix this on our side so that this implementation detail does not leak through

**Comment by davkean** [comment]
@jp2masa Can you Help -> Send Feedback -> Report a Problem on the enter should not add whitespace, that's the XML Editor which does not live in this repo. This is the best way to track and get up-votes for the idea.

With regards to EditorConfig, this has now been fixed in 15.7 and we now respect any .editorconfig files in the tree.
