### ISSUE TITLE
Documentation on how solutions work with a mix of the new and legacy project system

### ISSUE THREAD

**Issue by maxinfet** [dotnet/project-system#3146]
Does any documentation on how a solution works with a mix of the new and legacy project system exist? Is this not recommended?

**Comment by Pilchie** [comment]
In general, things should "just work".  There *can* be some issues where having legacy projects referencing SDK projects isn't ideal from a perf perspective, but this is a significant area of focus for us right now.

(This happens because both evaluations and design time builds happen synchronously in the old project system, but async in the new one).  We're working on both making them faster, and making the most annoying ones async.

**Comment by Pilchie** [comment]
Closing for now - let us know if you've got further questions.
