### ISSUE TITLE
Nuget Restore fails when project has multiple target frameworks and conditional assembly names

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/project-system#3160]
When targeting multiple frameworks and having different assembly names for the output assembly, Visual Studio fails to restore the packages.

The error I receive in the output window of Visual Studio is:
```
C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'c:\Projects\Test\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project.
```

My csproj file looks like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;netcoreapp2.0</TargetFrameworks>
    
    <AssemblyName Condition=" '$(TargetFramework)' == 'net462' ">assembly.name</AssemblyName>
    <AssemblyName Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">assembly.name.dotnetcore</AssemblyName>
  </PropertyGroup>

</Project>
```

Something to note, I am able to restore and build using the CLI, but not Visual Studio.

I have tried this in:
Visual Studio Enterprise 2017 15.5.3
Visual Studio Enterprise 2017 15.5.4
Visual Studio Enterprise 2017 15.6.0 Preview 2.0

**Comment by emgarten** [comment]
My guess is that NuGet blocks the nomination here because the asssembly name is different. NuGet uses the assembly name as the id of the project, and this flows transitively to parent projects.

Having a different id for each TFM isn't supported because it would be like having a nupkg with multiple ids.

The workaround here would be to set `<PackageId>assembly.name</PackageId>` so that NuGet doesn't fall back to reading the AssemblyName property.

**Comment by Pilchie** [comment]
Thanks - I'll move to NuGet/Home.

**Comment by Pilchie** [comment]
This issue was moved to NuGet/Home#6461
