### ISSUE TITLE
Create a new .net core/standard project, the dependencies node occurs warning sign.

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/project-system#3184]
## **Description:**
Create a new .net core/standard project, restore, build and run succeeded.
The Output window shows restore finished, no any warnings.
(I try a restore in the command line, restore completed, no any warnings.)
But the dependencies node occurs warning sign.
![image](https://user-images.githubusercontent.com/24784908/35373317-f05e29fa-01d8-11e8-9140-c808daef9225.png)
Solution: Close the solution and reopen
## **Test Environment:**
d15svc/27130.2024 (15.5.4) + master/SDK 2.1.300-preview2-008017:
(Add dotnet-core package source: https://dotnet.myget.org/F/dotnet-core/api/v3/index.json)
dotnet --info:
```
.NET Command Line Tools (2.1.300-preview2-008017)

Product Information:
 Version:            2.1.300-preview2-008017
 Commit SHA-1 hash:  f4a0d2db0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008017\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9

```

**Comment by natidea** [comment]
I've traced the problem to a change in .NET Core 2.1 and a bug in the dependency node. The 2.1 change is the addition of "Version" to the MSBuild properties that flow through our `CollectSDKReferencesDesignTime` task. In 2.0, version is empty:

![image](https://user-images.githubusercontent.com/7732033/35600209-add7de8e-05e1-11e8-8b9b-b2cfdce67198.png)

while in 2.1 version is set:
![image](https://user-images.githubusercontent.com/7732033/35599909-fb2270a2-05df-11e8-91a7-bc6b1fc30a8b.png)

The dependencies node bug is that [Version is included in the ID](https://github.com/dotnet/project-system/blob/294a0e55d95a09c5951ceb1fa1fd6d79206dc787/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DependencyModel.cs#L81) for dependencies, but not used when [mapping from NuGet packages to SDK references](https://github.com/dotnet/project-system/blob/7267defa7fb7d5790378e21f19ca740a21a36e1c/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs#L60-L74) to determine resolved state. In 2.0, this bug has no effect since version is empty anyway.

The warning goes away on reloading the solution because a [different code path](https://github.com/dotnet/project-system/blob/7267defa7fb7d5790378e21f19ca740a21a36e1c/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs#L46-L55) is used to determine resolved state. The code path used depends on the content and number of design time builds and whether the SDK reference occurs before or after the corresponding NuGet package reference. Fix pending.

**Comment by Xiu-Li** [comment]
Verified this:
**Not Repro** on D15.6/27402.02 (15.6 Preview 4) + [release/2.1](https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1) 2.1.300-**preview1**-008019
**Not Repro** on D15.6/27402.02 (15.6 Preview 4) + [master](https://github.com/dotnet/cli/tree/master) 2.1.300-**preview2**-008044
**Not Repro** on D15.6/27405.00 (15.6 Preview 4) + [master ](https://github.com/dotnet/cli/tree/master)2.1.300-**preview2**-008046

**Comment by natidea** [comment]
Fixed with https://github.com/dotnet/project-system/pull/3205
