### ISSUE TITLE
build.cmd fails with spaces in the path

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/project-system#3187]
```C:\W ork\project-system>build.cmd```

>C:\W : The term 'C:\W' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + C:\W ork\project-system\build\Build.ps1 -configuration Debug -restore ...
> + ~~~~
>     + CategoryInfo          : ObjectNotFound: (C:\W:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by davkean** [comment]
I spent a non-trivial amount of time attempting to fix this - and gave up. Here's what I've attempted so that others can learn from my adventure:

- Tried using `-File`. [this breaks the `-FooBar $False` parsing](https://stackoverflow.com/questions/5079413/how-to-pass-boolean-values-to-a-powershell-script-from-a-command-prompt/7302626)
- Tried using `-Command` with a bunch of quotes and ampersand to work cmd and powershell parsing `powershell -ExecutionPolicy ByPass -Command "& """E:\New Folder\PathWithSpace.ps1""" -Build:$False"` 
   - This broke later, when we tried to call MSBuild with the wrong command-line

At this point I'd suggest just removing the space from your repo name.

**Comment by tannergooding** [comment]
@davkean, the second issue (breaking in the call to Msbuild) is an issue in repo toolset, where it doesn't properly quote all the paths (cc. @tmat)

**Comment by tmat** [comment]
@tannergooding Can you point to the place where the paths are not quoted properly?

**Comment by tannergooding** [comment]
Most of these properties need to be quoted: https://github.com/dotnet/roslyn-tools/blob/master/sdks/RepoToolset/tools/Build.proj#L98

**Comment by tannergooding** [comment]
There may be more, but I didn't finish investigating last night.

**Comment by tannergooding** [comment]
Hmmm, actually, this may be specific to something project-system is doing. I don't get the same for another repo-toolset based project (such as dotnet/sdk)

**Comment by tannergooding** [comment]
PR is here: https://github.com/dotnet/project-system/pull/3318.

There is something that breaks if you specify `/p:QuietRestore=true`, remove that and everything works as expected.

**Comment by tannergooding** [comment]
Looks like when `/p:QuietRestore=true` is specified, we call `Exec` rather than the `MSBuild` task:

```
    <Exec Command='$(_MSBuildCmd) "$(MSBuildProjectDirectory)\Tools.proj" /bl:"$(ArtifactsLogDir)RestoreRepoTools.binlog" /nologo /m /v:quiet /t:Restore $(_RestoreToolsPropsCmdLine)'
          Condition="'$(Restore)' == 'true' and '$(_QuietRestore)' == 'true'" StandardOutputImportance="normal" />

    <Exec Command='$(_MSBuildCmd) "$(SolutionPath)" /bl:"$(ArtifactsLogDir)Restore.binlog" /nologo /m /v:quiet /t:Restore $(_SolutionBuildPropsCmdLine) /p:__BuildPhase=SolutionRestore'
          Condition="'$(Restore)' == 'true' and '$(_QuietRestore)' == 'true'" StandardOutputImportance="normal" />
```

The `$(_RestoreToolsPropsCmdLine)` need to be properly quoted/escaped in order to work with paths with spaces.

**Comment by davkean** [comment]
Note, we've fixed most of the issues in the repo - the last one is being tracked externally by: https://github.com/dotnet/roslyn-tools/issues/181.
