### ISSUE TITLE
Default included items not sync after file is removed

### ISSUE THREAD

**Issue by pepone** [dotnet/project-system#3230]
I have this code to remove a item from a project

```
//
// First remove the physical file, if it was included as part of
// a glob that will be enough
//
if (File.Exists(path))
{
    try
    {
        File.Delete(path);
    }
    catch (IOException)
    {
        // can happen if the file is being used by other process
    }
}

EnvDTE.ProjectItem item = project.GetProjectItem(path);
if (item != null)
{
    item.Remove();
}
```

Here the `GetProjectItem` is still returning an non null item, for a item that was default included and that the underlying file has been deleted.

As a result the call to `item.Remove` adds a `<Compile Remove="xxx.cs"/>` that shouldn't  be required when the file has already been removed.

**Comment by Pilchie** [comment]
This happens because the project tree is updated asynchronously, and a new tree is published at some point later after re-acting to the file deletion.  @natidea @lifengl @davkean - any idea on how an extender could wait to observe the changes in an example like this?

**Comment by lifengl** [comment]
There is no reason to write code like this.  ProjectItem.Remove will take care of globbing scenario, and work with source control better.

When you delete files directly, the project system only detects changes through file system watcher.  You cannot control when it happens.  You need either tell the project system what happens through more advanced API for every change, or refresh the tree and wait it’s done.  The later option can be very slow.


Sent from my phone

On Feb 8, 2018, at 8:17 AM, Kevin Pilch <notifications@github.com<mailto:notifications@github.com>> wrote:


This happens because the project tree is updated asynchronously, and a new tree is published at some point later after re-acting to the file deletion. @natidea<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnatidea&data=02%7C01%7C%7C55af5d83ada545f7f77908d56f0f7ba4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636537034638801046&sdata=LPA2ZZjZaOmSRkPUEKvcUVQcmKR7uOWVd%2FnB18wU1gA%3D&reserved=0> @lifengl<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7C55af5d83ada545f7f77908d56f0f7ba4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636537034638801046&sdata=ecy4%2Fs8xFYgJkK%2FGQ5b2rhoRtNJ3OJY5zx8YZgEHCIo%3D&reserved=0> @davkean<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavkean&data=02%7C01%7C%7C55af5d83ada545f7f77908d56f0f7ba4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636537034638801046&sdata=S4F3Igwx0W51vYDjr42HpxBnheV4ijZMYSIHMRAyEWE%3D&reserved=0> - any idea on how an extender could wait to observe the changes in an example like this?

**Comment by pepone** [comment]
That is not what I seeing in my case, my first code was just

```
EnvDTE.ProjectItem item = project.GetProjectItem(path);
if (item != null)
{
    item.Remove();
}
```

With a item originating in a glob, I see .the project ends up with <Compile Remove="XXX.cs"/> and the file is left in the tree

**Comment by lifengl** [comment]
That might be a bug, or the item can be picked up by multiple globbings.  Remove doesn’t delete a file, you might want to call Delete instead.

Sent from my phone

On Feb 9, 2018, at 7:44 AM, Jose <notifications@github.com<mailto:notifications@github.com>> wrote:


That is not what I seeing in my case, my first code was just

EnvDTE.ProjectItem item = project.GetProjectItem(path);
if (item != null)
{
    item.Remove();
}


With a item originating in a glob, I see .the project ends up with and the file is left in the tree

**Comment by pepone** [comment]
Using ProjectItem.Delete solves the problem
