### ISSUE TITLE
The dependencies tree uses quite lots of memory - TreeFlags

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3309]
The dependencies tree uses quite lots of memory.  Do we have any tracking item to reduce its memory foot print?

I noticed the TreeFlags uses 7 M memory, only for very few flags (SupportsRemove ?), but I guess largely different copies of HashSets to those strings.  

Of course, those won’t be enough to reduce usages.  I wonder crossing projects, we may have lots of duplicated nodes in the dependencies tree.  Any change we can save memory by reusing some structure?

![dependency_memory](https://user-images.githubusercontent.com/11638466/36689536-88acd2e6-1ae4-11e8-90bf-97a771d81193.png)

**Comment by Pilchie** [comment]
Ideally, we'd do 2 things here:

1. Re-use common subtrees if we don't today.
2. Not realize this memory unless you expand/search in solution explorer.

**Comment by abpiskunov** [comment]
Chatted with Lifeng offline, and Kevin's proposed point 1. is correct, we might want to try to reuse Dependencies models across projects, since usually there will be many same dependency models coming transitively.  This is not too easy and would require nice synchronization across all projects and their rules updates (that's why originally i did not go there). Immediate and simpler memory optimization that can be done separately is custom TreeFlags in Dependencies to be replaced with other data type (this change can be isolated and would give immediate improvements in memory).

**Comment by Pilchie** [comment]
Let's use this issue to track only the TreeFlags issue.  I'll file another for sharing between projects.

**Comment by drewnoakes** [comment]
The current implementation caches tree flags per dependency model provider, so we aren't doing set operations during update processing. I'd expect this to have much better perf than it used to.

**Comment by drewnoakes** [comment]
This issue has two parts.

1. Tree flag usage: they're now statically cached and reused so there's no duplication of the immutable hash sets used internally to track 'extended' string flags.

2. Reusing sub-trees: #3335 is tracking this
