### ISSUE TITLE
The visual effect of the dependencies node makes customer to wait on it

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3430]
Feedback from Svet.  I think he has a very good point on it:

There are two issues with the current UI:

1, the dependencies UI doesn’t make difference between references are not resolved correctly vs. resolving references is still on-going.  The bright yellow warning sign makes customers to feel something is wrong, which is not the case.
  Svet suggested that we should have a different UI indicator when the dependencies tree is not fully loaded/resolved, which can be less visual impactful  in the solution explorer.  Basically, we want an overlay icon for "loading..." state.

2, Svet also suggested that the top level dependencies node should not indicate “loading…” state, but only the second level nodes need show this state.  (We still want to show the warning icon on the top level node, when something failed to be resolved.)  The point is that a “loading” state will make customers to feel that they have to wait the background process to finish.  In 90% time, customers don’t need wait it.  
  The traditional reference node doesn’t have this visual effect to indicate design time build is on-going.  And C++ project system doesn’t even try to resolve references by default.  It is a visual effect to make customers to feel the .Net core project system is slower than those project systems.

In the future, when a customer tries to expand the dependencies tree, and it hasn’t been resolved.  We can potentially raise the priority of the background work for that specific project to get it done earlier than other projects.

**Comment by jjmew** [comment]
This is a good candidate to run an experiment to figure out what is the right user behavior

**Comment by cartermp** [comment]
Copying over from #4363

We should distinguish between the following:

* Have not yet resolved an item
* Have attempted to resolve an item and failed to do so

The latter case is when a warning icon would appear as it does today.

In the former case, we should also provide some UX indicating that we're still resolving. We don't want to have tons of little spinny icons everywhere, since that's distracting and could be a perf hit for large solutions. Some proposals:

* Parenthetical text on the top-level item being resolved - `Newtonsoft.Json 12.0.1 (resolving...)`. There are three sub-options:
   * Expanding this node gives the text "Resolving..." below it
   * Expanding this node gives a spinner icon
   * It is not possible to expand this node until it has resolved
* Spinner icon on the top-level item being resolved - `<icon> Newtonsoft.Json 12.0.1`, where the icon replaces the current icon that allows for exapnd/collapse. There is no ability to expand/collapse when resolving.

I personally prefer the parenthetical. This would be what it could look like:

![image](https://user-images.githubusercontent.com/6309070/52668391-4657b200-2ec8-11e9-914c-dfce6061074e.png)

I would also prefer to disable expandability while resolving, since there's nothing reasonable to show aside from more redundant information.

Placing a UX Board-approved spinner on the top-level item is something I would not prefer, but if that is desired, so be it 😄

**Comment by drewnoakes** [comment]
Point 1 is covered by #5044.
Point 2 is covered by #5045.
