### ISSUE TITLE
Reopening #2687: Single File Generators sill broken since 2017

### ISSUE THREAD

**Issue by hallambaker** [dotnet/project-system#3545]
Reopening #2687 as the problem still hasn't been fixed. Please actually test solutions before claiming that they are solved. The need to register the single file generators under the new project GUIDs was understood and the code does exactly that.

https://github.com/dotnet/project-system/issues/2687

Custom tools still do not work with Standard projects.

I use a lot of custom tools in my projects. These all run fine in VS2015 and VS2017 with .net framework and/or .net core projects. They do not run at all under Standard projects. The box for custom tool is there, I can fill it in but the custom tool is never run, not even when I invoke it directly.
I had thought it was some problem with the tools not registering the correct GUID. But just now I discovered that I have the exact same behavior regardless of whether the tool is present on the system at all. Specifically, my tool is registered as Protogen.
In a Framework project, declaring the custom tool as
Protogen - Works normally. - correct NotProtogen - Throws tool not found error - correct
In a standard project

Protogen - Does nothing, no error - wrong

NotProtogen - Does nothing, no error - wrong
I can find no mention of custom tools not working. It will be something of a hassle if I have to resort to running batch files to invoke the tools manualy.

The code for the tools I use is at the following URL. One of the tools generates the binding code for single file generators.

https://github.com/hallambaker/PHB-Build-Tools

**Comment by davkean** [comment]
The original bug was in lieu of another bug with more information https://github.com/dotnet/project-system/issues/3535, not resolved as fixed.

@hallambaker It's not clear on the repro steps involved to repro your situation, you mention it works fine with .NET Core projects but not .NET Standard but they are the same code path. Can you please upload a project that exhibits the exact issue you are encountering so that I can make sure we're referring to the exact same situation.

**Comment by davkean** [comment]
Tagging @Dark-Bond on this version too.

**Comment by hallambaker** [comment]
When the issue was looked at previously, it was determined that there was a bug in the code that checked the custom tool run.

It is not necessary to set up any project, if you enter 'doesnotwork' as the custom tool in a standard project, the command run custom tool does nothing, there is no error report. In .net framework it reports an error so obviously there is a difference in the code paths.


The code for all the tools is in this repo, there are about a dozen.
https://github.com/hallambaker/PHB-Build-Tools

One of the simplest tools is the one that generates the bindings to VSIX:
https://github.com/hallambaker/PHB-Build-Tools/tree/master/VSIXBuild/Goedel.Tool.VSIXBuild

The project that builds the tool set is here.
https://github.com/hallambaker/PHB-Build-Tools/tree/master/Pack/VSIX

These tools all run fine in a .net framework project.

**Comment by davkean** [comment]
@hallambaker Above when you say ".NET Standard" are you referring to "Shared Projects"?

**Comment by hallambaker** [comment]
It is not a shared projects issue. The lack of custom tools in shared projects is an issue but it is a separate issue and one I expect to go away when it becomes possible to write VSIX extensions using .NET standard libraries.

**Comment by davkean** [comment]
> write VSIX extensions using .NET standard libraries.
Is that what this bug is about?

**Comment by Dark-Bond** [comment]
Yes, I second that.  Please produce a working example and we'll be able to figure it out from there.

**Comment by davkean** [comment]
@hallambaker @Dark-Bond I'm not assuming there isn't a bug here - I'm just very confused. I have no idea what the bug is or the repro, we have a bunch of single file generators working against .NET Core/.NET Standard. In the few bugs on this, I've asked for:

1) Generated pkgdefs from your build

-or-

2) A sample project that repros the problem

Without either we're not going to make progress. I can provide a sample if I get time, but right now I'm just going to continue work on https://github.com/dotnet/project-system/issues/3535 which is to make single file generators from .NET Framework automatically light up on .NET Core/.NET Standard projects. If you can provide one of the above things I can make sure we work your extensions.

**Comment by davkean** [comment]
@Dark-Bond Please make sure the "project type" in the registration attribute is wrapped in braces: https://github.com/dotnet/project-system/issues/3535#issuecomment-390645950.

**Comment by davkean** [comment]
I'm going to track this bug via https://github.com/dotnet/project-system/issues/3535 - it has the latest discussion.
