### ISSUE TITLE
Changes to Solution made outside the IDE are no longer prompted to reload

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/project-system#3546]
This is not a [performance improvement](http://twitter.com/davkean/status/992016165915344896). I don't know how others work with the IDE, but sometimes I find it necessary to make textual adjustments, reload a folder here, file there, etc, and it is nice to have the IDE prompt. Sure, Git could also change contexts on you under the hood, as well. Perhaps expose that behavior as an option.

**Comment by mwpowellhtx** [comment]
Furthermore, changes to the Solution file do not prompt. Yet, changes to each Project state are automatically presented? How is this trade-off considered a performance improvement?

Come on, folks; think this thing through.

**Comment by davkean** [comment]
That tweet refers to the behavior we changed where we stop auto-reloading the entire solution (without prompts), to loading individual projects. This mimics the behavior we've had in the new project system from the command-line since we first shipped.

Can you expand on your workflow and what changed/broke in 15.7 so that I route the issue to team that owns this experience?

**Comment by mwpowellhtx** [comment]
@davkean Simply this: I'm suggesting there may also be changes to the Solution file itself, apart from the projects. These are apparently now ignored.

**Comment by davkean** [comment]
As before, we reload the entire solution if there are solution changes. Do you have video/repro where this is not the case?

**Comment by mwpowellhtx** [comment]
I can't seem to reproduce the issue. I'll keep an eye on it and if I come across that use case again, I'll report it back.

**Comment by davkean** [comment]
Okay feel free to open a new issue if you run into it.

**Comment by davkean** [comment]
@mwpowellhtx Was this situation you ran into specifically for solution file? Because I've just found a bug that might explain your situation, which appears to be a regression in 15.7.

We appear to not reloading or prompting to reload documents that were opened from a previous open of the solution, but have not yet been made "active". This leads to them getting out of sync with disk. Would this describe your behavior? I've filed this internally.

**Comment by mwpowellhtx** [comment]
@davkean It sounds familiar, but I don't recall the specific scenario. To answer you question, however; yes, it was to do with the solution file alone.

I will say this; :+1: for treating files in general as part of a project, notwithstanding noteworthy exceptions, special instructions, etc, listed in the project file. This makes for a fairly terse, compact project file.
