### ISSUE TITLE
Make ResX editor deterministic when saving into .resx file

### ISSUE THREAD

**Issue by martinsuchan** [dotnet/project-system#3575]
**Current behavior:**
The ResX/ResW editor for resource strings has one specific feature that makes development harder than necessary. **By default when adding new strings to the resx file, new strings are appended at the end of the file, instead of sorting in those new strings alphabetically.**  
This causes all kinds of issues when 2+ developers are working in branches and adding new resources strings to the same file. Each branch than contains different new strings at the end of the file, and **merging such files causes conflicts, requiring manual edits, that are quite error prone**.

As a workaround our team uses one hidden feature of the ResX editor that can be used for sorting all strings alhabetically. If I'm in the ResX editor and press Ctrl+A to select all, Ctrl+X to cut all and Ctrl+V to paste all, and save it, it saves all strings sorted alphabetically. It's important to note that this **cutting and pasting in ResX editor is quite slow**. With resource file with about 200 strings, both cut and paste takes several seconds. This could be optimized for sure - the file is only abut 50 kB in size. Ideally this cut and paste dance should not be needed at all!

**Expected behavior:**
The ResX editor should by default sort-in all new strings alphabetically to prevent merge issues when new strings are added in different branches, and without need to use cut&paste hacks for manually sorting the strings.

Another request, the **ResXFileCodeGenerator should not generate this line in the generated .cs file:**
```
Generated: 05/10/2018 12:13:23
```
Adding this string in different branches causes merge errors that needs to be manually resolved. There is no benefit in keeping this line in the generated file.

**Comment by davkean** [comment]
@martinsuchan I investigated this. The behavior is actually the opposite; by default when adding new strings to ResX, new strings will be appended in _ordinal_ order. If someone manually modifies the file and puts a string out of order, it will detect and consider that file "unordered" and new resources will be added to end of the file. The behavior is actually almost identical to how I would have implemented it; it does that to avoid reordering an entire file just when you've removed or added a single resource. I suspect this was a behavior introduced after ResX files were created. 

I could consider a slight change to the algorithm to prevent the situation where you've actually added two resources in different branches but they end up clashing because of the same prefix. Dev merges just these two resources out of order - breaking our "ordinal" check. In this case, maybe we say that if 90% of the file is ordered, then we consider it all ordered.

The relevant code is here: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb#L936.

**Comment by davkean** [comment]
@wjk Here's another Resource Designer one - make note I've spent very little time thinking about this.

**Comment by wjk** [comment]
@davkean I'm not entirely certain the best way to go about fixing this one. The best solution I can think of is to implement manual reordering of resx items in the UI (either via drag-and-drop or cut-and-paste). The user would then have to clean up the resx file themselves, but once that's done the default sorting behavior should kick back in. Furthermore, since we're only moving a few rows at a time (often just one), the slowdown related to cut-and-pasting the entire resx file should be avoided. I'll have to play around with this when I get home from work today.

Unfortunately, I don't think I can solve the issue raised with the ResXFileCodeGenerator writing out timestamps, because that code doesn't seem to be in this repository. This one may need to be handled internally.

**Comment by wjk** [comment]
Upon further research, my earlier technique of reordering the items via drag/drop or copy/paste won't really work, because the column headers sort the contents of the DataGridView when clicked, without reordering them in the back-end file. This would throw everything off, and I don't think reordering the file when the column headers are clicked is really called for.

@davkean I haven't a clue how to go about solving this one, unfortunately. I'm afraid you'll have to ask someone else.

**Comment by davkean** [comment]
Okay, thanks for looking at it.

**Comment by martinsuchan** [comment]
Just an update. Installed VS 2019 16.1 and the behavior is still the same.  

Whenever I need to add any item into our resx/resw file, I need to perform the same ritual over again:
- add the new string
- sort alphabetically by clicking the `Name` header
- Ctrl+A select all
- Ctrl+X cut
- Ctrl+V paste all, this causes regeneration of the resx file in alphabeticall order.

This ritual is necessary because when two different strings are added in different branches without sorting, merging these branches leads to collision.

Fixing the resx/resw editor to always sort all items alphabetically would be amazing life saver. Even opt-in for this behaviour would help for sure.

**Comment by davkean** [comment]
The behavior is opt in, see my comment above: https://github.com/dotnet/project-system/issues/3575#issuecomment-392248041.

**Comment by martinsuchan** [comment]
I was curious and tried to start with simple sorted list and really new strings are sorted-in as expected. But our list of resources is sorted as well, how come new strings are not sorted in anymore?

After lots of test I discovered, that the sorting algorithm in the ResX UI editor is different than the `ResourceFile.vb` string comparison algorithm you mentioned!
In other words if I sort my strings by clicking the Name header and save them sorted this way, the comparison algorithm might not be satisfied with the way the UI editor sorted my strings.

Simple repro, I have Resource.resx file with only these three values in this order:
```
  <data name="aaa" xml:space="preserve">
    <value>value1</value>
  </data>
  <data name="aaAA" xml:space="preserve">
    <value>value2</value>
  </data>
  <data name="aaAAA" xml:space="preserve">
    <value>value3</value>
  </data>
```
When I try to sort these reosurces by clicking the Name header, I get exactly this order.
BUT if I try to add new string with id `aa`, it's added to the end because the original list is not considered sorted by the `ResourceFile.vb` algoritm.

**Simple test and probably the cause of my problem:**
```
> String.Compare("aaa", "aaaa", StringComparison.Ordinal)
-97
> String.Compare("aaa", "aaAA", StringComparison.Ordinal)
32
> String.Compare("aaa", "aaAA")
-1
```

So the actual goal of this issue is now:
**Use identical string sorting algorithm in ResX visual editor and in `ResourceFile.vb` file.**

**Comment by davkean** [comment]
@martinsuchan Good find, I've fixed this: https://github.com/dotnet/project-system/pull/4864.

**Comment by davkean** [comment]
The fix for this will appear in 16.2 Preview 2.

**Comment by martinsuchan** [comment]
@davkean Any chance this fix will make it into VS2017 as well?

**Comment by davkean** [comment]
This will not make it into 2017. That release is considered done.
