### ISSUE TITLE
Files do not always get copied to the referencing project's output directory

### ISSUE THREAD

**Issue by andrewslavin** [dotnet/project-system#3637]
Steps to reproduce:

1. In .Net Core 2.0, create a solution with console app project `A` and class library project `L`.
2. Make `A` reference `L`.
3. Add text file `T` to project `L`.
4. Right-click on `T`, select properties, change `Copy to Output Directory` to `Copy if newer`.
5. Build the solution for the 1st time - `T` gets copied to the output folders of both `A` and `L`.
6. Edit `T` and build again - `T` gets updated in the output of `L`, but NOT `A`.

If after editing `T` you `Rebuild` solution, then `T` gets updated in the output folder of both projects, but if you just `Build`, it only gets updated in the output of `L`.

**Comment by andrewslavin** [comment]
@Pilchie I do not know how build process works behind the scenes, but looks like it's the former. If along with changing `T`, I make any other change that would force project `A` to build, then `T` gets updated in `A`'s output. If I force `A` to build by selecting `Rebuild Solution`, `T` gets updated in `A`'s output as well. But if VS decided that `A` is up to date and does not build it, `T` only gets updated in the `L`'s output.

**Comment by Pilchie** [comment]
Are these traditional .NET Framework projects, or SDK-Style .NETCore/.NETStandard projects?

**Comment by andrewslavin** [comment]
They are .Net Core projects, with "new" style `csproj` files. Both `csproj` files start with:

``

**Comment by andrewslavin** [comment]
Hi @Pilchie, @panopticoncentral. Any update on this? Were you able to reproduce?

**Comment by davkean** [comment]
Dup'ing against https://github.com/dotnet/project-system/issues/4665.

**Comment by ocallesp** [comment]
@davkean 
The file T.txt is not recogniced as an output for project A. 
If we make changes to T.txt, the fast-up-to-date will detect no changes in project A and hence no need for compilation. 
Since the compilation of project A is not needed, we don't tell msbuild to copy T.txt to project A directory.

It seems that we need to make the changes to BuildUpToDateCheck.CheckCopyToOutputDirectoryFiles()  to detect T.txt as an output when in project A.
what do you think ?
