### ISSUE TITLE
VB: Add support for Language Version 16 

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#3733]
This issue is tracking that we add support for VB 16 in the project system before dev16 ships.

Relates to https://github.com/dotnet/roslyn/pull/28522 (adding LangVersion 16 in Roslyn)
Relates to https://github.com/dotnet/project-system/issues/2088

**Comment by KathleenDollard** [comment]
VB 16 will ship with .NET Core 3.0, not VS 16.

**Comment by davkean** [comment]
While it will ship at *same time* as .NET Core, it ships in the box of VS so it will come with a VS release. When will projects be able to opt into VB 16? For example, you can opt into C# 8.0 starting now.

**Comment by jcouv** [comment]
I would recommend doing this change along with NullableOptionsContext and WarnVersion for convenience.. We can mark "16" as "beta" as we did for C# if the drop-down entry is visible before the RTM release.

**Comment by paul1956** [comment]
If there is a dropdown it is needed for the features added on 15.1 and 15.5 which for many are largely invisible or difficult to access today.

**Comment by paul1956** [comment]
Not sure if this is separate or should be included here but the immediate window  in 15.x seems to use last major version (15) not anything in the project file as its version. Seems this either should be setable or default to latest or to the project file.

**Comment by davkean** [comment]
That would be better filed over http://github.com/dotnet/roslyn, I agree it should default to the latest version - not the last major.

**Comment by paul1956** [comment]
Has any thought as to what Language will be the default for the VB that ships with first production release of VS2019, will it still be 15, or 15.5 or 16 or something else. I don't know what it means to Mark the version as 16 Beta when code is looking for a number.

**Comment by paul1956** [comment]
The latest Visual Studio 2019 Preview 2 includes feature(s) that require VB 16, the preview defaults to "15" if nothing is specified in project file and 15.5 if Latest is specified. Setting it to 16 in project file produces a warning (below) and but defaults to 16. Setting is to a random value like "1600" defaults to 15. Setting the value in code always works.
![image](https://user-images.githubusercontent.com/12789369/56999447-fd78d680-6b63-11e9-90c5-863465be2325.png)
This is not a Roslyn issue exactly according to comments in Roslyn this value comes from Project System through MSBuild and command line.

**Comment by KathleenDollard** [comment]
@cartermp What is the plan for selecting VB versions?

@paul1956 Which features are you looking for in VB 16? I don't think there is anything in VB 16 in the current previews, that work is coming in later previews.

**Comment by cartermp** [comment]
@KathleenDollard Same as before. When there's a new version, it should be available in dropdowns, and when VB16 ships it should be the default.

**Comment by paul1956** [comment]
@KathleenDollard 
First the issue is not selecting (though I would love if that was supported), you can't set version 16 in Project File.
Comment as line continuation is in VS 2019.1 Preview 2, all the tests pass, and from code where you set parsing version manually to 16, you can use the feature. From the IDE you can manually set version to 16 in the project file (same as always) you always get a warning. In some projects like the one above it works and others projects setting to 16, defaults to version 15. There is also some new null coalescing stuff I wanted to look at that shipped with VS 2019.0. Everything from 15.3 and 15.5, like the ability to name none trailing arguments which shipped with 15.5. For VS 2019 LangVersion.Latest is 15.5 but the default (when nothing is specified or what you enter is wrong) is 15. The example above is a case where 16 is partly understood and you see a comment after _ with no error. I can post results of another project where setting to 16 causes 15.3 and 15.5 features to give errors. The Project-System has comments that say MSBuild is involved and I have seen that stepping through it, MSBuild passes 16 but with only the Null Coalescing feature and I think that is where the warnings/errors I am seeing are coming from.
VS2019.0 shipped with VB V15.5 but defaults to VB 15 so the argument that customers need to wait till VS 16 to seems odd.

**Comment by paul1956** [comment]
The code below is what concerns me and may be causing the issue I am seeing and why 15 seems to be the default.
```VB
         Friend Shared Function ApplyVisualBasicParseOptionsFromCompilerOptions(parseOptions As VisualBasicParseOptions, ByRef compilerOptions As VBCompilerOptions) As VisualBasicParseOptions
                 parseOptions = parseOptions.WithPreprocessorSymbols(
                     GetConditionalCompilationSymbols(GetOutputKind(compilerOptions), If(compilerOptions.wszCondComp, "")))
 
                 ' For language versions after VB 15, we expect the version to be passed from MSBuild to the IDE
                 ' via command-line arguments (`ICompilerOptionsHostObject.SetCompilerOptions`)
                 ' instead of using `IVbcHostObject3.SetLanguageVersion`. Thus, if we already got a value, then we're good
                 If parseOptions.LanguageVersion <= LanguageVersion.VisualBasic15 Then
                     parseOptions = parseOptions.WithLanguageVersion(compilerOptions.langVersion)
                 End If
 
                 Return parseOptions _
                     .WithDocumentationMode(If(Not String.IsNullOrEmpty(compilerOptions.wszXMLDocName), DocumentationMode.Diagnose, DocumentationMode.Parse))
             End Function
```

**Comment by davkean** [comment]
@jcouv What exactly is this tracking anymore? The ability to select language versions has been removed from C#, so it won't be used for tracking adding this to VB. @paul1956 If you are still running into issues with VS picking the wrong version - can you open a bug against Roslyn http://github.com/dotnet/project
