### ISSUE TITLE
Port WinFormEditorProvider from CPS to here

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3823]
This adds support for opening a WinForms designer from a source file:

https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/134764?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FEditor%2FWinFormEditorProvider.cs&discussionId=1355860&_a=files

**Comment by davkean** [comment]
Should put this behind a new capability describing WinForms.

**Comment by wjk** [comment]
@davkean Since the milestone is 16.2, does this mean that the changes required to support the WinForms designer in a Core project will ship in the VS 16.2 update? If so, I can't wait.

Also: Are there any issues (related to WinForms designer support or otherwise) I could help out and create a PR for? Thanks!

**Comment by davkean** [comment]
WinForms for .NET Framework scenarios should quasi work (sans a few bugs) in 16.1. 16.2 we fixed a few more bugs, but there's nothing really to do. This bug is just a cleanup bug for layering purposes.

WinForms for .NET Core is very far away and cannot give you a timeframe, the majority of work for this is in closed source so nothing really to help. Our help wanted issues are tracked via https://github.com/dotnet/project-system/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22.

**Comment by davkean** [comment]
This is merged in, I'll leave it open to track the deletion of the CPS code.

**Comment by davkean** [comment]
This is now done.
