### ISSUE TITLE
Only appeared the first time .Net Core 2.2 Preview create netcoreapp2.2 targeting apps by default when used with 15.8

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/project-system#3909]
### Description:
1. Create a new .net core project via VS, open project properties page, for "Application" tab, the "Target framework" is  ".NET Core 2.2" by default.
2. Then re-create a new or more .net core project via VS, the default TFM is ".NET Core 2.1".

### Test Environment:

D15.8/28010.2014(15.8.2) + CLI/SDK [2.2.100-preview1-009349](https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20180820-01/final/assets/Sdk/2.2.100-preview1-009349/dotnet-sdk-2.2.100-preview1-009349-win-x64.exe)
dotnet --info:

> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.100-preview1-009349
>  Commit:    3f45457548
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.2.100-preview1-009349\
> 
> Host (useful for support):
>   Version: 2.2.0-preview-26820-02
>   Commit:  b4726350b3
> 
> .NET Core SDKs installed:
>   1.1.10 [C:\Program Files\dotnet\sdk]
>   2.1.401 [C:\Program Files\dotnet\sdk]
>   2.2.100-preview1-009349 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0-preview1-35029 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0-preview1-35029 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0-preview-26820-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> 
> 
>

**Comment by richaverma1** [comment]
@YunWeiaa, can you check if this repros on command line as well?

**Comment by Pilchie** [comment]
@jmarolf can you take a look at this?

**Comment by YunWeiaa** [comment]
Note: 
1. This doesn't happen when creating projects from command line.
2. The same results of the validations presented when creating projects using Dev15.9, i.e. only appeared the first time .Net Core 2.2 Preview create netcoreapp2.2 targeting apps by default via VS.

**Comment by richaverma1** [comment]
This is blocking for 2.2 Preview 2 which is shipping early next week. @Pilchie, @jmarolf please prioritize this.

**Comment by Pilchie** [comment]
@vijayrkn - how should we move this?

**Comment by vijayrkn** [comment]
@Phenning - Can you please create an issue in vsts and take a look?

**Comment by YunWeiaa** [comment]
I can still select 2.2 manually, and it remains as 2.2.

**Comment by phenning** [comment]
@YunWeiaa, From your description, it appears like you are just creating .NET Core Console application project. Can you confirm?

If it is just a console application being created, I think I know what is going on here. 

This appears to be a timing issue with our logic for determining which version of a template to create. In addition to the wizard code having constants set which should match our shipped version, the code also downloads a configuration file which allows some updating of these constants after we ship.  

In this case, it appears like that configuration file was not yet downloaded when the first template was created, so the logic determining which .NET Core version to create had no upper bound, which resulted in a 2.2 template being created. During the initial creation this file is downloaded asynchronously. That is the reason that the subsequent console applications are being created as 2.1 projects, because the file has been download and is now defaulting to 2.1, which is the desired behavior for 15.8
.

**Comment by richaverma1** [comment]
@phenning what can we do to get a consistent experience such that the first project is also created in 2.1?

**Comment by phenning** [comment]
@richaverma1 

In 15.8, I don't think we have a good solution, as all the code is within Visual Studio.

In 15.9, however, this should be addressed fully by the Use Preview SDK checkbox that has been added to the .NET Core options within Visual Studio.

**Comment by richaverma1** [comment]
@phenning, @nguerrera, I have 15.9 Preview 2 build installed along with 2.2 Preview 1 build. The option - 'Use Preview SDK is checked', but projects are targeting 2.1 by default. They use the 2.2 Preview 1 runtime though, I see that when I build the project. Should the projects be targeting 2.2? Is this functionality added?

**Comment by phenning** [comment]
The functionality, I believe, should already be in Preview 2. However, we still have the remote configuration file set to use 2.1 in 15.9 due to Preview 1, since Preview 2 or higher is what will be recommended for 2.2. Unfortunately, we do not have the capability to distinguish between preview versions in the configuration file, only servicing releases, so we are waiting to address this via an update to the configuration file as Preview 2 is shipped.

**Comment by richaverma1** [comment]
thanks @phenning , I understand the current design. It would be so ideal to have one setting that controls both - SDK and template.

**Comment by richaverma1** [comment]
@phenning, when is this expected to be fixed? The configuration file does not seem to be updated yet. We are shipping 2.2 Preview 3 on 10/17.

**Comment by phenning** [comment]
@richaverma1, I just sent the updated feed file on to be uploaded.

**Comment by richaverma1** [comment]
@phenning, we should be able to see the change as soon as the file is uploaded, correct?

**Comment by phenning** [comment]
@richaverma1, that is correct.
