### ISSUE TITLE
Coordination of updates in DependenciesProjectTreeProvider

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4140]
Whenever a dependency's snapshot changes, `DependenciesProjectTreeProvider` queues up an async `BuildTreeForSnapshotAsync` call, serialising operations with a lock and task:

https://github.com/dotnet/project-system/blob/730c8bb5672b28618017f4e68d31466a1d08f372/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs#L367-L383

However `BuildTreeForSnapshotAsync` is not actually async. It always returns `Task.CompletedTask`:

https://github.com/dotnet/project-system/blob/730c8bb5672b28618017f4e68d31466a1d08f372/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs#L387-L412

It does, however, kick off some async work, but ignores the task.

The other call to `SubmitTreeUpdateAsync` (during initialisation) doesn't wait on the returned task either.

I believe the current handling (`_treeUpdateLock`, `_treeUpdateQueueTask` and JTF) can be replaced with a lock-free cancellation token sequence, relying on `SubmitTreeUpdateAsync` to do the serialisation.

I'll put a PR together with these changes. If I'm barking up the wrong tree, please let me know.

**Comment by abpiskunov** [comment]
What is happening there is "queueing" we are updating tree in the order updates were received and code is scheduling update tasks in order. You are right that we do schedule tree updates by SubmitTreeUpdateAsync and ignoring it's returning task, that is because SubmitTreeUpdateAsync is also queuing it on CPS side and exiting. The code can be tuned up if you like that, however make sure you keep the order in which SubmitTreeUpdateAsync are scheduled.

**Comment by drewnoakes** [comment]
@abpiskunov thanks for the confirmation. I've made some changes in #4143 that would benefit from your review.
