### ISSUE TITLE
Disposal of ITargetedProjectContext

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4162]
The cross-target dependencies code has a bunch of logic around ensuring `ITargetedProjectContext` instances are disposed (in `AggregateCrossTargetProjectContext` for example), however it looks like this might be unnecessary.

This is an internal interface and its sole implementation `TargetedProjectContext` implements `Dispose` with an empty body.

Is this vestigial? Can I strip it out? Am I missing something?

//cc: @abpiskunov

**Comment by abpiskunov** [comment]
I was hoping to reuse this targeted aggregation logic with Language Services at that time since Dependencies and Language services were very similar in terms of rules and targets. It doe snot look like Dispose is needed there, there is nothing to dispose, it is just a left over from the original design. Feel free to get rid of it.

**Comment by davkean** [comment]
Bear in mind that this code is basically going to disappear when it moves to the same model we'd used in the language-service rewrite.
