### ISSUE TITLE
Why escape model ID in dependency ID?

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4196]
A dependency's ID is (usually) composed of:

1. the target framework name,
2. the dependency's provider type, and
3. a "model ID", which is usually a path.

These three strings are concatenated with `/` between.

In the process, the model ID is escaped:

- `/` becomes `\`
- `..` becomes `__`

Why does this escaping happen? As far as I can tell this is just an opaque identifier. I'm hoping we can remove this escaping as part of some work to reduce string allocations.

https://github.com/dotnet/project-system/blob/470e13362e2a8898845af5df177afd17d10d1595/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Dependency.cs#L393-L394

//cc: @abpiskunov

**Comment by abpiskunov** [comment]
It is needed because so weirdness in between Graphnodes communication and CPS, i don't remember specifics, but without normalization our nodes were not processed correctly, since we put id into node's filePath property which somewhere along the way in Graph logic (or CPS) was treated as path and was trimmed/modified and we could not see actual ID in graph nodes logic.

**Comment by drewnoakes** [comment]
Thanks for the explanation.

**Comment by Pilchie** [comment]
Similar to https://github.com/dotnet/project-system/issues/2559 and https://github.com/dotnet/project-system/issues/2558?

**Comment by drewnoakes** [comment]
@Pilchie fantastic, thanks.
