### ISSUE TITLE
Determining target framework in msbuild target when using TargetFrameworks

### ISSUE THREAD

**Issue by Im5tu** [dotnet/project-system#4284]
I have something resembling the following msbuild target:
```xml
<Target Name="EvaluateProperties" BeforeTargets="Restore">
  <Message Importance="High" Text="TargetFramework: $(TargetFramework)" />
  <Message Importance="High" Text="TargetFrameworks: $(TargetFrameworks)" />
</Target>
```
And I want to be able to determine the current framework that is being build, given the following in the csproj:
```xml
<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
```
How can I determine the target framework in the context of the build prior to the restore, or is this not possible? From the msbuild log, I do see it passed through to the inner build task as `AdditionalProperties=TargetFramework=net461` but then `$(TargetFramework)` evaluates to `''`

**Comment by Pilchie** [comment]
@dotnet/dotnet-cli any suggestions here?

**Comment by rainersigwald** [comment]
> From the msbuild log, I do see it passed through to the inner build task as `AdditionalProperties=TargetFramework=net461` but then `$(TargetFramework)` evaluates to `''`

How did you determine that?

The a project with `<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>` will be built **three** times in a normal build:

1. With no specified `TargetFramework` (the "outer" build). This usually doesn't do much work, just forwards to the inner builds.
1. With `TargetFramework=netstandard2.0`.
1. With `TargetFramework=net461`.

 If you define a target in the project file, it is present in all inner and outer builds. But it may not run in all the builds, depending on where it's hooked into the build process.

In your case, you specify `BeforeTargets="Restore"`. Because NuGet wants to restore _for all TFMs used in the project_, it doesn't call `Restore` on the "inner" builds. Instead, the outer-build version of `Restore` calls a more-specific target on the inner builds, then combines the results. I think that's why you're seeing only an unset `$(TargetFramework)`.

Are you trying to run logic to modify PackageReference items? NuGet provides an extension-point target for that: https://github.com/NuGet/NuGet.Client/blob/8c78fe56c15b78d539d404c43c94238c8b311497/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L151-L159

**Comment by Im5tu** [comment]
That extension point was exactly what I was looking for. Thanks, the custom target ended up looking something like this:

```xml
<Target Name="MyThing" BeforeTargets="CollectPackageReferences" Condition="$(TargetFramework) != ''">
    <!-- Do Stuff -->
</Target>
```
