### ISSUE TITLE
Dependency node no longer show content of packages

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4313]
Version: Version 16.0.0 Preview 2.0 [28321.115.d16.0stg]

**Expected:** 
![image](https://user-images.githubusercontent.com/1103906/48924044-1cfe3a00-ef08-11e8-985d-85233575f299.png)

**Actual:**
![image](https://user-images.githubusercontent.com/1103906/48924053-2daeb000-ef08-11e8-8339-15fdd6c501ec.png)

**Comment by drewnoakes** [comment]
_(note to self)_

This might be caused by an exception I'm seeing in CPS's `SimpleItemNode.ProjectPropertiesContext` (line 204) where the `TreeNode` property is not an `IProjectItemTree` and it throws. It's actually an `IProjectTree` (`Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree`).

Unclear at this point whether something in CPS changed or if I broke something in how we interact with the tree. I don't yet know the tree API.

**Comment by drewnoakes** [comment]
Bisect shows I introduced this in caf7fd22c33f11a65bda15e4ea931189198f4956. I'll fix it and add tests soon.
