### ISSUE TITLE
When project load failed, cannot double-click to edit

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4325]
![image](https://user-images.githubusercontent.com/350947/49105737-596bc600-f279-11e8-99b6-bc73ea2d2112.png)

When a project fails to load (due to invalid XML in this case) you cannot double-click to edit it.

**Comment by davidwengier** [comment]
I'm not sure this is something we want to fix. As far as I'm aware when a project doesn't load, we aren't part of the equation (since the project couldn't load, the project system that is supposed to handle it is unknown/unloaded), which not only means the fix for this would be in VS itself, it also means that it would apply to every project type in existence. Making double click to edit a project fail a VS feature is beyond the scope of the work we're trying to do IMO.

Unless I'm mistaken of course :)

**Comment by jjmew** [comment]
Closing this bases on @davidwengier  comments

**Comment by davkean** [comment]
This smells like we're shipping the org... :)
