### ISSUE TITLE
GetSelfAndDescendentsBreadthFirst allocating 8.2% 

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4339]
![image](https://user-images.githubusercontent.com/350947/49383324-5f95f280-f710-11e8-8f6b-18575fc5bf60.png)

This method can pool `Queue<>` objects, and it looks like half the time only the count is needed anyway.

**Comment by drewnoakes** [comment]
PR with fix in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/153974

**Comment by lifengl** [comment]
ValidateRelease is only used in the CPS debug build, and is not expected to be used in a released product.  In the debug build, an extra tree is recreated after each step to compare with the tree changed after applying a delta.  This is excessively expensive validation logic, and the debug build is basically not usable to load a large project.  Actually, that validation logic is mostly used in CPS unit tests to ensure tree mutation logic is correct.  Can you profile the product with a release build to see whether this problem is a real problem?

**Comment by drewnoakes** [comment]
Yes, there was a debug build of CPS in my hive. So it seems these changes in the above-linked PR will have less impact than advertised. I'll continue discussion on that PR.
