### ISSUE TITLE
Support editing AssemblyInfo in project properties

### ISSUE THREAD

**Issue by diverdan92** [dotnet/project-system#4409]
This is a feature request to make it easier to set assembly info metadata in Visual Studio.

**Comment by davkean** [comment]
By assembly info, what exactly do you mean? 

- In legacy, we have Project Properties -> Application -> Assembly Information to edit AssemblyInfo.cs.
- In CPS, we don't have AssemblyInfo.cs per se, as we auto-generate it based on properties in the project. This can be edited via Project Properties -> Package tab.

It sounds like this bug is really "make it more obvious that that's assembly info in that page?"

**Comment by jjmew** [comment]
We don't have a concrete understanding of what is being requested. Closing as No Repro.
