### ISSUE TITLE
Add support for .razor files

### ISSUE THREAD

**Issue by danroth27** [dotnet/project-system#4468]
ASP.NET Core 3.0 adds support for Razor Components, a new way to write client-side web UI. Razor Component files are Razor files (like .cshtml files) that get compiled to .NET classes that render to a structured presentation of the DOM. This allows the runtime to efficiently figure out exactly which parts of the DOM need to be updated. Because Razor Components use a fundamentally different compilation model from MVC views/pages they will have a different file extension: .razor.

Broadly speaking we need all our partner teams that special case .cshtml files today to also support .razor files. In .razor files you should get a rich C# editing experience and rich debugging experience in both web and class libraries just like you do with .cshtml files today. We want to land this work to support .razor files in the first update preview of VS2019 so that folks can start trying it out with the new Razor Component support in .NET Core 3.0.

@cartermp @rynowak

**Comment by rynowak** [comment]
The only place I'm aware of in the project-system that special cases `.cshtml` is right here: https://github.com/dotnet/project-system/blob/6aa36644148b762129f0c50a4f342d0a46e88ce1/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/DynamicItemHandler.cs#L19 - which passes us off to the language service so that we can integrate with them.

From the point of view of the project-system this should be the same - it will be ItemGroup `Content`, but the `.razor.` file extension.

**Comment by cartermp** [comment]
Tagging @jjmew as well
