### ISSUE TITLE
Project system guid when downgrading to legacy project

### ISSUE THREAD

**Issue by jnyrup** [dotnet/project-system#4564]
**Visual Studio Version**: 15.9.6

**Summary:** 
I had a project `A` which was created as a new style csproj, but eventually downgraded to legacy style csproj.
After downgrading `A`, a solution which referenced `A` using the `9A19103F-16F7-4668-BE54-9A1E7A4F7556` guid could no longer build `A`.

`A` is and it's files are visible in the solution explorer, but I noticed two oddities:
* `A` does not show up in the configuration manager
* When right clickick on `A` in solution explorer, built, rebuild and clean buttons are not available.

**Steps to Reproduce**:

1. Create a new solution with a new style project.
2. Ensure the project is referenced using `9A19103F-16F7-4668-BE54-9A1E7A4F7556` in the sln file
3. Close VS
4. Replace the content of `A.csproj` with its equivalent legacy style project.
5. Open VS

**Expected Behavior**:
Either:
* load `A` as legacy project, or
* give a error/warning that I'm trying to load a legacy project as a new style project.

**Actual Behavior**:
`A` is (partly?) loaded, but cannot be built

**User Impact**:
I'm not sure what to write here?

**Comment by davkean** [comment]
Thanks for the bug report. [It is a bug](https://github.com/dotnet/project-system/issues/1821) that we're putting 9A19103F-16F7-4668-BE54-9A1E7A4F7556 in the solution at all, and going to dupe this against it. The fix for this situation is change 9A19103F-16F7-4668-BE54-9A1E7A4F7556 -> FAE04EC0-301F-11D3-BF4B-00C04F79EFBC in the solution.
