### ISSUE TITLE
CPS needs to return a value for ProjectItems.Kind

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4675]
For Visual Basic properties pages support (#4249) we need CPS to return a value for ProjectItems.Kind so that various methods on `ResourcesFolderService` can work.

**Comment by davkean** [comment]
What's the exact API?

**Comment by davidwengier** [comment]
Shouldn't have said "implement". It's just a property on OAProjectItems that currently returns null, and there is a TODO on the base class about returning a value too. Its just a string, which is a guid, which comes from one of the VS constants, eg. [vsProjectItemKindPhysicalFile ](https://docs.microsoft.com/en-us/dotnet/api/envdte.constants.vsprojectitemkindphysicalfile?view=visualstudiosdk-2017) in this case.

**Comment by davkean** [comment]
Do you mean "ProjectItem.Kind"? If so, we should be returning values for files and folders, are we returning the wrong value for a certain node?

**Comment by davidwengier** [comment]
No, ProjectItem*s*.Kind: https://docs.microsoft.com/en-us/dotnet/api/envdte.projectitems.kind?view=visualstudiosdk-2017

**Comment by davkean** [comment]
Ah, okay didn't realize this existed.

Looking at [legacy's implementation](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvenus%2Fproject%2Fvsproject%2Fobjdte.cpp&version=GBlab%2Fd16.0stg&line=1422&lineStyle=plain&lineEnd=1422&lineStartColumn=31&lineEndColumn=39), if the ProjectItems hangs off the root, it returns ProjectItem.Kind of the project node (which I didn't think there was ProjectItem for the root folder - I'm assuming this is basically returning `Project.Kind`), otherwise returns `GUID_ItemType_PhysicalFolder`.

**Comment by davidwengier** [comment]
Interal PR open: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/172647?_a=overview

**Comment by davidwengier** [comment]
PR has been completed.
