### ISSUE TITLE
*.CoreCompileInputs.cache causes projects to rebuild unnecessarily until the third build

### ISSUE THREAD

**Issue by Treit** [dotnet/project-system#4736]
**Visual Studio Version**:
VS 2019 16.0.1

**Summary:**
SDK-style projects, even a trivial .NET Core project, build the entire project graph both the first and second time the project is built, even when nothing has changed between the first and second build.

While for trivial projects this is not a huge issue, for large projects with many dependencies this means that you can waste many minutes waiting for the project to build itself and all dependencies a second time.

**Steps to Reproduce**:

1. Create a new .NET Core console application project in Visual Studio 2019.

2. From the 'Build' menu, choose 'Clean Solution' to ensure you are starting from a clean state.

3. From the 'Build' menu, choose 'Build Solution' or press F6.

4. Note the 'output' Window says that it rebuilt the project, with the output:
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

5. From the 'Build' menu, choose 'Build Solution' or press F6 for a second time.

6. Note that, once again, the project was rebuilt and the output window says:
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

7. From the 'Build' menu, choose 'Build Solution' or press F6 for a third time.

8. Note that the output window says:
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

**Expected Behavior**:
The project should not be rebuilt the second time, since nothing changed from the previous build. On the second build command, the output window should say:
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

**Actual Behavior**:
The project rebuilds everything on the second build. On the second build command, the output window says:
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**User Impact**:
For large projects and for scenarios where you do something like change a single unit test after the initial build and then try to rebuild just the unit test project, you end up building the entire project graph unnecessarily. This can be very expensive, wasting the time of the user and leading to a significant loss in productivity.

**Notes**:
The rebuild is triggered by a "CoreCompileInputs.cache" file for the project. If you enable "FastUpToDate" logging under Tools | Options | Projects and Solutions | .NET Core you can see output like the following on the second build:

FastUpToDate: Input 'C:\Users\mtreit\Source\Repos\HelloWorldCore\HelloWorldCore\obj\Debug\netcoreapp2.1\HelloWorldCore.csproj.CoreCompileInputs.cache' has been modified since the last up-to-date check, not up to date. (HelloWorldCore)

Note that this behavior impacts full .NET Framework projects (like .NET 4.7.2 projects) that use the new SDK-style project format, not just .NET Core projects.

**Comment by jmarolf** [comment]
@Treit which version of the .NET SDK are you using?

It should tell you if you run this from the commandline
```console
dotnet --version
```

**Comment by Treit** [comment]
> @Treit which version of the .NET SDK are you using?
> 
> It should tell you if you run this from the commandline
> 
> ```
> dotnet --version
> ```

#> dotnet --version                                                                                                                                                                                                               2.1.602

**Comment by pavelchadnov** [comment]
I tried using the latest .net core version, the issue is still there

dotnet --version output:
3.0.100-preview4-011223

**Comment by pavelchadnov** [comment]
There is a race condition.

BuildUpToDateCheck stores last up-to-date check time. It's updated at the end of every check and this is the problem. Msbuild creates/updates the CoreCompileInputs.cache file later than LastCheckTimeUtc is set and on the next rebuild it appears that CoreCompileInputs.cache was modified after LastCheckTimeUtc because of this lag

1) BuildUpToDateCheck is run at 00:00:00 initially, returns false as CoreCompileInputs.cache does not exist yet. LastCheckTimeUtc is set to 00:00:00
2) MSbuild rebuilds the project as BuildUpToDateCheck returned false. The build creates CoreCompileInputs.cache file at 00:00:01
3) On the next rebuild BuildUpToDateCheck is called again and it checks if CoreCompileInputs.cache Modification time is greater than LastCheckTimeUtc. It is, so the method returns false again

**Comment by drewnoakes** [comment]
@Treit and @pavelchadnov thank you for the great bug report and analysis.

To fix this we won't be able to use `DateTime.UtcNow` in the up to date check.

@panopticoncentral @davkean @rainersigwald can you see a problem with the up to date check reading the last change time on `CoreCompileInputs.cache` (or some other file) on each invocation as a proxy for determining when the last build occurred?

**Comment by rainersigwald** [comment]
The fast up to date check should not make any decisions based on the timestamp of `CoreCompileInputs.cache`. It is an internal implementation detail of the build.

How is that making it into the list of input files?

**Comment by davkean** [comment]
https://github.com/dotnet/project-system/blob/8b00b4fb93f6d7a7c8162527da163d1c05581cd8/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L387

**Comment by rainersigwald** [comment]
Hmm, so introduced with #3486 to support triggering an incremental build after input files get deleted.

I don't think that's the right solution; I think you'll need to do something similar in spirit to what the cache itself does: remember the list (or a hash of the list) from the last evaluation, and rebuild when the list/hash changes.

The project system should not use the last modified time on `CoreCompileInputs.cache` for anything; it's deliberately _not_ the timestamp of the last build, but the timestamp of (a middle implementation-detail part of) the last build _that changed compiler inputs_.

**Comment by davkean** [comment]
There's another hit over here: https://github.com/dotnet/fsharp/issues/4904, but its every project in the solution. I've moved this to 16.3.

**Comment by drewnoakes** [comment]
I spent some time looking at this today.

Removing `CoreCompileInputs.cache` from the list of inputs fixes the above case but introduces a worse bug, described in #3245:

1. Build
1. Remove an input file (included via glob)
1. Press <kbd>Ctrl</kbd>+<kbd>F5</kbd>
1. No rebuild occurs and the last build of your app launches

This is worse in the sense that it's actively misleading users into thinking they are running the latest code when in fact the previous build is running.

The core of the problem is that our `IBuildUpToDateCheckProvider` implementation is not idempotent. Checking whether the project is up to date changes its internal state such that calling it again straight away will make the project appear up to date. If no build occurred in between, it will give an incorrect answer.

Written another way, the implementation (prior to #3486) assumes that when it returns `false` (i.e. not up to date) then a build is guaranteed to occur (and that a call/build operation does not overlap with another call/build operation).

In the <kbd>Ctrl</kbd>+<kbd>F5</kbd> case, `IsUpToDateAsync` is called twice, yielding an incorrect answer whenever that answer depends upon internal state that changes when `IsUpToDateAsync` is called (such as whether the list of input files has changed).

I can see two ways forward, either:

1. Accept the requirement that when `IsUpToDateAsync` returns `false` a build will occur, and that queries/builds don't overlap with one another, then go and fix whatever's calling this method twice in the <kbd>Ctrl</kbd>+<kbd>F5</kbd> case.
2. Parse MSBuild's input cache file and compare it with our own understanding of the project to determine if we're up to date.

Neither of these approaches is that great. I'm hoping there's something I've missed.

//cc: @davkean @rainersigwald @panopticoncentral

**Comment by davkean** [comment]
What about a build exactly causes IsUpToDateAsync to return the correct answer? What if a build is attempted, but is cancelled early, either via an early error, or cancelled by the user or an extension (restore on build case, for example)?

**Comment by drewnoakes** [comment]
Many factors affect the result of the fast up-to-date check:

https://github.com/dotnet/project-system/blob/master/docs/repo/up-to-date-check.md#what-is-checked

Cancellation should be correctly handled. An input will still be newer than an output.

If we only used timestamps, then after a successful build if an input was removed the timestamps make it seem as though everything is up to date.

The project system knows when inputs change. We don't categorically know the set of inputs of the last build. Currently we just say "inputs changed" on the _next_ call to `IsUpToDateAsync`, but that clears the dirty flag. So if we get called more than once (as in the <kbd>Ctrl</kbd>+<kbd>F5</kbd> case) we give the wrong answer on the second call (leading to #3245).

The fast up-to-date check can use file timestamps to observe when the most recent build occurred. However there's no equivalent ground truth for the set of inputs, unless perhaps we start using MSBuild's cache. Above @rainersigwald says this is internal to MSBuild. I'm wondering if we can have an API to query for this.

Without either such an API or the guarantee that a build always happens after querying `IsUpToDateAsync` (and competes before the next query) we will always have one of various bugs around this.

**Comment by rainersigwald** [comment]
In the current implementation, the cache isn't parseable; it's a hash of a list of paths. It was done that way because we only care if _something_ changed, and don't really have to care about _what_.

https://github.com/microsoft/msbuild/blob/07d3c25a1461dfba3fcc1cc9b28cb8accd4e32b9/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3416-L3446

One option might be to ignore the file and instead diff the item `CoreCompileCache` against the last build. I'm not sure if that's better or worse than using the lists of Compile and ReferencePath that the project system presumably already has--nice to have a single source of truth for "what's in the list?" (it does change, `DefineConstants` there is a newish addition), but potentially less performant than reuse, and the project system tracks more inputs than just `CoreCompile`'s.

Looping @benvillalobos in here since this is related to microsoft/msbuild#4472.

**Comment by jeffsaremi** [comment]
How can i check with dotnet sdk has this fix?

**Comment by davkean** [comment]
This was fixed in Visual Studio 16.3.

**Comment by jeffsaremi** [comment]
Do you know what dotnet-sdk that corresponds to? Or do you know how I can go about finding that? thanks

**Comment by jeffsaremi** [comment]
Found out! 
Since SDK 3.0.100-preview7-012821
https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by jeffsaremi** [comment]
Found out! 

Since SDK 3.0.100-preview7-012821
https://dotnet.microsoft.com/download/dotnet-core/3.0

And also I tried it and indeed solved my rebuild issues.
Would like to thank whoever fixed the problem

**Comment by davkean** [comment]
This works with any version of the .NET SDK. If you are hitting this problem via the command-line then this is a different issue that you should file over http://github.com/dotnet/msbuild.

**Comment by springy76** [comment]
I'm on netcore SDK 3.1.200 using VS 16.5.1 and this problem hits me every day since many months: After a Rebuild a following Build always builds everything again because FastUpToDate reports some seconds difference. Can't understand how this could be declared fixed at any time.

**Comment by drewnoakes** [comment]
@springy76 please open a new issue with steps that reproduce the problem. It would be helpful if you enable the output of verbose up-to-date logging (Options | Projects and Solution | SDK-Style Projects).
