### ISSUE TITLE
NuGet restore should use BulkFileOperation

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4781]
It's possible, due to timing, to get into a situation where we reevaluate with half a package's contents on disk, here's an example of this:

![image](https://user-images.githubusercontent.com/1103906/57054724-b4e32980-6cd9-11e9-8a9b-2cdca3b14fe4.png)

We should investigate whether NuGet should turn on bulkfileoperation at the beginning of a restore and turn it off at the end of restore to avoid us unnecessarily reevaluating until all files are written and loaded.

**Comment by davkean** [comment]
Spoke to Pavel Ustinov over o figure out if this new API was a good fit for this scenario. It is, but there is a cravats - it doesn't allow overlapping of operations[1] - so it makes it very hard to coordinate an existing operation that may have begun as part of a branch switch, so we'll need to fix that first before we use it.

Next step is to figure out who will actually call it - we don't have enough context at the project-level, only NuGet really knows that a restore operation is occurring so will chat with them about it.

[1] They tried to allow this via a ref-counting mechanism but failed to come up with a good design so they disabled it.

**Comment by davkean** [comment]
As a followup to this, I spoke to Nikolche Kolev from NuGet, and it seems this will be easy to use BulkFileOperation in restore; it has a well defined start and end.

**Comment by davkean** [comment]
Hit count here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/989345?src=WorkItemMention&src-action=artifact_link.

**Comment by davkean** [comment]
Triage: This needs to be spec'd out a little more so that other folks can pick it up.

**Comment by davkean** [comment]
@Lifengl What's blocking this?

**Comment by lifengl** [comment]
I think we need bring the source control team on board to handle the case of switching branches during a NuGet restoration.

Sent from my phone

On Aug 20, 2020, at 6:54 PM, David Kean <notifications@github.com> wrote:

﻿

@lifengl<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7C43def691a19c40025a6808d8457512a9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335716405263143&sdata=qFb9fz%2B8ofVuyoSser7SAqzCvFdLqfBmwmeDqpkbqSw%3D&reserved=0> What's blocking this?

**Comment by panopticoncentral** [comment]
We had a discussion meeting around this, here is the summary:

The primary concern from the source control team is that:

1. Allowing multiple users of BFO will introduce random time delays when user tries to do branch switching because of a random background operation.
2. It might lead even more people to use BFO for other reasons, which may lead to other delays as in the 1st issue.

Based on the discussion, the majority of the NuGet restoring work is downloading new version of packages in newly created folders.  We don’t need freeze the system during that phase.  The only time we want to freeze reloading/reevaluating is the time it takes to refresh generated files. Based on that, if NuGet can limit the refresh time to the small window, the random time delay should not be a problem for this scenario. Also, if the window is small enough to contain refreshing limited number of files, we may not need extra work to support priorities & cancellation token for now.

From NuGet:
NuGet is currently doing work for each project.  The simple solution is to limit the batch during the end of the work for individual projects, to prevent project reloading/reevaluating between the time gap of updating .props/.targets/asset file. A more complex solution is to separate downloading and project updates into two phase in a batch. That will require more work in the NuGet side.

From Project System:
- We think the perf gained by batching individual project updates might not be great, because we have already have a sliding window for reloading files. (Although this might not be accurate, because the asset file is handled separately from .props/.targets. But that will be less than batching projects together.)
- We want to measure how much we can gain by batching the entire batch with BFO today to see potential gain of the work.
- Project system may need extra work to align DT build/NuGet restoring work after a set of projects are changed. They are not optimized even after we use BOF.

From SCC:
- BFO freezes 5 sub system, including locking text buffer for files to be changed in the operation, calling HandsOff for IVsTrackProjectDocuments, freezes VS file watching service, allows VS to control whether to reload projects or solution, and a few others. NuGet restoring feature doesn’t need almost any of them, other than it need ask CPS projects to freeze reloading/revaluating projects because of .props/.targets/asset file changes.
- NuGet/CPS may consider a different API for this reason.  However, the drawback is that we have extra public contract to maintain & it is partially overlap with BFO.
- SCC team hopes BFO APIs to be updated and completed in. As it is today, it is public documented, but any 3rd party’s usage is actually not supported. If BFO doesn’t allow 2 callers to use it at the same time, ideally, the user experience to wait between them should be centralized.

Next Step:
- [ ] NuGet team to measure how much performance gain we can get by using BFO for a batched operation. We may need further project system side change to make it more efficient.
- [ ] If the performance gain justifies the need to do this work, we can decide whether to define a new contract, or reuse BFO. (I think BFO is still preferred at this point.)
- [ ] We currently don’t have budget to improve BFO for other 3rd party usages (SCC team wants a new telemetry event to measure whether there is any 3rd party to use it.)
- [ ] We should minimize the time of locking system in BFO in the NuGet by grouping local file updates. In that case, we don’t need worry about the delay, and potentially, we don’t need add priority & cancellation handling beyond the current set of APIs.

**Comment by cheenamalhotra** [comment]
Have been recently noticing this error when building for .NET Framework:

`##[error]E:\nuget\microsoft.sourcelink.common\1.0.0\build\InitializeSourceControlInformation.targets(3,81): Error MSB4022: The result "" of evaluating the value "$(_MicrosoftSourceLinkCommonAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.`

Any suggested workaround?

**Comment by nkolev92** [comment]
We probably won't need this anymore, given that we've added https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivsnugetprojectupdateevents-interface  https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivssolutionrestorestatusprovider-interface and https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivssolutionrestoreservice4-interface

cc @drewnoakes @ocalles
