### ISSUE TITLE
Common properties, like ProjectDir, do not appear when echoed from PreBuildEvents

### ISSUE THREAD

**Issue by davidhunter22** [dotnet/project-system#4916]
Applies Visual Studio 16.1.3 and 16.2 Preview 2
.NET Core 2.2 and .NET Core 3.0 Preview 6

I am porting an existing C# solution to the new new build system. This all went well apart from a `<PostBuildEvent>` in a project file. After investigation it was found that various predefined properties no longer appear to exist for instance
```
  <PropertyGroup>
    <PostBuildEvent>
      echo ProjectDir='$(ProjectDir)'
      echo SolutionDir='$(SolutionDir)'
    </PostBuildEvent>
  </PropertyGroup>
```
produces 
`1>ProjectDir=''`
`1>SolutionDir='C:\Users\Sensiblestuff\...\'`
So SolutionDir seems to work while ProjectDir comes out empty. The odd thing is that if I look in the Macros screen in the event editor in the Visual Studio GUI properties I see an entry for ProjectDir with the correct expected value. So there appears to be a disconnect between the two.

**Comment by jmarolf** [comment]
Related to https://github.com/dotnet/project-system/issues/1569

Because of the order in which properties are evaluated in MSBuild this cannot work with sdk-style project files where most defaults are implicitly defined after your project file.

There are two options here:

## 1: use the property page editor or define your own targets

If you go to the properties page and add this:
![image](https://user-images.githubusercontent.com/9797472/59455785-c126d000-8dc9-11e9-975e-978826fef51a.png)

It will add this target which will work as expected and be transposed correctly from the project file to the ui and back.
```XML
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="echo ProjectDir='$(ProjectDir)'&#xD;&#xA;echo SolutionDir='$(SolutionDir)'" />
</Target>
```

## 2: explicitly import properties and targets in the same order as the old-style projects

Transform this:
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <!-- ... Other properties in you project files ... -->
  <PropertyGroup>
    <PostBuildEvent>
      echo ProjectDir='$(ProjectDir)'
      echo SolutionDir='$(SolutionDir)'
    </PostBuildEvent>
  </PropertyGroup>
  
</Project>
```


into this:

```XML
<Project>

  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.props" />
    <!-- ... Other properties in you project files ... -->
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />

  <PropertyGroup>
    <PostBuildEvent>
      echo ProjectDir='$(ProjectDir)'
      echo SolutionDir='$(SolutionDir)'
    </PostBuildEvent>
  </PropertyGroup>
  
</Project>
```
