### ISSUE TITLE
Visual Studio new projects not adhering to Microsoft.CodeAnalysis.FxCopAnalyzers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5274]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/653066/visual-studio-new-projects-not-adhering-to-microso.html)._

---
When one creates a new Visual Studio project from one of the templates, and then analyze it using the FxCopAnalyzers (and probably other Microsoft.CodeAnalysis analyzers) then there are many warnings.

My suggestion is that Microsoft should update their templates to adhere to this, and ideally all other Roslyn analyzers.

---
#### Jane Wu [MSFT] on 7/22/2019, 03:53 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by davkean** [comment]
Triage: Can you investigate what warnings/errors show up by default and send this back to triage?

**Comment by ocallesp** [comment]
I don't thing we can have a template (for beginner developers) code with 0 warnings using Analyzers. I would only make changes to templates if an important security checkers detects issues. 

The templates show only few warnings using the Analyzer.
We can:
1) Fix the templates so that Analyzer will show 0 warning/errors.
    disadvantage: Will make the code more complicated to understand for beginner developers.
	advantage: Analyzer will show 0 warnings
	
2) Mark this as won't fix.
	disadvantage: - The advanced developer should fix only few warning.
			       - Or disable the warning using the codefix
				  
3) Make the minimum changes to templates in places not relevant to the beginner developer.
	advantage: less warnings after the Analyzer is installed.

**Console App**
warning CA1303: Method 'void Program.Main(string[] args)' passes a literal string as parameter 'value' of a call to 'void Console.WriteLine(string value)'. Retrieve the following string(s) from a resource table instead: "Hello World!".
 warning CA1801: Parameter args of method Main is never used. Remove the parameter or use it in the method body.

**Windows Forms (.net)**
warning CA2000: Call System.IDisposable.Dispose on object created by 'new Form1()' before all references to it are out of scope.

**ASP.NET Core Web Application (Empty)**
warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable
warning CA1822: Member ConfigureServices does not access instance data and can be marked as static (Shared in VisualBasic)
warning CA1822: Member Configure does not access instance data and can be marked as static (Shared in VisualBasic)
warning CA2007: Consider calling ConfigureAwait on the awaited task
warning CA1801: Parameter services of method ConfigureServices is never used. Remove the parameter or use it in the method body.

C**lass Library (.Net Standard)** 
No warnings

**Blazor App**
warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable
warning CA1822: Member GetForecastAsync does not access instance data and can be marked as static (Shared in VisualBasic)
warning CA1822: Member Configure does not access instance data and can be marked as static (Shared in VisualBasic)
warning CA1822: Member ConfigureServices does not access instance data and can be marked as static (Shared in VisualBasic)

**ASP.NET Core Web Application (Model-view-controller)**
warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable
warning CA1822: Member ConfigureServices does not access instance data and can be marked as static (Shared in VisualBasic)
warning CA1822: Member Configure does not access instance data and can be marked as static (Shared in VisualBasic)

**ASP.NET Core Web Application (API)**
warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable
warning CA1822: Member ConfigureServices does not access instance data and can be marked as static (Shared in VisualBasic)
warning CA1822: Member Get does not access instance data and can be marked as static (Shared in VisualBasic)
warning CA1822: Member Configure does not access instance data and can be marked as static (Shared in VisualBasic)
