### ISSUE TITLE
Please include why a project is not up-to-date in the build window even when set to minimum verbosity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5353]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/356825/please-include-why-a-project-is-not-up-to-date-in.html). Please vote and comment there to make sure your voice is heard._

---
<p>We often hit unexpected projects being out of date which kills developer efficiency, yet debugging is hard because it's not practical to leave output verbosity up at diagnostic all the time.  The out-of-date reason is usually a line or two long.  Please include that in the minimum verbosity level info.</p>

---
#### Fiona Niu[MSFT] on 10/15/2018, 00:30 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about five business days on our next steps. </p>
#### Ruben Rios [MSFT] on 2/15/2019, 00:33 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

#### Shrey Khosla [MSFT] on 2/26/2019, 03:17 PM: 

<p>I agree with this.</p>

#### Cedric Caillaud [MSFT] on 2/26/2019, 04:30 PM: 

<p>I also have experienced the same limitations and support this request</p>

#### Vicente Cartas Espinel [MSFT] on 2/26/2019, 04:37 PM: 

<p>This would be really useful.</p>

**Comment by drewnoakes** [comment]
Currently the up-to-date check has three log levels:

![image](https://user-images.githubusercontent.com/350947/63985513-76d50580-cb13-11e9-911d-5f3fb2931d96.png)

The default is `None`. `Info` produces several lines per project build. `Verbose` can produce hundreds.

Rather than change the default behaviour for all users and start logging output when `None` is selected, we could add a new log level (e.g. `Minimal`) that results in only a summary in the case of projects being out of date. It would sit between `None` and `Info` and produce just a single output line per project that's considered _not_ up-to-date.

**Comment by VicenteCartas** [comment]
Would that also include the reason why the project is considered out of date?
