### ISSUE TITLE
Add "Enumeration" item to the "Add New Item" dialog box

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5368]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/391739/add-enumeration-item-to-the-add-new-item-dialog-bo.html). Please vote and comment there to make sure your voice is heard._

---
<p>Hi, I would like to suggest a little productivity improvement to the &quot;Add New Item&quot; dialog box by adding the &quot;Enumeration&quot; item to the list. Actually, we need to select some of the existing templates and modify it in order to create a new enum in a C# project. I think it would be interesting if the &quot;Enumeration&quot; item already existed in the list, also helps students and beginners by providing an enum blank template.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/49714-add-new-item-dialog-box.png"> Image:49714-add-new-item-dialog-box.png</a></p><p>Thanks so much!!</p>

---
#### Jane Wu [MSFT] on 11/27/2018, 00:30 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by cartermp** [comment]
Suggestion: also have a struct template, and ordering would be:

* Class
* Struct
* Enum

**Comment by KWodarczyk** [comment]
This is awesome idea, it's soo annoying and time consuming that you have to chose class and then change the type :(

**Comment by DanielSpindler83** [comment]
I wonder if mentioning that JetBrains Rider has this ability would maybe move things along?
I have a list of things now that VS cant do and one day it will be the tipping point to move to Rider.....

**Comment by dannevesdantas** [comment]
It's not a super important kind of thing, but for those newbies learning C# it might be useful.

**Comment by drewnoakes** [comment]
Thanks everyone for your interest in this feature. It's something I'd love to see added too.

This GitHub repo doesn't own the templates associated with .NET projects. This issue was originally created from a [feedback ticket](https://developercommunity.visualstudio.com/t/add-enumeration-item-to-the-add-new-item-dialog-bo/391739). The best way to signal the importance of this item is to vote on that ticket, so that the right team sees your votes.

I'm going to close this issue as adding support here doesn't help the feature actually get delivered. Please vote on the [ticket](https://developercommunity.visualstudio.com/t/add-enumeration-item-to-the-add-new-item-dialog-bo/391739).

**Comment by smitpatel** [comment]
Also related https://github.com/dotnet/sdk/issues/28915
