### ISSUE TITLE
Fix the TODO in TargetFrameworkProjectConfigurationDimensionProvider to read TargetFrameworks from an MSBuild evaluation at the unconfigured project level

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#547]
Currently we are working around this by reading the MSBuild project file XML, but we probably need to read the property via an evaluation.

**Comment by mavasani** [comment]
@lifengl for assistance - I am not sure if this is even possible. Can we read properties from an MSBuild evaluation at unconfigured project level? Currently, our dimension provider just reads the project xml for TargetFrameworks property.

**Comment by mavasani** [comment]
I am closing this out - I don't think this is needed, if at all possible.

**Comment by mavasani** [comment]
Re-activating this issue, as unless this is fixed, we cannot support cases where TargetFramework or TargetFrameworks needs an evaluation to get the correct property value.

**Comment by srivatsn** [comment]
I believe this has now been resolved per @RaulPerez1. @davkean can you confirm?

**Comment by srivatsn** [comment]
I verified that this is fixed.

**Comment by am11** [comment]
@srivatsn, this seems to be partially fixed in devenv 15.1.

I have multi-project solution.

In old csproj days, I extracted `<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>` from all csproj files in MyCommon.props, along with other common properties, no issue with props inheritance.

With new csproj, when I extracted out  `<TargetFramework>net462</TargetFramework>`, VS 2017 RTM was giving me migration dialog (as if the project is xproj). VS2017 Update 15.1 seems to fix that issue as there is no more migration dialog, but now I get:

> C:\Program Files\dotnet\sdk\1.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(84,5): error : Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework=''. They must be specified explicitly. [C:\test-new-csproj\example.csproj]

with both VS build as well as dotnet-build. Is it the issue for dotnet/sdk repo?

**Comment by davkean** [comment]
@am11 Can you open a new bug with a repro project?

**Comment by am11** [comment]
@davkean, apologies; I had an error in `<Import Project` path to props file (as I moved the csproj files one level up), which is why it was not picking up the TFM `<TargetFramework>net462</TargetFramework>`. 😊

**Comment by bernd5** [comment]
@am11 
I had the same issue like you, see: https://github.com/dotnet/sdk/issues/1056

I quickfixed it by declaring a "dummy" target framework before my Common.props import which will override it...
