### ISSUE TITLE
[Cloud] C# files are being opened under Miscellaneous files

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5725]
_Copied from [AB#1031759](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1031759)_

**Steps to reproduce:**

1. Create a connected environment  (instructions here)
2. Us the following repo: https://github.com/dotnet/project-system.git 
3. Open the solution
4. click on C# file

**Result:** The file gets open under "Miscellaneous files"

**Comment by tmeschter** [comment]
Workaround when hosting the server locally: point the server to the solution file rather than a folder path. There seems to be an assumption in LiveShare that once a "workspace" is open you won't/can't switch to another. However, in the cloud environment you fill often start in the "folder" workspace and then transition to a "solution" workspace, and that isn't being respected right now.

**Comment by tmeschter** [comment]
This issue is now being tracked by https://github.com/dotnet/roslyn/issues/40362.
