### ISSUE TITLE
"Modernize" CPS repo

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#5750]
The repo is based off of VS-Platform and a few months ago they did several modifications including:

- [x] Update toolset to use VS 2019
- [ ] ~~Pin .NET SDK version used to build~~
- [ ] ~~Bump nuget.exe used to 5.0.2~~
- [ ] Only set the cloud build number once at the start of the build #6004
- [ ] Speed up first use of dotnet.exe #6003
- [x] Dramatically improve perf when downloading tools (e.g. nuget.exe)
- [ ] ~~Fix build warnings about packages with license URLs~~
- [ ] ~~Fix build warnings about symbol indexing (by switching from GitLink to SourceLink)~~
- [x] Make VS insertions auto-approve and auto-complete

The changes can be seen in https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS-Platform/pullrequest/188440?_a=overview

**Comment by davkean** [comment]
Triage: We should split this into individual issues around things we actually want to do. For example, CPS doesn't use NuGet.exe so the upgrade NuGet version isn't needed.

**Comment by wjk** [comment]
Just curious: Why is this a public issue if the CPS code is all private? It doesn't provide any value for me as an external contributor.

As an aside while I'm here: I would really, _really_ appreciate some actual documentation for CPS. I am forced to decompile the CPS assemblies just to see the available API surface, and even then I have no clue how to use what I find. [The VSProjectSystem repo](https://github.com/microsoft/VSProjectSystem) is dead as a doornail, and many of the resources referenced there don't even exist anymore. This repo is the only example that I can find that is more complex than "Hello, World", but due to its complexity using this repo as a guide doesn't work very well. Thanks for looking into this for me!

**Comment by davkean** [comment]
Rather than tracking our team's work across multiple bug trackers, we're tracking all our work in this respository. Our team contributes to CPS, hence this bug.

Understood your frustration with the VSProjectSystem repo, I can only suggest you open a Developer Community Feedback item and I'll route it to the team that owns it.

**Comment by davkean** [comment]
@dmonroym Please split this up for 16.6 and send them back to triage.

**Comment by dmonroym** [comment]
Will revise the work items and open each one as new. I'll close this issue once that's done.
