### ISSUE TITLE
Old projectInstance & catalog snapshots can be leaked in TargetedDependenciesSnapshot code

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#5836]
TargetedDependenciesSnapshot can retain old copy of IProjectCatalogSnapshot, when it doesn't need update.

The code will return the previousSnapshot, when no change need to be applied. However, the previousSnapshot will reference a copy of the old project catalog snapshot, which holds a copy of old project instance.

When the project is changed, a new copy of project instance will be created. Because the dependency tree is less likely to be updated, it ends up to retain two copies of the project evaluation results.

**Comment by lifengl** [comment]
I think the updating was skipped earlier. Like the DependencyRulesSubscriber/DependencySharedProjectsSubscriber, which all skip raise dependencies changed event, when the change delta is empty.

**Comment by drewnoakes** [comment]
@lifengl if the `IProjectCatalogSnapshot` is the same object reference, then it's true that the returned `TargetedDependenciesSnapshot` can be `previousSnapshot`.

Is the issue that `ProjectCatalogSource` doesn't necessarily produce a new value on every project update, and therefore we end up with a transitive reference to an old instance of project evaluation?

**Comment by davkean** [comment]
https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencySharedProjectsSubscriber.cs#L73

**Comment by drewnoakes** [comment]
When there are no changes here, the event is not raised and the snapshot is not updated, hence we retain the old catalog/project instance:

https://github.com/dotnet/project-system/blob/6f7b36b354063ab26401269a968640ff292d9de5/src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs#L135-L139

**Comment by lifengl** [comment]
@drewnoakes : I still see this memory leak in the 16.7 preview 4 build.

**Comment by lifengl** [comment]
@drewnoakes : I believe the leak still exists, due to the code in DependencyRulesSubscriber.Handle short-cut the event, when there is no project subscription changes.

Here is my suggestion, which won't completely fix the leak, but would prevent the worse part with very little changes:

I checked TargetedDependenciesSnapshot.Catalog, although it captures IProjectCatalogSnapshot, it only uses NamedCatalogs eventually, and IProjectCatalogSnapshot.Project is nullable. With recent CPS fixes, IPropertyPageCatalog no long references any project snapshot, so if your code can create a private implementation of IProjectCatalogSnapshot, which removes Project snapshot from it (which is nullable in the contract), your model will not retain this large object. It may still retain stale catalogs, but it is a far less problem. This will only require a minor change to make it possible in 16.8

**Comment by drewnoakes** [comment]
@lifengl thanks for the analysis.

> although it captures IProjectCatalogSnapshot, it only uses NamedCatalogs

I took a look at this but unfortunately we do use `IProjectCatalogSnapshot.Project` as well as `NamedCatalogs`, here:

https://github.com/dotnet/project-system/blob/5a3fe3edc82a7ee5c64b044cd375782275cc9fe0/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.cs#L280

So we cannot apply an optimisation like the one you describe.

---

I think a simpler fix is to remove the attempt at optimising updates with no changes:

https://github.com/dotnet/project-system/blob/5a3fe3edc82a7ee5c64b044cd375782275cc9fe0/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs#L112-L123

Fixed in #6606.
