### ISSUE TITLE
Remove FullPath from source item evaluation rules for C#/VB projects

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#5837]
It is the single largest string in the item properties collection in project evaluation rule snapshots, and also prevents the immutable properties collection to be shared cross different items.

**Comment by drewnoakes** [comment]
Notes: use telemetry to identify properties which are unused across a variety of project types (e.g. F#).

**Comment by drewnoakes** [comment]
Sending back to triage as I mistook this as being related to the dependencies node. CPS wants to use this work in order to unlock perf gains soon.

**Comment by davkean** [comment]
I've found three items that use FullPath:

1) TreeItemOrderPropertyProvider (I don't know - maybe MakeRooted, or individual F# rules for None/Content/EmbeddedResource/Compile)
2) PotentialEditorConfigFilesDataSource (add PotentialEditorConfigFiles -> AdditionalDesignTimeBuildInput and remove this class and its base completely)
3) DesignTimeInputsDataSource (can be removed and just fallback to MakeRooted)

**Comment by drewnoakes** [comment]
`PotentialEditorConfigFiles` was removed in f48ac0d8155b2dfa09a26589306617eac3acd80a.

`DesignTimeInputsDataSource` is straightforward to migrate off `FullPath`.

That leaves `TreeItemOrderPropertyProvider`, which is a tricky one. There's not enough information on `IProjectTreeCustomizablePropertyContext3` to identify the item's path. Specifically this fails for linked items where the item path could be `../LinkedScript.fs`. We just see the `ItemName` of `LinkedScript.fs`.

Options that I can see are:

1. Introduce `IProjectTreeCustomizablePropertyContext4.ItemPath` in CPS. The challenge here is:
   - There are 31 instantiations of CPS's `ProjectTreeCustomizablePropertyContext`, and they'd all need to be reviewed in order to set a correct value.
   - What path is it? Project-relative seems sensible.
   - Does this property make sense for all item types?

2. Introduce new rules for F#'s `Compile`/`Content`/`EditorConfigFiles`/`EmbeddedResource`/`None` items, as suggested by @davkean.
   - It'd be good to avoid forking these rules just for F# if possible.

**Comment by davkean** [comment]
It was very deliberate that 1. wasn't done at time this was introduced, you'll want to sync with CPS.
