### ISSUE TITLE
ProjectItem.Remove() immediately after File.Delete() causes <Item Remove="" />

### ISSUE THREAD

**Issue by bricelam** [dotnet/project-system#5895]
We're seeing reports in https://github.com/dotnet/efcore/issues/18381 of what looks like a race condition. Our Remove-Migration PMC command calls File.Delete() on a few files then finds the EnvDTE.ProjectItem objects for those files and calls Remove(). (I know that's unnecessary on CPS-based csproj, but just do it always to handle legacy project systems too.) Many customers are seeing entries like the following in the csproj:
```xml
<ItemGroup>
  <Compile Remove="Migrations\20200220022002_InitialCreate.cs" />
  <Compile Remove="Migrations\20200220022002_InitialCreate.Designer.cs" />
</ItemGroup>
```
If I add a call to `Thread.Sleep()` just before calling ProjectItem.Remove(), the csproj doesn't contain the Remove entries (the expected behavior).

**Comment by davkean** [comment]
This will occur because we haven't seen the file watch notification. There's no way to force this without falling back to CPS APIs. We can look to see if we can wait for these notifications in Remove.

If you call ProjectItem.Delete this should not occur.

**Comment by bricelam** [comment]
Happy to work around it on our end; just wanted to touch base with you guys first.

**Comment by davkean** [comment]
@lifengl What's your thoughts on this? I can see that the same problem can occur with:

``` C#
ProjectItem.RemoveItem
IVsProject4.RemoveItem
IVsHierarchyDeleteHandler.DeleteItem(DELITEMOP_RemoveFromProject)
```

Should we wait for file system events to catch up before we actually remove?

**Comment by lifengl** [comment]
No, that will lead a performance hit, and also it is undefined when we receive file system event.  I think the extension code should call Item.Delete, instead of calling File.Delete + RemoveItem.  If the file needs to be deleted, it can call DeleteItem after that.

Of course, one option is Remove logic always check disk first, and work as Delete. That would fix it, but it would add more disk IO for a very special usage, so hard to justify with a single feedback.

Sent from my phone

On Feb 15, 2020, at 4:05 PM, David Kean <notifications@github.com> wrote:

﻿

@lifengl<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7C8785e6c5fdb4453152a908d7b273e67f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637174083158720116&sdata=J80vQGRojeo0a5zsMEDnd%2BQeEigoW5Z0nn7fpRZmfKI%3D&reserved=0> What's your thoughts on this? I can see that the same problem can occur with:

ProjectItem.RemoveItem
IVsProject4.RemoveItem
IVsHierarchyDeleteHandler.DeleteItem(DELITEMOP_RemoveFromProject)

Should we wait for file system events to catch up before we actually remove?

**Comment by jjmew** [comment]
Triage: closing based on Lifeng's comments
