### ISSUE TITLE
optimize the target framework list order

### ISSUE THREAD

**Issue by csqCreate** [dotnet/project-system#5942]
**Visual Studio Version**:16.4.5

**Expected Behavior**:

-------LTS------
.NET CORE 2.1
.NET CORE 3.1
------EOL------
.NET CORE 1.0
.NET CORE 1.1
.NET CORE 2.0
.NET CORE 2.2
.NET CORE 3.0

**Actual Behavior**:

.NET CORE 1.0
.NET CORE 1.1
.NET CORE 2.0
.NET CORE 2.1
.NET CORE 2.2
.NET CORE 3.0
.NET CORE 3.1

**Comment by jjmew** [comment]
@dsplaisted We will need the SDK to update their description name. Do you have a way to move this to your repo?

**Comment by Varorbc** [comment]
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props#L18-L25

https://dotnet.microsoft.com/download/dotnet-core
![image](https://user-images.githubusercontent.com/5714438/76082097-90d13280-5fe5-11ea-855b-a6175b07d11e.png)

can the list of supported target framework add the status and end of support date attributes as shown in the figure above, so that users can know how to select a target framework more clearly?

**Comment by dsplaisted** [comment]
@jjmew This is where we define the supported target frameworks: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props#L18-L25

Are you suggesting we update the display names?  Or add additional metadata?

If we just update the display names, then that wouldn't get localized.

**Comment by jjmew** [comment]
@dsplaisted  we will need additional metadata

**Comment by dsplaisted** [comment]
@jjmew Whenever you've defined the metadata that needs to be added, we can add it to the .props file.  Until then I don't think there's a reason to move this to the SDK repo, as it's not actionable yet.

**Comment by Varorbc** [comment]
The download page has also been revised

![IMG_20200915_063201](https://user-images.githubusercontent.com/5714438/93144841-883c8000-f71d-11ea-8b92-22ccb39f3dbd.jpg)
