### ISSUE TITLE
Design Time Builds failing if we have some derived properties in Implicit or leading imports

### ISSUE THREAD

**Issue by Anipik** [dotnet/project-system#5996]
In case of multple TargetFrameworks,  DesignTimeBuild uses  msbuild ```setproperty``` function to  set the TargetFramework property.  

So this updates a property if it exists, otherwise it searches for the first unconditioned PropertyGroup in the project file to add the property to. This is always going to be after any implicit imports as well as explicitly leading imports. This appears to be the long-standing behavior of SetProperty. Contrast that to SetGlobalProperty, which will treat the property as global.

Hence any property derived from targetFramework in implicit imports and leading imports will not be evaluated correctly.

There is a detail repro here https://github.com/dotnet/runtime/issues/33427#issuecomment-597634844

cc @ericstj 

similar issue https://github.com/OmniSharp/omnisharp-roslyn/issues/1738

**Comment by davkean** [comment]
This is an MSBuild issue, please open it against http://github.com/microsoft/msbuild. I'd move the issue but I can't across orgs.

**Comment by ViktorHofer** [comment]
@Anipik did you open an issue in msbuild as David suggested? Can't find one.

**Comment by Anipik** [comment]
no i missed his comment, i am  just doing it right now.

**Comment by Anipik** [comment]
https://github.com/microsoft/msbuild/issues/5319

**Comment by ericstj** [comment]
@davkean are you sure this is an MSBuild issue?  I believe MSBuild is behaving correctly.  The problem is that the project system ends up setting a local property rather than a global property: https://github.com/dotnet/project-system/blob/600486bb5da07a40b9e3bd08699d758be37c1f91/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs#L41-L59

This results in an inconsistency between what the SDK does in an actual build (global property) vs what the project system does in the design time build (local property).
