### ISSUE TITLE
[Regression] "Executable" and "Project" are showing up as debug targets

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6225]
**Visual Studio Version**:
16.7

**Summary**:
Two new debug types have shown up for .NET Core projects (legacy is not affected)

**Steps to Reproduce**:

1.  Create new project

2. Drop down the Debug launch:
![image](https://user-images.githubusercontent.com/1103906/82663671-78cb8f80-9c73-11ea-8798-f63b6d4988bd.png)

**Expected Behavior**:

No "Executable" or "Project".

Is this a regression introduced by the Nexus targets?

**Comment by davkean** [comment]
@tmeschter ^ Was this introduced by your changes?

**Comment by davkean** [comment]
I think maybe this regressed it: https://github.com/dotnet/project-system/pull/6194/files. CPS is definitively return these two extra options.

**Comment by tmeschter** [comment]
CPS assumes each "debugger" `Rule` (with `PageTemplate="debugger"`) should be shown in this drop down, _and_ expects that each provides the GUID and ID of the related VS debugger command in their metadata. `Rule`s which do not are associated with default GUIDs and IDs.

Our debugger rules don't provide the GUID and IDs because they provide a debug target (e.g., Executable, Project, IIS, IISExpress, etc.) instead. For the purposes of the debugger they aren't directly "startable" on their own--they need to be associated with a launch profile that provides all the relevant settings. So we don't want them to appear on this menu.

I can't simply update CPS to filter out "debugger" pages that lack the GUID and ID, because in theory other pages are usable by the debugger with the default values and we want to keep showing those.

Instead I'll update the property page code in CPS to look for a new kind of page (maybe "targetBasedDebugger") and update the appropriate .xaml files in our repo to use that new page template.
