### ISSUE TITLE
Undoing project changes causes the editor to be out of sync forever

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6279]
**Visual Studio Version**:

**Summary**:

**Steps to Reproduce**:

1.  Create two projects; 1 and 2

2.  Open project file editor on 2

3. Drag 1 onto 2 to add a project reference

4. In the editor, press CTRL+Z to undo the change

5. Drag 1 onto 2 to add a project reference

**Expected Behavior**:
For the reference to be reflected in the editor

**Actual Behavior**:
The reference is not reflected in the editor

**User Impact**:

**Comment by davkean** [comment]
Why does dragging the reference get added to the undo buffer of the editor?

**Comment by davidwengier** [comment]
This is admittedly confusing, but it's not a bug. By not saving after step 4 the undo doesn't actually apply to the underlying project, so step 5 doesn't cause a change, and the editor doesn't have any need to respond to anything. @davkean Did you do anything else that made you think the editor was "out of sync forever" because I'm not seeing it out of sync at all. If I swap step 5 for a different change, like excluding a class file, the editor responds as expected.

Having said all of that, I don't think the project change being on the undo stack makes sense, and that is worth fixing in cases where there aren't any editor changes.

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/256296

**Comment by davidwengier** [comment]
Internal PR has been completed. Project changes are no longer in the undo buffer, so this scenario makes a lot more sense now.
