### ISSUE TITLE
Project always rebuilt: Improper up-to-date check with conditional items

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6321]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/947356/project-always-rebuilt-improper-up-to-date-check-w.html). Please vote and comment there to make sure your voice is heard._

---
1. Create a new project (I used C# UWP app, this bug may be in other project types).
2. Add a content file (for example, `dummy.xml`)
3. Change the file to "Copy if newer"
4. Save the solution
5. Open the project file in a text editor (e.g. by unloading the project and selecting Edit from the context menu)
6. Find the content file and add a condition that always fails.  For example, change this:
    
```
    <Content Include="dummy.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

to this:
    
```
    <Content Include="dummy.xml" Condition="'Foo' == 'Bar'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```
7. Reload the project
8. Build
9. Build again

(The attached project contains this repro).

**Expected:**
In step 9, the project should not be rebuilt since everything is up to date.

**Actual:**
The project is rebuilt.  In the output window we see the following trace:
>1>Project 'VSBug7' is not up to date. Copy to output file 'c:\prj\VSBug7\bin\x86\Debug\dummy.xml' missing from output location.
This is incorrect, since `dummy.xml` was excluded due to the condition.

**Additional notes:**
Although the repro steps in this bug use a condition that always fails, this is only for illustration purposes.  I found this bug with a more sane condition (`Condition="'$(Platform)' == 'x64'"`) which is sometimes true and sometimes false.  The point is that when the condition is false the dependency is not properly ignored in the up-to-date check.

---
#### Oz Solomon [MSFT] on 3/12/2020, 07:34 AM: 

<p>I'll also add that this problem occurs if the condition is placed on the `ItemGroup` rather than the item.</p>

#### Visual Studio Feedback System on 3/12/2020, 07:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 3/17/2020, 01:03 AM: 

<p>Thank you for your feedback and taking the time to reach out to us. I can reproduced this issue through your shared steps and this issue has been escalated for further investigation, if there is any process, I will inform you immediately.</p>

#### Maik Gerth on 6/18/2020, 03:36 AM: 

I have the same problem when we copy .dlls conditionally based on the Platform in C#, example from .csproj:<br><br>    &lt;Content Include=&quot;..\DLL\testx32dbg.dll&quot; Condition=&quot; &#39;$(Configuration)|$(Platform)&#39; == &#39;Debug|AnyCPU&#39; &quot;&gt;<br>      &lt;Link&gt;testx32dbg.dll&lt;/Link&gt;<br>      &lt;CopyToOutputDirectory&gt;PreserveNewest&lt;/CopyToOutputDirectory&gt;<br>    &lt;/Content&gt;<br>    &lt;Content Include=&quot;..\DLL\testx64.dll&quot; Condition=&quot; &#39;$(Configuration)|$(Platform)&#39; == &#39;Release|x64&#39; &quot;&gt;<br>      &lt;Link&gt;testx64.dll&lt;/Link&gt;<br>      &lt;CopyToOutputDirectory&gt;PreserveNewest&lt;/CopyToOutputDirectory&gt;<br>    &lt;/Content&gt;<br><br><br>Then Visual Studio Diagnostic Build will always trigger a rebuild, because it thinks that one of the .dlls (from the irrelvant Platform for the current build which it therefore did not copy) is missing e.g. in 32bit Debug  it would show<br><br>Project &#39;MyProject&#39; is not up to date. Copy to output file &#39;...Debug32\textx64.dll&#39; missing from output location.

---
### Original Solutions
(no solutions)

**Comment by ocallesp** [comment]
If I change   `==`   to    `!=`  in the Condition Fast up-to-date works. 
@rainersigwald What is the correct logic ? it seems inverted. 

    <Content Include="dummy.xml" Condition="'Foo' == 'Bar'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

**Comment by ocallesp** [comment]
This doesn't repro in DotNet Core.
It seems that when Condition is False, FUTD stills take dummy.xml as an input.

Doing a little debugging I see that Design-time Build 
**when Condition is True**, the item dummy.xml has the metadata `CopyToOutputDirectory=PreserveNewest`
![image](https://user-images.githubusercontent.com/510598/87344118-b970b800-c502-11ea-86cb-81e746d03885.png)

BUT

**when Condition is False**, dummy.xml has no metadata. I was expecting to see `CopyToOutputDirectory=Never`, so that Fast up-to-date can ignore that input.
![image](https://user-images.githubusercontent.com/510598/87343898-6bf44b00-c502-11ea-96dd-54e53c0b6f93.png)
 
I still need to check the source code of the **Fast up-to-date in the old project**.
How FUTD handles when the item has no metadata, does it treat the item as CopyToOutputDirectory=Never ? In case metadata is missing, the issue might be in the Design-time build. 

In a ConsoleApp, I see the  dummy.xml does not appear in the list of items (Content) when Condition is False.
![image](https://user-images.githubusercontent.com/510598/87346056-e1154f80-c505-11ea-95aa-0d5e9cd8bc47.png)

**Comment by jjmew** [comment]
This doesn't repro in CPS.

**Comment by mgexo** [comment]
When will this bugfix or the "new Project System" with the fix be released? 
Migration to VS2019 from earlier Visual Studio is really nerve wrecking with this bug
https://developercommunity.visualstudio.com/content/problem/947356/project-always-rebuilt-improper-up-to-date-check-w.html

**Comment by drewnoakes** [comment]
@mgexo there are two main C# project systems that ship with VS.

1. The "new project system", which handles SDK-style projects and which receives the greatest amount of development.
2. The "legacy project system", which handles traditional .csproj files, which is stable but lacks modern features.

So to answer your question, the new project system was available back in July when this issue was closed.

**Comment by mgexo** [comment]
> @mgexo there are two main C# project systems that ship with VS.
> 
> 1. The "new project system", which handles SDK-style projects and which receives the greatest amount of development.
> 2. The "legacy project system", which handles traditional .csproj files, which is stable but lacks modern features.
> 
> So to answer your question, the new project system was available back in July when this issue was closed.

For all readers who wonder what this is about, see https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md
