### ISSUE TITLE
Tag the commits that were inserted into a particular VS version

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#6453]
Use https://github.com/dotnet/roslyn-tools/tree/master/src/CreateTagsForVSRelease

**Comment by MiYanni** [comment]
We would not use a roslyn-tools for this action. There is likely a way to do this via the automatic insertion process, to be done in: https://github.com/dotnet/project-system/issues/7911

**Comment by MiYanni** [comment]
The original solution in https://github.com/dotnet/project-system/pull/8517 did not work. The multi-repo triggering mechanism requires that the repo containing the YAML file **also** be within the same AzDO org. This was not mentioned in the documentation linked within the PR. To make a solution for this using the same concept, the current idea is to use an internal mirror of this repo. There will need to be changes to the `tagger.yml` to account for this. That PR can resolve this issue.

**Comment by kvenkatrajan** [comment]
@MiYanni, can this be closed as : Closed not planned at the moment.

**Comment by MiYanni** [comment]
@kvenkatrajan The only reason this got put on-hold is a red-tape issue which I won't go into details here. However, I can workaround that in the near term (since the problem wasn't resolved yet). I've added you to an email thread related to it.

**Comment by MiYanni** [comment]
This was *nearly* completed prior to my team move. Everything is in-place for this to work but there were some tweaks needed:
- The [tagger pipeline](https://github.com/dotnet/project-system/blob/main/eng/pipelines/tagger.yml) needs to be modified to run properly internally. This pipeline needs to run based off of our `-Trusted` repo (`main` branch since that is cloned). It cannot be connected to the GitHub repo as the trigger will not function properly.
- The scripts related to the process need to explicitly target the public GitHub repo. Right now, they target the repo they run on, which would mean that it would create tags in `-Trusted` (which we don't want).
- After the automatic tagging is set up and working, follow the information here to tag all previous releases: https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/34672/Release-Tagging-(script)

**Comment by smitpatel** [comment]
Is idea to create tag for VS releases or every VS insertion? Tagger.yaml is working to tag every insertion.

**Comment by MiYanni** [comment]
> Is idea to create tag for VS releases or every VS insertion? Tagger.yaml is working to tag every insertion.

@smitpatel The tagger pipeline has a specific trigger mechanism that only activates when VS creates a tag following a certain format. It combines these two features:
- Trigger based on tag: https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#tags
- Multi-repository triggers: https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#triggers

**Comment by smitpatel** [comment]
We created pipeline which is running perfectly now. For 15.x/16.x we tagged very last release. Future patches are covered by automated pipeline itself.
