### ISSUE TITLE
Generated code under obj folder causes obj folder to show in solution explorer

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/project-system#6634]
**Visual Studio Version**:
16.8.0 Preview 3.0

**Summary**:
I'm using an MSBuild task (in a nuget package) to generate code. These C# code files are generated based on other files in the project, and placed under the obj folder. test.foo would generate obj/debug/netcoreapp3.1/test.foo.g.cs. These generated files are declaratively included in the compilation, using a transformation based on input foo file. Additionally, these generated files are hidden (Visible=false MSBuild metadata). The generated code files themselves *are* hidden, unfortunately the folder that they sit in (obj/debug/netcoreapp3.1) is not hidden and appears (empty) in the solution explorer.

I'm hoping there is some mechanism I can use to also hide the folders in the solution explorer. If not, I'd like to report this as a bug, because it results in a bad user experience.

I've tried varieties of:
```
<Folder Include="obj/**/*"><Visible>false</Visible></Folder>
```
But, nothing I tried caused the obj folder to be hidden.

**Steps to Reproduce**:

1. clone https://github.com/MarkPflug/CodeGenRepro, which contains a minimal repro.

2. Build the project.

3. Notice that the `obj/Debug/netcoreapp3.1` folder appears in the Solution Explorer.

4. Delete `obj` from the solution explorer.

5. Notice how the obj folder doesn't delete, and the project system edits the .csproj file to remove the test.foo.g.cs file.

**Expected Behavior**:
The obj folders don't appear in the solution explorer.

**Actual Behavior**:
The obj folders appear in the solution explorer.

**User Impact**:
It's an annoyance, and confusing. Users delete the folder but it will immediately reappear when the build task runs to regenerate the code.

**Comment by tmeschter** [comment]
@MarkPflug I took a look at your minimal repro (thanks for that!) and I have a solution for you.

Here's a snippet from your original code:
``` XML
<ItemGroup>
  <Foo Include="**/*.foo" />

  <Compile Include="@(Foo->'%(GeneratedCode)')">
    <Visible>false</Visible>
  </Compile>
</ItemGroup>

<Target Name="Gen" BeforeTargets="CoreCompile">
  <Copy SourceFiles="@(Foo)" DestinationFiles="@(Foo->'%(GeneratedCode)')" />
</Target>
```

You're statically declaring a `<Compile>` item in the item group even though the associated files are dynamically generated. I think the way the project system handles these "static" items is causing us to show the `obj\Debug\netcoreapp3.1` directory even though you've marked the item with `<Visible>false</Visible>`.

Display issues aside, a better practice is to dynamically create items for dynamically-generated files. Replace the snippet above with the following:
``` XML
<ItemGroup>
  <Foo Include="**/*.foo" />
</ItemGroup>
	
<Target Name="Gen" BeforeTargets="CoreCompile">
  <Copy SourceFiles="@(Foo)" DestinationFiles="@(Foo->'%(GeneratedCode)')">
    <Output TaskParameter="CopiedFiles" ItemName="Compile" />
  </Copy>
</Target>
```

The `Copy` task has an output parameter name "CopiedFiles" that includes the paths to all the files it copied. The `<Output TaskParameter="CopiedFiles" ItemName="Compile" />` line tells MSBuild to take that output parameter and create `<Compile>` items for each of those paths. Since those items are created dynamically, VS doesn't try to show them in Solution Explorer and avoids displaying an empty `obj\Debug\netcoreapp3.1`.

**Comment by MarkPflug** [comment]
Thanks for taking a look. While the approach you suggest removes the obj folder from the Solution Explorer, it also makes the generated code no longer visible in Intellisense. Being visible to Intellisense is critical for my use-case. I'd tried doing the same thing with a Target/ItemGroup/Compile, which has the same result: no Intellisense.

Maybe I need to explore doing this with a SourceGenerator instead. It's frustrating, because I'm 99% there already, but the obj folder issue is unacceptable.

**Comment by MarkPflug** [comment]
And the fix for that, [as I've been told before](https://github.com/dotnet/project-system/issues/2853), is to add a `PropertyPageSchema` for my "foo" file type. That fixes the intellisense issue when adding the Compile items dynamically. I'm not sure why I forgot about that. Thanks again.

**Comment by tmeschter** [comment]
@MarkPflug I tried out the solution I proposed and it worked for me--it may be that you needed to reload the project after making that change before the file was picked up properly. A similar approach is used for a couple of other files that the SDK generates under the obj directory, such as *AssemblyInfo.cs. Regardless, I'm glad you were able to come to some resolution.

**Comment by MarkPflug** [comment]
@tmeschter I tried it again. You're right. It does work with Intellisense. Not sure why it didn't yesterday. Anyway, thanks a bunch for taking the time to look at this. Much appreciated!
