### ISSUE TITLE
Extend fast up-to-date check telemetry

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6776]
Currently we only capture whether VS's fast up-to-date check succeeded or failed, and if failed then what the reason was (a simple string).

We should extend this to include:

- How much time was spent on the up-to-date check
- How many files were sniffed on disk
- Potentially other items (please comment)

Ideally we would also report on cases where the check decided the project was not up to date so scheduled a build, but MSBuild then concluded the project actually was up to date. @rainersigwald do you know of a way we could capture this information?

**Comment by rainersigwald** [comment]
MSBuild doesn't really have a concept of "up to date" at the project level. We could potentially report back that "all of the targets that defined inputs/outputs were skipped", which is about as close as we can get--but many targets intentionally don't define incremental behavior because they expect to be rerun every time (for example ResolveAssemblyReferences has to run to figure out if the output reference closure has changed, and copy-to-bin targets rely on the copy task for incremental).

**Comment by drewnoakes** [comment]
Thanks @rainersigwald.

I've added the other telemetry in https://github.com/dotnet/project-system/pull/6778.
