### ISSUE TITLE
Clearing a project property text box is not possible

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6899]
(Moved from #6627)

Repro steps:

1. Open the Project Properties UI
2. Clear the text in the _Default namespace_ text box
3. Press <kbd>Tab</kbd>
4. Notice the previous value is restored

This happens on most text boxes. The reason is as yet unknown.

It doesn't seem to happen on _Assembly name_, which seems to have a sensible default provided by the SDK.

**Comment by drewnoakes** [comment]
@tmeschter I believe this is behaviour from the server. The client is calling `SetUnevaluatedUIPropertyValue` and passing an empty string, then re-querying the property's value via the Project Query API and receiving the original value back.

**Comment by tmeschter** [comment]
Interesting--this is intentional behavior on the part of CPS. It considers the value of the "RootNamespace" property to be the empty string **within the context of the project file**. Since we're attempting to set the value within the project file to the empty string, and the property already has that value within the project file, CPS considers it a no-op and returns before making any modifications.

I'm not quite sure why CPS considers the value within the context of the project file to be the empty string--the default value comes from a .props file imported at the beginning of the project file.

**Comment by tmeschter** [comment]
I see what's happening. CPS is looking for a definition of "RootNamespace" specifically within the project file. When it doesn't find one, it returns `null` for that definition. The subsequent code does not make a distinction between "the property wasn't found in this context" and "the property was found but its value is null or the empty string". In both cases CPS treats the effective value of the property as the empty string, and since the user is trying to set the property to the empty string it decides there is nothing to do.

I believe this is a bug. If the property _were_ defined in the project file, CPS would quite happily set it to the empty string.

**Comment by tmeschter** [comment]
@drewnoakes Can you think of any properties where you would really want to set it to the empty string?

**Comment by drewnoakes** [comment]
> @drewnoakes Can you think of any properties where you would really want to set it to the empty string?

Perhaps NoWarn, the documentation file path, or some of the packaging properties such as description or license.

**Comment by drewnoakes** [comment]
I'm wondering if there's a way to clear out the value for a property whose default value is defined in a .targets file. An empty property element is equivalent to no property at all, from my understanding of MSBuild.

**Comment by tmeschter** [comment]
> I'm wondering if there's a way to clear out the value for a property whose default value is defined in a .targets file. An empty property element is equivalent to no property at all, from my understanding of MSBuild.

Yeah, I don't think there's a good way to do that. On the other hand, if the empty string is a reasonable value for that property then it should probably **be** the default.

However, this is a problem you would run into even when modifying the project file by hand--I don't think we need to worry about solving it within the property pages.

**Comment by davkean** [comment]
Overriding a value such as via item definition by setting it to empty value at the context, is a pretty normal thing that CPS does. Just clear any default metadata in the properties window.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by tmeschter** [comment]
Fixed by https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/302251.

**Comment by drewnoakes** [comment]
CPS PR merged. Verified fix during testing:

![image](https://user-images.githubusercontent.com/350947/107163848-f4d35680-69ff-11eb-94a4-38f812519377.png)

**Comment by drewnoakes** [comment]
Tested this again with Package ID and it reverts the value.

Here I'm clearing the value with <kbd>Delete</kbd> then committing the value with <kbd>Enter</kbd>:

![clear-package-id-reverted](https://user-images.githubusercontent.com/350947/107165726-ef7a0a00-6a07-11eb-9fcc-3675c69e2de1.gif)

**Comment by tmeschter** [comment]
OK, I'll take a look at those specific properties so that we're sure we know what's going on.

If the default _is_ coming from a .targets file, I don't think we need to do anything--the SDK is effectively enforcing that the property can't be the empty string. We might think about updating the description to explain that limitation.

**Comment by tmeschter** [comment]
@drewnoakes As suspected, `PackageId`, `Company`, and `Authors` are all given defaults values in the .targets files so there is no way to "unset" them. I propose we close this issue. Any objections?

**Comment by davkean** [comment]
This should result in an empty property in project file that overrides SDK
________________________________

**Comment by davkean** [comment]
Ah, I see the defaults are in wrong place.
________________________________

**Comment by tmeschter** [comment]
Closing this issue. Fundamentally this is an SDK issue; we will wait for customer feedback to see if there is anything more to do.
