### ISSUE TITLE
Modifying conditional compilation symbols produces unexpected evaluated values. (2)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6931]
While testing #6899 I noticed the following strange behaviour.

1. Create a new .NET Core Console App
2. Open new Project Properties UI
3. Modify _Conditional compilation symbols_ by appending a `2` so it reads `$(DefineConstants)TRACE2`
4. Press <kbd>Enter</kbd> to commit the value
5. Notice the evaluated values look wrong

Before

![image](https://user-images.githubusercontent.com/350947/107163917-614e5580-6a00-11eb-9b1a-2d9cce698e5f.png)

After

![image](https://user-images.githubusercontent.com/350947/107163924-690dfa00-6a00-11eb-9095-4b6a78dec801.png)

**Comment by drewnoakes** [comment]
@tmeschter I've tentatively assigned you as I believe this is a back end issue.

In the legacy pages, there was a more complex UI around this, with checkboxes for TRACE and DEBUG. Nowadays those check boxes don't actually work correctly, but I wonder if they were added due to some complexity in how this property's value is handled during evaluation that we're no bumping into. It's possible those check boxes were just a convenience though.

**Comment by drewnoakes** [comment]
Similar behaviour for _Treat specific warnings as errors_:

Before

![image](https://user-images.githubusercontent.com/350947/107165088-e38d4880-6a05-11eb-9cfc-9d2037d53891.png)

After

![image](https://user-images.githubusercontent.com/350947/107165103-f0aa3780-6a05-11eb-9468-82fdd4739452.png)

The problem occurs when a property is defined in terms of itself. That application occurs both in the project file and externally. This leads to surprising behaviour.

We could force the user to edit the evaluated value for these properties. Currently, whether a property shows unevaluated values is determined by its editor (i.e. the default `StringProperty` editor always shows the unevaluated value). We could use a different editor for these properties to force the UI to work with evaluated values only, or add metadata for the existing properties to modify the behaviour of existing editors. It's not clear to me what then happens if you attempt to use an MSBuild expression in that value. I'm guessing the expression is evaluated when the property is updated, and the evaluated value is baked into the project file at that time. This is probably not a great experience either.

Other ideas?

**Comment by tmeschter** [comment]
That's... interesting.

I'm guessing the default is in a .props file, defined like so:

``` XML
<WarningsAsErrors>$(WarningsAsErrors);NU1605</WarningsAsErrors>
```

Which evaluates to ";NU1605" at that point in the MSBuild evaluation pass.

And then we write this to the project file:

``` XML
<WarningsAsErrors>$(WarningsAsErrors);NU1605Update</WarningsAsErrors>
```

Which is evaluated in terms of the previous value of `WarningsAsErrors` and becomes ";NU1605;NU1605Updated".

Fundamentally we're running up against the limitations imposed by treating what is logically a set of items (the warning numbers) as a single property. I'd say the system is working as _designed_ though probably not as _expected_, and this is a good example of the value in showing both the unevaluated and evaluated values. :-)

The real implication is that there isn't a good way to selectively remove the "NU1605" warning from that list without also removing every other value that may be in that list. The best you can do is replace it entirely. Unless we can find a way to address that problem I would leave the existing experience as-is, since it is accurate.

Maybe the right answer is to get NuGet to treat NU1605 as an error when it is produced rather than promoting it after the fact?

**Comment by drewnoakes** [comment]
I agree with your assessment wrt `WarningsAsErrors`.

The situation appears slightly different in the case of compilation symbols. The value is being modified both in props and targets. I wonder if the number of symbols here is going to explode with the `NET_4_5_OR_GREATER`-style symbols.

**Comment by drewnoakes** [comment]
Any fix for this should also cover #7050.

**Comment by tmeschter** [comment]
The more I think about this, the trickier it is.

Fundamentally, the issue is that the recursive definition of a property in a .props file is _not_ the same definition you want in your project file. E.g., if the .props file has `<ABC>$(ABC);DEF</ABC>` you do not want to have `<ABC>$(ABC);DEF</ABC>` in your project file as well--that would evaluate to `;DEF;DEF`. More specifically, you do not want `DEF` to appear anywhere in the definition in your project file, because that will cause it to be repeated. So the issue is not with the recursive reference `$(ABC)`, but with all the other parts of the definition.

This ends up being a problem because the previous definition becomes the starting point we give the user when they want to edit the value, which then goes into the project file.

**Comment by tmeschter** [comment]
We show the unevaluated value largely so the user can understand how the property is currently defined. We also use it as the basis for edits that will go into the project file, and (as we see in this issue) the existing definition is not necessarily a good candidate for that.

I think that brings us back to making a distinction between "this is the value in your project file" and "this is the default you get if it is not defined in your project file". That's not something we can currently express, and there are other issues we need to address for Dev17 that are more important. I'm going to remove the `Must-Have` label for now.

**Comment by drewnoakes** [comment]
Sending this back to triage to decide on priority for this work item. The property is pretty broken as it stands so we should probably do something about it in 17.0.

**Comment by jjmew** [comment]
This is something that we should take a look post feature complete

**Comment by tmeschter** [comment]
Status of this: there are ways for us to determine if an unevaluated value is from the project file, or is coming from some imported .props/.targets (in which case we can consider it a default). However, there is currently no way for us to express this in the Project Query API.

Future work may include:
- Adding a property to the Project Query API indicating if a value is a default value or not
- Updating the back end to populate that property
- Update the UI to show default values as watermark text, rather than editable text.
