### ISSUE TITLE
Identify pages and properties missing in the WPF experience (1+?)

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6938]
We need to identify the WPF-specific pages and properties missing from the new project property pages experience and file issues to address those.

**Comment by paul1956** [comment]
UseWindowsForms and UseWPF when you want to set both.

**Comment by tmeschter** [comment]
@paul1956 Are you requesting that we add controls for these? This work item is strictly about controls that exist on the current property pages but are missing from the new property pages.

**Comment by paul1956** [comment]
I don't use WPF but added these here because I I had the same request for WinForms. The package split of what is included between Framework and Core has changed. To get everything you got in Framework you need to set both options, most applications don't need everything or even anything from the other so it seems reasonable to include a control. Specifically Windows.Media is only in WPF but Windows.Media.Color is used on WinForm Applications and there is no way to set it. I don't have an example of something in WinForms that a WPF developer might want, so maybe its not necessary here.

**Comment by drewnoakes** [comment]
C# & VB

**Comment by drewnoakes** [comment]
> UseWindowsForms and UseWPF when you want to set both.

These have both been added to the new Project Properties UI.

I've reviewed the legacy property pages for C# legacy and SDK projects, and see no WPF-specific properties to port.

For VB projects, I've filed #7379 to track missing features.

Closing this.
