### ISSUE TITLE
Support filtering up-to-date inputs/outputs via metadata using global properties

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7290]
We have a use case for VS to filter the set of up-to-date check inputs/outputs to use for different kinds of builds.

The mechanism here will be:
- A global property will be provided to the up-to-date check:
   ```xml
   <FastUpToDateCheckIgnoresKinds>foo;bar</FastUpToDateCheckIgnoresKinds>
   ```
- Items such as `UpToDateCheckInput`, `UpToDateCheckOutput` and `UpToDateCheckBuilt` will have an optional `Kind` metadata entry that labels it as a candidate for exclusion via the above global property
   ```xml
   <UpToDateCheckOutput Kind="foo">somefile.dll</UpToDateCheckOutput>
   ```

CPS PR https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/323751 adds a new `IBuildUpToDateCheckProvider2` interface via which the up-to-date check may receive the set of global properties.

- [x] Wait for `IBuildUpToDateCheckProvider2` to be published in a new CPS package [here](https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vs-impl%40Local&view=versions&package=Microsoft.VisualStudio.ProjectSystem&version=17.0.596-pre&protocolType=NuGet) (PR https://github.com/dotnet/project-system/pull/7294)
- [x] Change our check to implement this new interface
  - [x] Update our rules to bring in `Kind` metadata for these items
  - [x] Filter items as appropriate
  - [x] Unit tests
- [x] Update our documentation

cc @mavasani

**Comment by drewnoakes** [comment]
This has been completed.

**Comment by bwvick** [comment]
I am trying to take advantage of this setting.  I have the following settings in my .vbproj file:
  <ItemGroup>
  <UpToDateCheckInput Include="VersionAutoIncrement.vb" Kind="UpdateVersion" />
  <UpToDateCheckOutput Include="VersionAutoIncrement.vb" Kind="UpdateVersion" />
  </ItemGroup>

  <PropertyGroup>
  <FastUpToDateCheckIgnoresKinds>UpdateVersion</FastUpToDateCheckIgnoresKinds>
  </PropertyGroup>

VersionAutoIncrement.vb is a generated file using Text Templating.  Even after these settings I am getting the following message when building.  And the project rebuilds due to this file changing.

FastUpToDate: Input 'C:\Users\brad\source\repos\EdasConfig\EDASHelper\VersionAutoIncrement.vb' (1/18/2022 12:20:31 PM) has been modified since the last up-to-date check (1/18/2022 12:18:50 PM), not up to date. (EDASHelper)

I am using VS 2022 Version 17.0.5

**Comment by drewnoakes** [comment]
@bwvick in your case those files are likely also `Compile` items, which cannot be excluded using this mechanism.

It looks like you are trying to generate code during build. This repo contains an example of one way to achieve that without breaking incremental build:

https://github.com/drewnoakes/generate-code-sample

**Comment by drewnoakes** [comment]
Are you using SDK-style projects? If so you can use MSBuild properties to define the version at build time.

This Stack Overflow post might help:

https://stackoverflow.com/a/58631756/24874
