### ISSUE TITLE
"Working directory" does not have a browse button

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7331]
The "Working directory" property in the Launch Profiles should have a browse button, but does not:

![image](https://user-images.githubusercontent.com/10506730/122604891-85afe380-d02b-11eb-994f-eae50bfb458a.png)

**Comment by drewnoakes** [comment]
It turns out that `folder` is a common alternative to `directory` for a `StringProperty`'s `SubType`. In that sense this is a more general bug in the system, rather that with this property in particular, as it is likely to trip up others as they bring their existing rule files to the new Project Property / Launch Profiles system. Bumping to must-have and submitting a fix.
