### ISSUE TITLE
New Property Pages: Unable to switch from .NET Framework to .NET Core/Standard

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7367]
In testing adding "Prefer 32-bit" to the property pages, I was testing the visibility conditions related to it. One of the conditions is that it must be .NET Framework. When making [this GIF](https://github.com/dotnet/project-system/pull/7362#issuecomment-868137005), I encountered an issue where I couldn't switch from .NET Framework to .NET Core. I created a project (.NET 6.0) and then manually changed the it to .NET Framework. Then, I tried to use the properties pages to change it to .NET Core and it just wouldn't work.

I'll put the GIF here directly too:
![123356816-3f6fee00-d51d-11eb-945b-310c184c1ffe](https://user-images.githubusercontent.com/17788297/123707031-f15d3200-d81d-11eb-822a-add820e740ea.gif)

**Comment by tmeschter** [comment]
We don't support moving between .NET "families" (e.g., Framework, Core, and Standard) from the property pages. There are lots of issues with doing so, and we don't want to encourage it. We expect that if you're comfortable making that migration you're comfortable editing the project file directly.

The real issue here is that we aren't filtering the versions in the list to only those within the current "family".
