### ISSUE TITLE
Intellisense ready state might be declared too earlier in warm load (when DT cache is ready.)

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#7468]
The intellisense stage almost finished immediately after loading the solution in some warm loading time, after that, I saw nuget restore messages in the output window (although mostly they didn’t do anything, but sometime it might have pending work.)

I think the problem happens because the NuGet restore dataflow endpoints is registered too late.  CPS calls all background works are done, when all registered dataflow points are finished. If one is registered after that, it will push the project to the processing state again, but the solution intellisense ready state only count the first time when a project indicates it’s ready.

To ensure that, we need to satisfy one condition below:
•	A critical dataflow affecting the intellisense stage must be registered before solution load is completed
•	If we need run background initialization code to initialize any critical dataflow a part of intellisense stage after solution load is completed (which may make sense, because we do want to maintain the initial loading time short). This background initialization task must be registered to the operation progress itself, as an umbrella task to cover the other registration work.  Generally, we prefer the 2nd solution, so we load less code during modal phase of the solution loading.)

I wonder that we don’t cover the NuGet restore part in this way. (The language service part was covered by the first condition, so I don’t think this too early happens in a cold load/DT cache not ready state .

**Comment by drewnoakes** [comment]
Also reported in AB#1337213.

**Comment by drewnoakes** [comment]
I believe this is fixed in #7569.

---

### Some notes

The goal is to have operation progress complete _after_ package restore completes.

We attempt to do this currently, however there is a race condition.

During the initialization of `PackageRestoreProgressTrackerInstance` we register our data source with `IDataProgressTrackerService`. This allows CPS to identify when the data source is up-to-date with the project, signifying everything is in sync. However, it's possible that operation progress completes before we are able to register our data source, resulting in this bug.

Here are the relevant steps today:

- We have a `ConfiguredProjectImplicitActivationTracking` class, which is a `IProjectDynamicLoadComponent`
- CPS activates that component, which creates and initializes a `ConfiguredProjectImplicitActivationTrackingInstance`
- During initialization, that instance subscribes to project capabilities and the active configuration group
- When it receives data it determines a set of `IImplicitlyActiveConfigurationComponent`s to activate
- Our `PackageRestoreProgressTracker` is one such `IImplicitlyActiveConfigurationComponent`, and when activated it creates and initializes an instance of `PackageRestoreProgressTrackerInstance`
- That `PackageRestoreProgressTrackerInstance` is an `IJoinableProjectValueDataSource` and during initialization registers itself via `IDataProgressTrackerService.RegisterOutputDataSource`, which lets it contribute to operation progress

If all of that completes before operation progress, things work correctly. If not, they don't. That's the race. We need a way to guarantee operation progress waits for all of the above.

---

### About the fix

I went through several iterations of this before coming up with the fix in #7569, which was by far the simplest and I believe the most robust.

It creates a new operation progress registration for our `ConfiguredProjectImplicitActivationTracking` class, to cover the window of time between when we initialize that tracker (which creates a dataflow internally) and when its components are activated in response to that dataflow pumping. Those components then create their own operation progress registrations, ensuring there is no window of time during which we don't advertise that something is ongoing, until restore completes.
