### ISSUE TITLE
Proposal: Always add simple timing to any build output

### ISSUE THREAD

**Issue by xoofx** [dotnet/project-system#7802]
Hey,
Whether I make no changes, or change one script in a project, or make a bunch of changes, I'm missing one key information in the build result metrics which is about **"how much time did it take?"** instead of only _"number of projects succeeded/failed/up-to-date/skipped"_:

```
Build started...
========== Build: 0 succeeded, 0 failed, 30 up-to-date, 0 skipped ==========
```

One possibility is to modify the msbuild verbosity output to normal, but it is flooding the verbosity of the log and it doesn't work in all cases (no changes).

So could we append something simple like `(elapsed: 100ms)` or similar?

```
Build started...
========== Build (elapsed: 100ms): 0 succeeded, 0 failed, 30 up-to-date, 0 skipped ==========
```

I can make a PR to this repo, but I failed to find the string formatting for this log, and I suspect that part of it could be also on msbuild side depending on the kind of update?

**Comment by drewnoakes** [comment]
Hi Alexandre,

I like this idea a lot.

The code for that particular message is internal to VS rather than in this repo, as a build can span multiple types of projects.

Personally I use this extension to log build info in the output window. It also colourises output messages which can make skimming through logs much easier:

https://marketplace.visualstudio.com/items?itemName=MikeWard-AnnArbor.VSColorOutput64

Once installed, you have to use _Tools | Options | VSColorOutput_ in order enable build duration logging.

Would you mind filing a feature request using _Help | Send Feedback | Suggest a Feature_? Because the work would be done outside GitHub, a feedback ticket is the best way to route the request to the right VS team. If you link a ticket here I will ensure it is routed appropriately and champion it internally.

Thanks for taking the time to share this proposal.

**Comment by xoofx** [comment]
> Would you mind filing a feature request using Help | Send Feedback | Suggest a Feature? Because the work would be done outside GitHub, a feedback ticket is the best way to route the request to the right VS team. If you link a ticket here I will ensure it is routed appropriately and champion it internally.

Yep, done here: https://developercommunity.visualstudio.com/t/Proposal:-Always-add-simple-timing-to-an/1597054

Closing this issue here and hoping it can be fixed by VS feedback! 🤞
