### ISSUE TITLE
Package dependencies appear with yellow triangles when using SDKs before 3.1.4xx

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7972]
_Originally reported in [this feedback ticket](https://developercommunity.visualstudio.com/t/Visual-Studio-16115---All-NuGet-Packag/1566613)._

When a customer pins their SDK to a version before 3.1.4xx (such as 3.1.120), package reference nodes will appear in Solution Explorer with yellow triangles.

This is only a cosmetic issue. They packages continue to function correctly.

In 3.1.4xx we changed how package references were exposed to the project system in the SDK. The project system works best with the new format, but we also added a best effort fallback to help customers who have pinned old versions of the SDK.

The bug originates from here, where we have a best effort fallback logic to handle the old style of data:

https://github.com/dotnet/project-system/blob/9471d60f646325f98ffa973485f1bf07dd07b4b2/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs#L188

In this code, `targetFrameworkName` has a value such as `".NETStandard,Version=v2.0"`, yet `targetFramework` has a value of `"netstandard2.0"`. These values are from different domains and cannot be directly compared without some kind of translation first.

The problem goes away if you increase the version of the SDK you are using to 3.1.4xx or higher.

**Comment by tmeschter** [comment]
We don't support arbitrary older versions of the SDK.

**Comment by BradKnowles** [comment]
@tmeschter @drewnoakes This is happening with the .NET Core 3.1, which I thought was supported until December 03, 2022?

**Comment by tmeschter** [comment]
It is supported, via the 3.1.4xx version (or higher) of the SDK.

**Comment by drewnoakes** [comment]
The core runtime is supported, yes. The issue here is an interaction between an older version of the SDK and its interaction with a newer version of VS. I understand the distinction may not be satisfying however.

Is there a reason you cannot update to SDK 3.1.4xx?

**Comment by BradKnowles** [comment]
After doing a little digging, I was able to find the [servicing updates support policy](https://docs.microsoft.com/en-us/dotnet/core/releases-and-support#servicing-updates-1) which confirms what you both are saying.  As a fellow developer I understand the need to discontinue supporting older versions.  Microsoft can't keep supporting everything forever, makes total sense.

However, my dissatisfaction and frustration isn't necessarily in the resolution, it's about the process.  Let me try to explain.
- While this GitHub issue was just created on 2022-MAR-11, the linked feedback ticket was created on 2021-OCT-28, 4 months and 20 days ago.
- At that time, we were using the 3.1.20 SDK which was still in support, as the 3.1.21 SDK wouldn't be released until 2021-NOV-08 (if I'm understanding the support cadence correctly).
- I was very responsive to all requests for more information, providing logs and a sample project that demonstrated the issue.
- Time kept increasing between updates from Microsoft while the problem still exists, in VS 2019 and 2022.  By this time, it had fallen out of support, unbeknownst to me.
- This happened to get revived because I caught the right Twitter thread that @drewnoakes happened to be on.  I didn't even realize you were the one involved on the original ticket until I found the link to post to Twitter 😄  So thanks for re-engaging!
- While I'm the one that filed the ticket, it's affecting everyone on my team.

Can you provide guidance on how best to handle future support issues we may have?
- This was found in the context of my day job, where we all have Visual Studio Professional subscriptions.  Should I have used a different mechanism for support than the Developer Community portal?  Would that have arrived at a solution sooner while things were still technically supported?

To address your question about upgrading, the answer is, it depends :tm:.
- We're using .NET Core 3.1 for AWS Lambda.  They did not natively support .NET 6 until 2022-FEB-24.
- We periodically check the version of .NET Core 3.1 the Lambda runtime uses.  As of today, they are using 3.1.22 (3.1.416 SDK).  I'm not sure when that updated.
- We try to stay in step with AWS so that we can be assured of compatibility and if we need support we can say "We're using the exact same runtime and SDK that Lambda uses."
- If I upgrade to 3.1.416, I'm still out of support with Microsoft, because 3.1.417 was released 2022-MAR-08.  I can't win LOL.
- We have a lot of testing and deployments to do for no new functionality gains that will be difficult to get approved and scheduled.  Definitely a "me" problem I know.

Is my concern of trying to stay in sync with AWS unwarranted?  Should I be worried of using a new SDK and Runtime than what's running natively in Lambda?  Isn't there be a possibility of something working locally but not working once it gets to AWS (testing not withstanding)?

Thanks for the help and feedback, it is appreciated.

**Comment by drewnoakes** [comment]
Firstly, I'm truly sorry that it took so long for your feedback ticket to get to this point. As you can imagine, there are a lot of feedback tickets. Not all of them get in front of the engineering teams, but a lot still do. We spend a lot of time on feedback tickets in addition to our regular product work. There is, unfortunately, much more work than we can do, so we have to prioritize based on impact to a large number of customers, especially for cases where no workaround exists.

> Should I have used a different mechanism for support than the Developer Community portal?

There are other channels for support, though I am not an expert on those. Does your organization have a sales contact within Microsoft whom you could ask?

> To address your question about upgrading, the answer is, it depends

To be clear, you can use newer versions of the SDK to target older versions of the runtime. For example, you can use the .NET SDK 6.x to build for .NET Core 3.1 (or even for .NET Framework). This will also allow you to use newer versions of the compiler and language. I want to be careful about giving you guidance here as I am not intimate with AWS Lambda, but my sense is that you should be able to unpin the SDK (i.e. remove that from global.json, or just remove global.json entirely) and have everything work correctly so long as your projects target the correct `TargetFramework` (which seems to be `netcoreapp3.1` from your description). Unpinning the SDK means that you're always using the version that ships with VS, which will avoid the kind of issue you're experiencing here.
