### ISSUE TITLE
"Use apphost" checkbox missing from remodeled app designer for .NET console app project

### ISSUE THREAD

**Issue by AArnott** [dotnet/project-system#7976]
## Visual Studio Version

Dev17.2 Preview 3 (32309.498.main)

## Summary

The app designer for a .NET Console Application has no discoverable way to disable the apphost that the project system spawns the app under (whether with Debug or Execute) as it used to. 
This setting would control the `UseAppHost` msbuild property. It is useful for at least a few things, including working around https://github.com/dotnet/msbuild/issues/7466.

## Steps to Reproduce

1. Create a new .NET Console Application
2. Right-click on the project node in Solution Explorer and click Properties
3. Use "search properties" to find "apphost", "host" or other variants. Or just look around every promising section manually.

## Expected Behavior

Find a "Use apphost" checkbox.

## Actual Behavior

No such checkbox to be found.

## User Impact

Inability to workaround issues created by the app host.

**Comment by rainersigwald** [comment]
I think it might be reasonable to have this checkbox but please talk to @baronfel about how interested the .NET SDK is to expose this prominently; _most_ apps should accept the default (use an apphost so that you launch `yourapp.exe` instead of `dotnet.exe yourapp.dll`).

**Comment by drewnoakes** [comment]
From https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#useapphost is looks like we'd only want this option to be visible from .NET Core 3.0 onwards.

If @baronfel agrees with this request, it should be straightforward to add on our side.

**Comment by tmeschter** [comment]
Adding the checkbox is easy; the hard part if figuring out if we should.

**Comment by baronfel** [comment]
I would prefer not to expose this flag explicitly. The primary reason for this is that for the .NET 7 timeframe we are looking at making two changes that will make the use of AppHosts much more regular/predictable for end users based on their projects' use cases:

* https://github.com/dotnet/sdk/issues/23540 will make certain kinds of executables and applications produce RID-specific artifacts by default (and therefore use an apphost)
* https://github.com/dotnet/sdk/issues/23545 will make portable apps no longer produce an apphost by default

As a result, the apphost becomes an emergent property of the application's execution model instead of a top-level property.

**Comment by adamint** [comment]
Closing due to request not to complete this.
