### ISSUE TITLE
Configured value visibility conditions are not working correctly under specific circumstances

### ISSUE THREAD

**Issue by japarson** [dotnet/project-system#8354]
## Visual Studio Version
Microsoft Visual Studio Enterprise 2022 (64-bit) - main
Version 17.4.0 Preview 1.0 [32721.605.main]

## Summary
When setting a `ConfiguredValueVisibilityCondition` for certain rule editor types, the UI hurts itself in confusion. This seems to only occur under certain conditions that I haven't quite nailed down, but I tried to capture them under the gifs below:

### StringProperty
![string_prop](https://user-images.githubusercontent.com/59936622/180904228-baf42adc-ef5c-4909-81a8-3fc76a0ce79c.gif)

### StringProperty w/ File Picker Metadata
![file_picker](https://user-images.githubusercontent.com/59936622/180903509-d73f5528-83a1-4bc3-bfac-5c7f193ebc12.gif)

### ConfiguredValueVisbilityCondition
```
(or
	(eq (evaluated "ConfigurationGeneralPage" "TargetPlatformIdentifier") "ios")
	(eq (evaluated "ConfigurationGeneralPage" "TargetPlatformIdentifier") null))
```

## Steps to Reproduce

1. Create a .NET Maui app.
2. Follow the steps in the gifs above.
   - The string property is `iOS -> On Demand Resources -> Initial Tags`.
   - The string property w/ file picker metadata is `iOS -> Bundle Signing -> Custom Entitlements`.

## Expected Behavior
The UI displays configured values only for the iOS target framework.

## Actual Behavior
The UI displays configured values for other types of target frameworks, even a blank one?

## User Impact
Confusion.

**Comment by japarson** [comment]
@adamint @drewnoakes

**Comment by adamint** [comment]
huh, my first response is confusion too. I'll look into this for 17.4

**Comment by adamint** [comment]
update from chat, after investigation

There is one bug, and one feature that needs to be added here:
- the bug is that the observable value filter is not refreshed after property update
- the feature, from chat:

[11:10 AM] Adam Ratzman
the issue is that your condition evaluates to true for propertyvalues that have no TargetPlatformIdentifier (a propertyvalue that has multiple evaluated values for different configurations), even if none of those propertyvalue's evaluated values have a configuration that include ios

I'll add a function (has-multiple-evaluated-values) that returns true if the PropertyValue has multiple child evaluated values. Additionally, the ConfiguredVisibilityConditionEvaluator needs to be extended to also contain a reference to the PropertyValue that it's linked to.

Here, you don't want has-multiple-evaluated-values to return true because you're only looking for either:
-no configuration set
-a configuration explicitly containing iOS

You can change your expression to
(and (not (has-multiple-evaluated-values "your-page" "your-property")) (your-original-expression))

**Comment by adamint** [comment]
PR tracked in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/415825
