### ISSUE TITLE
.NET Project System no longer in //index

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8488]
For example, the new `LanguageServiceHost` class is not found.

http://index/?query=LanguageServiceHost

Is this fallout from recent infrastructure changes?

**Comment by MiYanni** [comment]
Closing since these are being published correctly.
![image](https://user-images.githubusercontent.com/17788297/190835818-dc6bde8b-72fc-46d8-b8d8-d82dc937781a.png)

![image](https://user-images.githubusercontent.com/17788297/190835826-59b26aa3-5b8d-41e6-967d-e6fe53856cf8.png)

![image](https://user-images.githubusercontent.com/17788297/190835841-5a57a987-3c95-46ba-ab31-f224e4ae4602.png)

Index is only refreshed once a week, and we publish them as part of our nightly scheduled build.

**Comment by drewnoakes** [comment]
> Index is only refreshed once a week, and we publish them as part of our nightly scheduled build.

That code was merged a few weeks back, so I would have expected it to have refreshed.

I'll keep an eye on it in future. Thanks for investigating.
