### ISSUE TITLE
Create unit test to ensure all categories in rule file. 

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8552]
We need to make sure that all categories used in a rule file are present in the <Categories> metadata on the top of the file. If not present, they are not correctly picked up when a different language is set, i.e., Spanish. An example of a recent bug: [AZDO#1631080](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1631080).

Having a unit test that ensures this is followed will help us not miss these localization bugs.

**Comment by tmeschter** [comment]
Note that a page that extends another page may not need to define categories (and indeed _shouldn't_ redefine an existing category), and the test needs to take that into account.

We should also verify that each property explicitly states the category it belongs to; otherwise it will get dropped into a generated "General" category which won't have a translated name.
