### ISSUE TITLE
Build acceleration stabilization

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8760]
- [x] #8733 
- [x] Add `AccelerateBuildsInVisualStudio` to MSBuild's XSD for IntelliSense support when editing project files (https://github.com/dotnet/msbuild/pull/8337)
- [x] #8814
- [x] #8799
- [x] #8801
- [x] #8798
- [x] #8804
- [x] #8865

**Comment by Meligy** [comment]
Any reason that this applies to VS build only and not `dotnet build` too?

**Comment by drewnoakes** [comment]
> Any reason that this applies to VS build only and not dotnet build too?

`dotnet build` is a one-shot operation today. This feature requires a long-running process with pre-computed information about all the projects so that when a build request is received it can be addressed immediately without having to evaluate the project or call any MSBuild targets. Most of the perf win comes from not actually calling MSBuild.

We are discussing approaches that might make this work on the CLI, but it's too early to say whether that's feasible or not.

**Comment by Genbox** [comment]
> We are discussing approaches that might make this work on the CLI, but it's too early to say whether that's feasible or not.
A lot of us have asked ourselves this question. Is there an issue tracking the progress on this feature?

**Comment by drewnoakes** [comment]
> A lot of us have asked ourselves the question about why it is only VS and not dotnet

I tried to answer the technical reasons for that above. If anything's unclear, let me know.

> Is there an issue tracking the progress on this feature?

I'm not aware of one. I know it's on the team's radar and would likely build on top of the MSBuild server work started in https://github.com/dotnet/msbuild/issues/7315. I expect it would be a large undertaking, and I don't want to speak to their priorities.
