### ISSUE TITLE
Disable build acceleration when pre/post build steps exist

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8804]
If a project has custom pre or post build steps specified, we may wish to opt-out of build acceleration for that project. We cannot know whether those steps are safe to skip or not, and it's probably best to err on the side of caution.

That said, if the project explicitly opts in, we should respect that. This would only effect the default, when no `AccelerateBuildsInVisualStudio` property is specified.

Note that we cannot detect all pre/post build steps, as there are many ways to hook these up. We can, however, detect those specified via the project properties UI.

**Comment by Dunge** [comment]
Quick remark from my usage

I'm using [slow-cheetah](https://github.com/microsoft/slow-cheetah) as a nuget to transform .config files based on the build configuration. While my projects themselves don't have post build steps, I believe this tool create one internally. Took me a while to understand why some config files would _sometimes_ not get transformed properly, until I realized this happens only since I enabled Visual Studio Build Acceleration.

So yeah, this cause an unfortunate side effect that can create a lot of confusion from unsuspecting users.

**Comment by drewnoakes** [comment]
@Dunge thanks very much for bringing this to our attention. We'll investigate whether there's something to improve in the product here. I've filed #8886 to track that specific scenario. Let's continue the discussion there.

**Comment by drewnoakes** [comment]
It's not clear that pre/post build events necessarily require us to disable build acceleration. It really depends upon what those steps do. I'm going to close this out for now but we can revisit in the face of further feedback.

**Comment by derekpiasecki** [comment]
FYI, there is a somewhat related issue https://github.com/dotnet/project-system/issues/9421 about the post-build event not running when a build is accelerated.
