### ISSUE TITLE
FastUpToDate - Support code generation during build

### ISSUE THREAD

**Issue by yfital** [dotnet/project-system#8878]
## Summary

We have a large solution that includes a custom pre-build code generation:
* We came before source code generation (the transition isn't trivial at this point although we use Roslyn all the way)
* It's a heavy flow (it can take several seconds due to heavy Roslyn recursive usage)
* The code generation(s) does 1 to 1 & 1 to many outputs.
* Almost all outputs are code files (.cs)
* All outputs are used inside the same project, e.g. project A will generate a .cs which is needed for project A to compile (partials for instance)

We're running the code generation at this point:

```
  <Target Name="GenerationInsideVisualStudio" BeforeTargets="PreBuildEvent;PrepareResources" DependsOnTargets="ResolveReferences" />
```

Which I found is the earliest possible which is done after I actually have the relevant reference DLLs available (which I need for generation).

In case a generation is actually made (returned files from the generation call) I add them directly to the Compile and FileWrites ItemGroups.

I've thought about opening this as a bug, but in the end, I think it's just currently not supported due to the basic concept of:
```
The set of project items was changed more recently (XXX) than the last successful build start time (YYY), not up-to-date.
```
Attempts to add the files to the UpToDateCheckBuilt/Ouptut are irrelevant as they are (unless I'm mistaken) needed for files that the fast up-to-date mechanism is NOT aware of (and in this case, they are, just not in the correct time).

2nd build will always re-run msbuild (including our generation):
* I've added logic to the generation to avoid reapplying code changes, but the logic to detect that is slow (almost the same as the build)
* No ItemGroups are changed

3rd build will always skip due to fast up-to-date now being valid (the item groups are not changes in 2nd build)

## User Impact
As most of our projects use the pre-build code generation, the fast up-to-date mechanism is just non-functional causing very slow builds

**Comment by drewnoakes** [comment]
Thanks for the detailed explanation of your situation.

Two questions:

1. Are the generated files checked in to source control?
2. If, after your 3rd build, you modify one of the inputs such that the generation runs again on your 4th build, are you up to date on the 5th build?

One possibility to investigate is whether your generators are deleting then recreating the source files. From the project's perspective, that would constitute a change in the set of items. We may be able to improve that scenario. Though if that is what's happening and you own the generation, perhaps you could open the file, truncate it, then rewrite instead of deleting and recreating.

**Comment by yfital** [comment]
Hey Drew,

1. No, the generated files are not checked into source control
2. Currently yes, probably due to the fact that once I change a file, my post-generation target updates the entire Compile set by removing & re-adding the generated files again via glob.
This can be optimized to be more specific, I just don't think it will help as the fast up-to-date already notifies of a problem)

```
18:03:13:495	WARNING: Potential build performance issue in 'Press.Common.csproj'. The project does not appear up-to-date after a successful build: Input Compile item 'C:\WorkSpaces\OCB2\pc\Src\Press\Common\Calibrations\CalibrationConfigEntity.DataType.gen.cs' (2023-02-28 18:02:56.700) has been modified since the last successful build started (2023-02-28 18:02:52.040), not up-to-date. See https://aka.ms/incremental-build-failure.
```

Although the file was already in the Compile setlist during builds 4 & 5 (though modified).

To make sure I understood you correctly here:
"Though if that is what's happening and you own the generation, perhaps you could open the file, truncate it, then rewrite instead of deleting and recreating."
You refer to the "set items file" (which isn't an actual file... what am I missing?)
If you referred to my generated files, I do not update a file in case it has not changed, I take care of that in the generation itself (I just don't want to reach that point at all, as the knowledge of whether an output should change can take some time,  I have a lot of optimizations there as well)

One of my attempts was to constantly remove all items from Compile which are generated (via glob) and return them, hence causing them to always be in the same order, but that didn't help as well

I'm now following another suggestion I found that recommended outputting all the files to an external folder (Intermediates ) but that's causing me more issues than solutions :)

**Comment by drewnoakes** [comment]
> You refer to the "set items file" (which isn't an actual file... what am I missing?)

I was referring to the "set of items", which is what's causing your build as per:

> The set of project items was changed more recently (XXX) than the last successful build start time (YYY), not up-to-date.

Specifically, the set of items would be, for example `Class1.cs` and `Class2.cs`. If you then generate `Generated.cs`, VS sees the new file appear on disk and the set of items now contains all three.

If during the build, you delete `Generated.cs` then recreate `Generated.cs`, VS sees the file system's _delete_ event, then the _create_ event. The set of items goes from 3 to 2 then back to 3. This constitutes a change (today at least) and will leave the project in a dirty state, causing an extra build (or endless builds, depending upon whether you delete the file even if it's up-to-date). To address this, you could just overwrite the existing file so that the set of items never changes.

> I'm now following another suggestion I found that recommended outputting all the files to an external folder (Intermediates ) but that's causing me more issues than solutions :)

Given you're not committing the generated files to version control, sticking them in the intermediate folder (`obj`) is a good idea as that's usually ignored by your version control system, but it won't have any impact on your up-to-date check issue.

**Comment by drewnoakes** [comment]
You might find this repo helpful. It provides a sample of generating code during build:

https://github.com/drewnoakes/generate-code-sample

**Comment by yfital** [comment]
Hey,

Thank you for the detailed answers.
I've indeed looked at that repo (I found it by mistake just before you sent it) and I'm happy to say that with some tweaks I've managed properly maintained the generation and still have a valid FUTD.

The repo is **not complete**, it doesn't include the handling of already created files for instance, and some minor fixes.

I still think that my original request makes sense, the move to the intermediate folder feels superficial and annoying to the developers as well, and the boilerplate code only shows now when you press "show all files".

Also file nesting is a serious issue as the simple globbing I had before (filename --> filename.identity.cs) is now very complex (not sure it's worth it).

I'd be happy if a more wholesome solution will be provided, but as a workaround, the basic concepts of:
https://github.com/drewnoakes/generate-code-sample
are indeed enough.

**Comment by drewnoakes** [comment]
Glad to hear you made progress. I have a few follow up questions on your comments.

> The repo is not complete, it doesn't include the handling of already created files for instance, and some minor fixes.

If the generated file already exists on disk, I would expect this to work. If you provide more information about this please, I can investigate extending the [repo](https://github.com/drewnoakes/generate-code-sample).

> the move to the intermediate folder feels superficial and annoying

That move is optional. It's only to prevent the file being added to version control, which you mentioned as a goal in your case.

> the [generated] code only shows now when you press "show all files"

In the sample repo, the `Compile` item for the generated file is added in a target that VS doesn't see. If you wanted the file to appear in Solution Explorer, you could move it. I updated the sample repo to handle this properly in https://github.com/drewnoakes/generate-code-sample/commit/41e10267a361c723aa781f23c7b5169b7259481c, along with some other fixes.

> Also file nesting is a serious issue as the simple globbing I had before (filename --> filename.identity.cs) is now very complex (not sure it's worth it).

You can more easily control nesting with the `DependentUpon` metadata on items.

See `Foo.cs` in this example:

![image](https://user-images.githubusercontent.com/350947/222992563-e9ef4c28-181f-4df3-ae52-aaa318f344a2.png)

These items are essentially:

```xml
<ItemGroup>
  <GeneratorInput Include="Foo.input" />
  <Compile Include="obj\Debug\net6.0\Foo.cs">
    <Link>Foo.cs</Link>
    <DependentUpon>Foo.input</DependentUpon>
  </Compile>
</ItemGroup>
```

---

At this point, if there is a product change to consider here I think it would be to better handle when a build removes then re-adds the same item(s), which lead us to think we're out of date due to _The set of project items was changed more recently than the last successful build start time_. If a build does that, we could probably continue safely with the existing timestamp checks. Let me know if I'm missing anything.

We would need to be considerate of the scenario:

1. Build
2. Delete a source file
3. Build again
4. Undelete file
5. Build again

The undelete restores the file with its original timestamp, which is _before_ the last build. In this case though I think the set-of-files check should be fine.

**Comment by drewnoakes** [comment]
I've filed https://github.com/dotnet/project-system/issues/8933 to track improving the item set monitoring, which should help in your scenario.

To your other points I'm not clear what we can do to improve the situation. MSBuild projects contain many kinds of items, and we need to know which item types to consider, and with what semantics. In general we hope the complexity associated with this is pushed into reusable/consumable build assets (like the .NET SDK, MSBuild common targets, or a NuGet package's bundled `.targets` files).
