### ISSUE TITLE
Unable to set same value across all configurations in Conditional compilation symbols property

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8901]
When selecting the option to "Use the same value across all configurations", the UI briefly changes the control correctly but reverts to show all configurations.

![conditional-compilation-symb-bug](https://user-images.githubusercontent.com/8518253/223292493-15a24787-bcb5-41ce-8e43-da75819eb0d0.gif)

**Comment by adamint** [comment]
@melytc can you send the .csproj for this project

**Comment by melytc** [comment]
it's a new c# console app

**Comment by adamint** [comment]
Ah! I see what's going on.

Since the evaluated values for this property will **always** be different (see DEBUG) in the top evaluated value, while the bottom has RELEASE, they can never be simplified. See PropertyValue.Create#85 for associated code. 

The correct course of action is to disable the "Use single value for configurations" button for this property.

**Comment by adamint** [comment]
This is only an issue for DefineConstants (c#), not vb
