### ISSUE TITLE
Yellow triangle on Analyzer with full path displayed solved in 16.5 preview, back in 17.6 preview

### ISSUE THREAD

**Issue by ebfortin** [dotnet/project-system#8936]
In #4893 the OP was describing a problem where Analyzers showed the full patch to the Analyzer assembly and a Yellow warning triangle. The issue has been closed as it has been resolved in 16.5 preview. However I just got the same error described in 17.6 preview 2.0. 

![image](https://user-images.githubusercontent.com/5997017/227779292-86d987f0-7208-43c0-8125-312fa7d91d97.png)

I have nothing to diagnose that problem. All I can say it that I updated from .NET 5 to .NET 7 on four projects in a solution and that's when I encountered the problem. I did all the different thing you can do with doing that upgrade breaks things up : delute .vs dir, clear nuget cache and restore, force load of project dependencies. Nothing works.

I also have yellow triangle on all of my dependencies.

**Comment by drewnoakes** [comment]
@ebfortin when yellow triangles appear on all dependencies, it's usually a sign that the design-time build has failed.

Rather than detail this here, I've added a doc about this in the following PR: https://github.com/dotnet/project-system/pull/8948

Could you please review that doc and see whether it contains enough information to help you diagnose the issue you're encountering?

Alternatively, are you able to provide a minimal repro for the issue here so that we can investigate?

Thanks.

**Comment by drewnoakes** [comment]
I cannot repro this, and the code here has evolved enough that I supsect it's fixed. If anyone sees this and has repro steps they can share, please do.
