### ISSUE TITLE
Add readme.md to the csproj file fails due to a syntax error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9032]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/add-readmemd-to-the-csproj-file-fails-d/1556889). Please vote and comment there to make sure your voice is heard._

---

When selecting a readme.md in the csproj property window the "wizard" changes the file and adds  

```xml
<ItemGroup>
  <None Update="ReadMe.md">
    <Pack>True</Pack>
  </None>
</ItemGroup>
```

The issue is that it generates a Update and not a Include making the publish fail as it can't find the readme.md file 

```xml
<None Include="ReadMe.md" pack="true" PackagePath="." />
```

![B9524d4ff8ea8425abf214156784cb780637701622119622256_20211018-155649-image](https://github.com/dotnet/project-system/assets/350947/d7210bb9-47a7-4066-8045-1605df61329d)

---

## Workaround

In my version of visual studio, I navigate to the package configuration of the project properties, There set the `<a target='_blank' href="http://readme.md">readme.md</a>` you will see that VS sets the wrong value it will set update instead of Include.

**Comment by drewnoakes** [comment]
Note to MSFT employees, there's some relevant private discussion with the customer on the feedback ticket.

**Comment by MiYanni** [comment]
## Repro Steps
So, a 'symptom' of the issue exists (`Update` instead of `Include`), but the actual issue (`Pack` failing) seems to be user error(?). The description of the issue took me a minute to parse and test. Let me explain clearly:

1. Create C# console app to use to test.
2. Add a ReadMe.md file (include text in the file, such as `12345`) in the same folder as the .csproj file.
    - There is a comment from the vendor on the original feedback ticket saying that `Update` occurs when the file is in the project hierarchy and `Include` occurs when the file it outside the hierarchy, such as the folder above the .csproj file.
    - You must include content in the file. Otherwise, it will throw [NU5040](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5040) when running the Pack operation.
3. Open the Property Pages for the project.
4. Go to `Package > General > README` section.
5. Hit the Browse button and select the ReadMe.md file you created.

![image](https://github.com/dotnet/project-system/assets/17788297/12e38661-ee92-4a19-8db5-63ac127bfdb1)

6. Double click (or right click > Edit Project File) on the project in the Solution Explorer.
7. Observe that a None item with `Update` was created (along with the property `PackageReadmeFile`).

![image](https://github.com/dotnet/project-system/assets/17788297/f34973f1-9103-4f80-85bf-91dba9fc750e)

8. Right click on the project in Solution Explorer and select `Pack`.
9. Observe that the Pack operation will succeed.

![image](https://github.com/dotnet/project-system/assets/17788297/cf6df35e-fa75-44a6-b9c5-fc98e5e471d0)

10. Remove the line `<PackagePath>\</PackagePath>` from the None item.
11. Run the Pack operation again on the project.
12. Observe that the Pack operation will fail with the same NU5039 error as seen in the original feedback ticket.

![image](https://github.com/dotnet/project-system/assets/17788297/7bfdfd8a-5842-4466-ae0a-949dfc9af014)

## Summary
The original feedback ticket thinks that because it says `Update`, that's the issue. If you look closer, you'll see they don't have `PackagePath` metadata on their None item. That is the actual issue. When I added [the `PackageReadmeFile` property](https://github.com/dotnet/project-system/pull/7440), I made sure to handle it adding PackagePath. I don't know how the user ended up without it in their file. In their first screenshot, they show it missing. In their follow-up screenshot, `<PackagePath>\</PackagePath>` is present. I believe they confused the vendor to think that `Update` was the issue, when it was not.

For why `Update` is there... that seems to be a CPS issue. Looking at the code, I simply tell CPS to add the None item. In this part of the code, it is aware that no None item existed prior for this purpose.
https://github.com/dotnet/project-system/blob/cd3bfb02177713781965264746ec2be7de9818c6/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageFilePropertyValueProviderBase.cs#L112-L116

However, it being `Update` doesn't cause any issues by itself. This is why we haven't gotten more reports about it.
