### ISSUE TITLE
Form1.Designer.cs file is lost when changing the access modifier from "No code generation" to "Public" for the Form1.resx file

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/project-system#9034]
## Visual Studio Version

Version 17.7.0 Preview 2.0 [33718.333.main]

**Have you experienced this same issue with previous previews of VisualStudio?**
Yes, it is not a regression issue, also can repro on VS 16.11.26.

## Steps to Reproduce

1. Create a C# .NET Core WinForms application.
2. Open Form1.resx file.
3. Change the access modifier from "No code generation" to "Public".
4. Observe solution explorer. 

## Expected Behavior
Form1.Designer.cs file exist and generate Form11.Designer.cs file under Form1.resx file.
![image](https://github.com/dotnet/project-system/assets/94418985/18731280-6657-457c-a49a-f9b88747ee6c)

## Actual Behavior
Form1.Designer.cs file is lost.
![image](https://github.com/dotnet/project-system/assets/94418985/50973bc0-ba3c-4f0b-9e3c-7b9929d4f1b9)

**Comment by drewnoakes** [comment]
The key problem here is that both `Form1.cs` and `Form1.resx` want to make `Form1.Designer.cs`. There's a difference in behaviour between legacy and SDK-style here.

Legacy avoids the conflict by appending a `1`, leading to `Form11.Designer.cs` (note 11, not 1).

SDK-style seems to fail to create the file altogether.

We should investigate where this collision avoidance is occurring, and why it differs.

**Comment by adamint** [comment]
So, per the comments in the legacy resource designer we don't want users to actually modify this file. You get a warning when trying to do anything *except* change this accessibility combobox. Since I can't find the root cause at a cursory glance, it's a legacy editor, and it's behavior we want to discourage anyway, I think it's enough to just add the same warning as appears when trying to modify the values in the file.
