### ISSUE TITLE
Conditons on ItemGroups Don't Work on Non-SDK Projects

### ISSUE THREAD

**Issue by mruiz2112** [dotnet/project-system#9577]
### Issue Description

Adding a condition on an ItemGroup, i.e. `<ItemGroup Condition="false">`, does not work for non-SDK projects. The condition seems to be ignored and whatever is inside the ItemGroup will be added/executed. I've noticed this to be true within a csproj file as well as in a Directory.Packages.props file.

My company has a few large non-SDK web apps that we can't upgrade to SDK style so it would be nice to have this fixed.

### Steps to Reproduce

[WebApplication_NonSDK.zip](https://github.com/user-attachments/files/17497045/WebApplication_NonSDK.zip)

I uploaded a small sample solution with an ItemGroup, `<ItemGroup Condition="false">`, that adds a PackageReference. Despite the condition clearly evaluating to false, the PackageReference is added anyway. Changing the syntax to this fixes the issue:

```
<Choose>
    <When Condition="false">
      <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
      </ItemGroup>
    </When>
  </Choose>
```

However, it is confusing and inconvenient that the conditional on the ItemGroup does not work, especially since it only seems to affect non-SDK projects.

### Expected Behavior

The PackageReference is NOT added to the project

### Actual Behavior

The PackageReference is added to the project

**Comment by drewnoakes** [comment]
@mruiz2112 your issue has been moved to the .NET Project System repo which is the codebase/team for SDK-style projects, while your issue is actually related to non-SDK-style projects. The code/team for that system is internal to Microsoft, and doesn't track their work here on GitHub.

Could you please file a feedback ticket per https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022 so that it can be routed to them? If you share the link to the ticket here I'll make sure it gets routed correctly.

Thanks.

**Comment by mruiz2112** [comment]
@drewnoakes sorry for the delayed response, here is the ticket I created: https://developercommunity.visualstudio.com/t/Conditons-on-ItemGroups-Dont-Work-on-No/10795615

**Comment by drewnoakes** [comment]
Thanks @mruiz2112, I've routed it to the team that owns non-SDK-style C#/VB projects.

> My company has a few large non-SDK web apps that we can't upgrade to SDK style

Out of curiosity, what issue prevents the upgrade to SDK-style?

**Comment by mruiz2112** [comment]
AFAIk SDK-style doesn't natively support Asp.Net WebApplications, which is what we have (they are old)
